// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: phi/voting/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgCreateElection opens a poll.
type MsgCreateElection struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	// Unique election id.
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Question/title.
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// Choice labels (at least two).
	Options []string `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
	// Credential template that gates eligibility.
	RequiredTemplateId string `protobuf:"bytes,5,opt,name=required_template_id,json=requiredTemplateId,proto3" json:"required_template_id,omitempty"`
	// Expected issuer DID of that template.
	RequiredIssuerDid string `protobuf:"bytes,6,opt,name=required_issuer_did,json=requiredIssuerDid,proto3" json:"required_issuer_did,omitempty"`
	// Voting window (Unix seconds); 0 start means "open immediately".
	VotingStart int64 `protobuf:"varint,7,opt,name=voting_start,json=votingStart,proto3" json:"voting_start,omitempty"`
	VotingEnd   int64 `protobuf:"varint,8,opt,name=voting_end,json=votingEnd,proto3" json:"voting_end,omitempty"`
}

func (m *MsgCreateElection) Reset()         { *m = MsgCreateElection{} }
func (m *MsgCreateElection) String() string { return proto.CompactTextString(m) }
func (*MsgCreateElection) ProtoMessage()    {}
func (*MsgCreateElection) Descriptor() ([]byte, []int) {
	return fileDescriptor_35a87a98f587e9e9, []int{0}
}
func (m *MsgCreateElection) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateElection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateElection.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateElection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateElection.Merge(m, src)
}
func (m *MsgCreateElection) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateElection) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateElection.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateElection proto.InternalMessageInfo

func (m *MsgCreateElection) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateElection) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MsgCreateElection) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MsgCreateElection) GetOptions() []string {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *MsgCreateElection) GetRequiredTemplateId() string {
	if m != nil {
		return m.RequiredTemplateId
	}
	return ""
}

func (m *MsgCreateElection) GetRequiredIssuerDid() string {
	if m != nil {
		return m.RequiredIssuerDid
	}
	return ""
}

func (m *MsgCreateElection) GetVotingStart() int64 {
	if m != nil {
		return m.VotingStart
	}
	return 0
}

func (m *MsgCreateElection) GetVotingEnd() int64 {
	if m != nil {
		return m.VotingEnd
	}
	return 0
}

type MsgCreateElectionResponse struct {
}

func (m *MsgCreateElectionResponse) Reset()         { *m = MsgCreateElectionResponse{} }
func (m *MsgCreateElectionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateElectionResponse) ProtoMessage()    {}
func (*MsgCreateElectionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_35a87a98f587e9e9, []int{1}
}
func (m *MsgCreateElectionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateElectionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateElectionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateElectionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateElectionResponse.Merge(m, src)
}
func (m *MsgCreateElectionResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateElectionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateElectionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateElectionResponse proto.InternalMessageInfo

// MsgCastVote casts an anonymous ballot.
//
// The signer (voter) is only the transaction fee payer — it is NOT the voter's
// identity and is not linked to the ballot; anonymity relies on using a relayer/
// throwaway account plus the identity-revealing-nothing BBS+ proof. The chain
// verifies eligibility_proof against the template issuer key with the bound nonce
// SHA256(election_id ‖ nullifier), then deduplicates the nullifier.
type MsgCastVote struct {
	// Transaction fee payer (relayer/throwaway) — not the voter identity.
	Voter string `protobuf:"bytes,1,opt,name=voter,proto3" json:"voter,omitempty"`
	// Election being voted in.
	ElectionId string `protobuf:"bytes,2,opt,name=election_id,json=electionId,proto3" json:"election_id,omitempty"`
	// Per-election nullifier (one-vote-per-nullifier).
	Nullifier []byte `protobuf:"bytes,3,opt,name=nullifier,proto3" json:"nullifier,omitempty"`
	// Serialized BBS+ selective-disclosure proof of eligibility (verified, not stored).
	EligibilityProof []byte `protobuf:"bytes,4,opt,name=eligibility_proof,json=eligibilityProof,proto3" json:"eligibility_proof,omitempty"`
	// Chosen option index into the election's options.
	OptionIndex uint32 `protobuf:"varint,5,opt,name=option_index,json=optionIndex,proto3" json:"option_index,omitempty"`
}

func (m *MsgCastVote) Reset()         { *m = MsgCastVote{} }
func (m *MsgCastVote) String() string { return proto.CompactTextString(m) }
func (*MsgCastVote) ProtoMessage()    {}
func (*MsgCastVote) Descriptor() ([]byte, []int) {
	return fileDescriptor_35a87a98f587e9e9, []int{2}
}
func (m *MsgCastVote) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCastVote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCastVote.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCastVote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCastVote.Merge(m, src)
}
func (m *MsgCastVote) XXX_Size() int {
	return m.Size()
}
func (m *MsgCastVote) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCastVote.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCastVote proto.InternalMessageInfo

func (m *MsgCastVote) GetVoter() string {
	if m != nil {
		return m.Voter
	}
	return ""
}

func (m *MsgCastVote) GetElectionId() string {
	if m != nil {
		return m.ElectionId
	}
	return ""
}

func (m *MsgCastVote) GetNullifier() []byte {
	if m != nil {
		return m.Nullifier
	}
	return nil
}

func (m *MsgCastVote) GetEligibilityProof() []byte {
	if m != nil {
		return m.EligibilityProof
	}
	return nil
}

func (m *MsgCastVote) GetOptionIndex() uint32 {
	if m != nil {
		return m.OptionIndex
	}
	return 0
}

type MsgCastVoteResponse struct {
}

func (m *MsgCastVoteResponse) Reset()         { *m = MsgCastVoteResponse{} }
func (m *MsgCastVoteResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCastVoteResponse) ProtoMessage()    {}
func (*MsgCastVoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_35a87a98f587e9e9, []int{3}
}
func (m *MsgCastVoteResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCastVoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCastVoteResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCastVoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCastVoteResponse.Merge(m, src)
}
func (m *MsgCastVoteResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCastVoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCastVoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCastVoteResponse proto.InternalMessageInfo

// MsgCloseElection closes a poll early (creator only).
type MsgCloseElection struct {
	Creator    string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	ElectionId string `protobuf:"bytes,2,opt,name=election_id,json=electionId,proto3" json:"election_id,omitempty"`
}

func (m *MsgCloseElection) Reset()         { *m = MsgCloseElection{} }
func (m *MsgCloseElection) String() string { return proto.CompactTextString(m) }
func (*MsgCloseElection) ProtoMessage()    {}
func (*MsgCloseElection) Descriptor() ([]byte, []int) {
	return fileDescriptor_35a87a98f587e9e9, []int{4}
}
func (m *MsgCloseElection) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCloseElection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCloseElection.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCloseElection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCloseElection.Merge(m, src)
}
func (m *MsgCloseElection) XXX_Size() int {
	return m.Size()
}
func (m *MsgCloseElection) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCloseElection.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCloseElection proto.InternalMessageInfo

func (m *MsgCloseElection) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCloseElection) GetElectionId() string {
	if m != nil {
		return m.ElectionId
	}
	return ""
}

type MsgCloseElectionResponse struct {
}

func (m *MsgCloseElectionResponse) Reset()         { *m = MsgCloseElectionResponse{} }
func (m *MsgCloseElectionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCloseElectionResponse) ProtoMessage()    {}
func (*MsgCloseElectionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_35a87a98f587e9e9, []int{5}
}
func (m *MsgCloseElectionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCloseElectionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCloseElectionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCloseElectionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCloseElectionResponse.Merge(m, src)
}
func (m *MsgCloseElectionResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCloseElectionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCloseElectionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCloseElectionResponse proto.InternalMessageInfo

// MsgCancelElection cancels a poll before any vote (creator only).
type MsgCancelElection struct {
	Creator    string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	ElectionId string `protobuf:"bytes,2,opt,name=election_id,json=electionId,proto3" json:"election_id,omitempty"`
}

func (m *MsgCancelElection) Reset()         { *m = MsgCancelElection{} }
func (m *MsgCancelElection) String() string { return proto.CompactTextString(m) }
func (*MsgCancelElection) ProtoMessage()    {}
func (*MsgCancelElection) Descriptor() ([]byte, []int) {
	return fileDescriptor_35a87a98f587e9e9, []int{6}
}
func (m *MsgCancelElection) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelElection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelElection.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelElection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelElection.Merge(m, src)
}
func (m *MsgCancelElection) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelElection) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelElection.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelElection proto.InternalMessageInfo

func (m *MsgCancelElection) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCancelElection) GetElectionId() string {
	if m != nil {
		return m.ElectionId
	}
	return ""
}

type MsgCancelElectionResponse struct {
}

func (m *MsgCancelElectionResponse) Reset()         { *m = MsgCancelElectionResponse{} }
func (m *MsgCancelElectionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCancelElectionResponse) ProtoMessage()    {}
func (*MsgCancelElectionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_35a87a98f587e9e9, []int{7}
}
func (m *MsgCancelElectionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelElectionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelElectionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelElectionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelElectionResponse.Merge(m, src)
}
func (m *MsgCancelElectionResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelElectionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelElectionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelElectionResponse proto.InternalMessageInfo

// MsgUpdateParams updates module parameters — governance only.
type MsgUpdateParams struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Params    Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_35a87a98f587e9e9, []int{8}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_35a87a98f587e9e9, []int{9}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateElection)(nil), "phi.voting.MsgCreateElection")
	proto.RegisterType((*MsgCreateElectionResponse)(nil), "phi.voting.MsgCreateElectionResponse")
	proto.RegisterType((*MsgCastVote)(nil), "phi.voting.MsgCastVote")
	proto.RegisterType((*MsgCastVoteResponse)(nil), "phi.voting.MsgCastVoteResponse")
	proto.RegisterType((*MsgCloseElection)(nil), "phi.voting.MsgCloseElection")
	proto.RegisterType((*MsgCloseElectionResponse)(nil), "phi.voting.MsgCloseElectionResponse")
	proto.RegisterType((*MsgCancelElection)(nil), "phi.voting.MsgCancelElection")
	proto.RegisterType((*MsgCancelElectionResponse)(nil), "phi.voting.MsgCancelElectionResponse")
	proto.RegisterType((*MsgUpdateParams)(nil), "phi.voting.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "phi.voting.MsgUpdateParamsResponse")
}

func init() { proto.RegisterFile("phi/voting/tx.proto", fileDescriptor_35a87a98f587e9e9) }

var fileDescriptor_35a87a98f587e9e9 = []byte{
	// 769 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x41, 0x4f, 0xdb, 0x48,
	0x14, 0x8e, 0x13, 0x02, 0xe4, 0x05, 0x58, 0x32, 0x64, 0x17, 0x63, 0x20, 0xb0, 0xd9, 0x45, 0x42,
	0x2c, 0x89, 0x77, 0x59, 0xb5, 0x07, 0x6e, 0xa5, 0x50, 0x35, 0x07, 0xa4, 0xc8, 0xb4, 0x1c, 0x7a,
	0x89, 0x4c, 0x3c, 0x38, 0x23, 0x39, 0x1e, 0xd7, 0x33, 0x41, 0x70, 0xab, 0x7a, 0xec, 0xa9, 0x97,
	0xaa, 0x7f, 0xa1, 0x3d, 0x95, 0x43, 0x7f, 0x04, 0x47, 0xd4, 0x53, 0xd5, 0x43, 0x55, 0xc1, 0x81,
	0x1f, 0xd0, 0x3f, 0x50, 0x8d, 0xc7, 0x76, 0x1c, 0xa7, 0x25, 0x87, 0xaa, 0x97, 0x38, 0xf3, 0x7d,
	0xef, 0xbd, 0xf9, 0xde, 0x37, 0x6f, 0x6c, 0x98, 0xf3, 0x3a, 0x44, 0x3f, 0xa1, 0x9c, 0xb8, 0xb6,
	0xce, 0x4f, 0xeb, 0x9e, 0x4f, 0x39, 0x45, 0xe0, 0x75, 0x48, 0x5d, 0x82, 0x5a, 0xd9, 0xa6, 0x36,
	0x0d, 0x60, 0x5d, 0xfc, 0x93, 0x11, 0xda, 0x7c, 0x9b, 0xb2, 0x2e, 0x65, 0x7a, 0x97, 0xd9, 0xfa,
	0xc9, 0x7f, 0xe2, 0x11, 0x12, 0x0b, 0x92, 0x68, 0xc9, 0x0c, 0xb9, 0x08, 0xa9, 0x92, 0xd9, 0x25,
	0x2e, 0xd5, 0x83, 0xdf, 0xa8, 0x4c, 0x62, 0x77, 0xf9, 0x90, 0x44, 0xf5, 0x53, 0x16, 0x4a, 0xfb,
	0xcc, 0xbe, 0xef, 0x63, 0x93, 0xe3, 0x3d, 0x07, 0xb7, 0x39, 0xa1, 0x2e, 0xda, 0x82, 0x89, 0xb6,
	0x40, 0xa8, 0xaf, 0x2a, 0xab, 0xca, 0x7a, 0x61, 0x47, 0xfd, 0xf0, 0xbe, 0x56, 0x0e, 0x37, 0xb9,
	0x67, 0x59, 0x3e, 0x66, 0xec, 0x80, 0xfb, 0xc4, 0xb5, 0x8d, 0x28, 0x10, 0xcd, 0x40, 0x96, 0x58,
	0x6a, 0x56, 0x84, 0x1b, 0x59, 0x62, 0xa1, 0x32, 0xe4, 0x39, 0xe1, 0x0e, 0x56, 0x73, 0x01, 0x24,
	0x17, 0x48, 0x85, 0x09, 0xea, 0x89, 0x3d, 0x98, 0x3a, 0xb6, 0x9a, 0x5b, 0x2f, 0x18, 0xd1, 0x12,
	0xfd, 0x0b, 0x65, 0x1f, 0x3f, 0xed, 0x11, 0x1f, 0x5b, 0x2d, 0x8e, 0xbb, 0x9e, 0x63, 0x72, 0xdc,
	0x22, 0x96, 0x9a, 0x0f, 0xd2, 0x51, 0xc4, 0x3d, 0x0a, 0xa9, 0x86, 0x85, 0xea, 0x30, 0x17, 0x67,
	0x10, 0xc6, 0x7a, 0xd8, 0x6f, 0x59, 0xc4, 0x52, 0xc7, 0x83, 0x84, 0x52, 0x44, 0x35, 0x02, 0x66,
	0x97, 0x58, 0xe8, 0x4f, 0x98, 0x92, 0xbd, 0xb7, 0x18, 0x37, 0x7d, 0xae, 0x4e, 0xac, 0x2a, 0xeb,
	0x39, 0xa3, 0x28, 0xb1, 0x03, 0x01, 0xa1, 0x65, 0x80, 0x30, 0x04, 0xbb, 0x96, 0x3a, 0x19, 0x04,
	0x14, 0x24, 0xb2, 0xe7, 0x5a, 0xdb, 0xb5, 0xe7, 0x37, 0xe7, 0x1b, 0x51, 0xc7, 0x2f, 0x6e, 0xce,
	0x37, 0x96, 0x12, 0xbe, 0x0e, 0xd9, 0x58, 0x5d, 0x84, 0x85, 0x21, 0xd0, 0xc0, 0xcc, 0xa3, 0x2e,
	0xc3, 0xd5, 0xaf, 0x0a, 0x14, 0x05, 0x6b, 0x32, 0x7e, 0x48, 0x39, 0x46, 0x75, 0xc8, 0x9f, 0x50,
	0x8e, 0x47, 0x3b, 0x2e, 0xc3, 0xd0, 0x0a, 0x14, 0x71, 0x58, 0xb3, 0x15, 0x1b, 0x0f, 0x11, 0xd4,
	0xb0, 0xd0, 0x12, 0x14, 0xdc, 0x9e, 0xe3, 0x90, 0x63, 0x82, 0xfd, 0xe0, 0x10, 0xa6, 0x8c, 0x3e,
	0x80, 0xfe, 0x81, 0x12, 0x76, 0x88, 0x4d, 0x8e, 0x88, 0x43, 0xf8, 0x99, 0x18, 0x23, 0x7a, 0xac,
	0x8e, 0x05, 0x51, 0xb3, 0x09, 0xa2, 0x29, 0x70, 0xe1, 0x9c, 0x3c, 0xa6, 0x16, 0x71, 0x2d, 0x7c,
	0x1a, 0x9c, 0xc9, 0xb4, 0x51, 0x94, 0x58, 0x43, 0x40, 0xdb, 0x6b, 0xc2, 0x1a, 0x29, 0x4d, 0x18,
	0xf3, 0x47, 0xca, 0x98, 0xb0, 0xcb, 0xea, 0xef, 0x30, 0x97, 0x58, 0xc6, 0x66, 0xbc, 0x52, 0x60,
	0x56, 0xe0, 0x0e, 0x65, 0x3f, 0x37, 0x85, 0xa3, 0x5c, 0xd9, 0xde, 0x4c, 0x1f, 0xe1, 0x62, 0x4a,
	0x69, 0x52, 0x42, 0x55, 0x03, 0x35, 0x8d, 0xc5, 0x9a, 0x5f, 0x2b, 0xf2, 0xea, 0x98, 0x6e, 0x1b,
	0x3b, 0xbf, 0x56, 0xf4, 0xc8, 0xb9, 0x1b, 0xd0, 0x10, 0xcd, 0xdd, 0x00, 0x18, 0xcb, 0x7e, 0xa7,
	0xc0, 0x6f, 0xfb, 0xcc, 0x7e, 0xec, 0x59, 0x26, 0xc7, 0x4d, 0xd3, 0x37, 0xbb, 0x0c, 0xdd, 0x85,
	0x82, 0xd9, 0xe3, 0x1d, 0xea, 0x13, 0x7e, 0x36, 0x52, 0x76, 0x3f, 0x14, 0xdd, 0x81, 0x71, 0x2f,
	0xa8, 0x10, 0x68, 0x2e, 0x6e, 0xa1, 0x7a, 0xff, 0x85, 0x56, 0x97, 0xb5, 0x77, 0x0a, 0x17, 0x9f,
	0x57, 0x32, 0x6f, 0x6e, 0xce, 0x37, 0x14, 0x23, 0x0c, 0x96, 0xed, 0xf4, 0xcb, 0x88, 0x86, 0xb4,
	0xc1, 0x86, 0x92, 0xea, 0xaa, 0x0b, 0x30, 0x9f, 0x82, 0xa2, 0x66, 0xb6, 0xde, 0xe6, 0x20, 0xb7,
	0xcf, 0x6c, 0x74, 0x08, 0x33, 0xa9, 0x57, 0xd8, 0x72, 0x52, 0xca, 0xd0, 0x2d, 0xd4, 0xd6, 0x6e,
	0xa5, 0xa3, 0xfa, 0x68, 0x17, 0x26, 0xe3, 0x0b, 0x3a, 0x9f, 0x4e, 0x09, 0x09, 0x6d, 0xe5, 0x07,
	0x44, 0x5c, 0xe5, 0x00, 0xa6, 0x07, 0x27, 0x7b, 0x29, 0x9d, 0x91, 0x64, 0xb5, 0xbf, 0x6f, 0x63,
	0xe3, 0xa2, 0xa2, 0xe5, 0xc1, 0xd1, 0x1b, 0x6a, 0x79, 0x80, 0x1e, 0x6e, 0xf9, 0xbb, 0xf3, 0x81,
	0x9a, 0x30, 0x35, 0x30, 0x1b, 0x8b, 0xa9, 0xb4, 0x24, 0xa9, 0xfd, 0x75, 0x0b, 0x19, 0x55, 0xd4,
	0xf2, 0xcf, 0xc4, 0xe9, 0xef, 0x3c, 0xb8, 0xb8, 0xaa, 0x28, 0x97, 0x57, 0x15, 0xe5, 0xcb, 0x55,
	0x45, 0x79, 0x79, 0x5d, 0xc9, 0x5c, 0x5e, 0x57, 0x32, 0x1f, 0xaf, 0x2b, 0x99, 0x27, 0x9b, 0x36,
	0xe1, 0x9d, 0xde, 0x51, 0xbd, 0x4d, 0xbb, 0x7a, 0x93, 0xfa, 0xbc, 0xd6, 0x7c, 0xd8, 0xd0, 0xbd,
	0x0e, 0xa9, 0xb5, 0x3b, 0x26, 0x71, 0xf5, 0xd3, 0xf8, 0xbb, 0x79, 0xe6, 0x61, 0x76, 0x34, 0x1e,
	0x7c, 0xb9, 0xfe, 0xff, 0x16, 0x00, 0x00, 0xff, 0xff, 0xc9, 0x23, 0x92, 0x08, 0x52, 0x07, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// CreateElection opens a new poll gated by a credential template.
	CreateElection(ctx context.Context, in *MsgCreateElection, opts ...grpc.CallOption) (*MsgCreateElectionResponse, error)
	// CastVote casts an anonymous, eligibility-proven, nullifier-deduplicated ballot.
	CastVote(ctx context.Context, in *MsgCastVote, opts ...grpc.CallOption) (*MsgCastVoteResponse, error)
	// CloseElection closes a poll early (creator only).
	CloseElection(ctx context.Context, in *MsgCloseElection, opts ...grpc.CallOption) (*MsgCloseElectionResponse, error)
	// CancelElection cancels a poll before any vote (creator only).
	CancelElection(ctx context.Context, in *MsgCancelElection, opts ...grpc.CallOption) (*MsgCancelElectionResponse, error)
	// UpdateParams updates module parameters — governance only.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateElection(ctx context.Context, in *MsgCreateElection, opts ...grpc.CallOption) (*MsgCreateElectionResponse, error) {
	out := new(MsgCreateElectionResponse)
	err := c.cc.Invoke(ctx, "/phi.voting.Msg/CreateElection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CastVote(ctx context.Context, in *MsgCastVote, opts ...grpc.CallOption) (*MsgCastVoteResponse, error) {
	out := new(MsgCastVoteResponse)
	err := c.cc.Invoke(ctx, "/phi.voting.Msg/CastVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CloseElection(ctx context.Context, in *MsgCloseElection, opts ...grpc.CallOption) (*MsgCloseElectionResponse, error) {
	out := new(MsgCloseElectionResponse)
	err := c.cc.Invoke(ctx, "/phi.voting.Msg/CloseElection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CancelElection(ctx context.Context, in *MsgCancelElection, opts ...grpc.CallOption) (*MsgCancelElectionResponse, error) {
	out := new(MsgCancelElectionResponse)
	err := c.cc.Invoke(ctx, "/phi.voting.Msg/CancelElection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/phi.voting.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// CreateElection opens a new poll gated by a credential template.
	CreateElection(context.Context, *MsgCreateElection) (*MsgCreateElectionResponse, error)
	// CastVote casts an anonymous, eligibility-proven, nullifier-deduplicated ballot.
	CastVote(context.Context, *MsgCastVote) (*MsgCastVoteResponse, error)
	// CloseElection closes a poll early (creator only).
	CloseElection(context.Context, *MsgCloseElection) (*MsgCloseElectionResponse, error)
	// CancelElection cancels a poll before any vote (creator only).
	CancelElection(context.Context, *MsgCancelElection) (*MsgCancelElectionResponse, error)
	// UpdateParams updates module parameters — governance only.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateElection(ctx context.Context, req *MsgCreateElection) (*MsgCreateElectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateElection not implemented")
}
func (*UnimplementedMsgServer) CastVote(ctx context.Context, req *MsgCastVote) (*MsgCastVoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CastVote not implemented")
}
func (*UnimplementedMsgServer) CloseElection(ctx context.Context, req *MsgCloseElection) (*MsgCloseElectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseElection not implemented")
}
func (*UnimplementedMsgServer) CancelElection(ctx context.Context, req *MsgCancelElection) (*MsgCancelElectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelElection not implemented")
}
func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateElection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateElection)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateElection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phi.voting.Msg/CreateElection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateElection(ctx, req.(*MsgCreateElection))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CastVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCastVote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CastVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phi.voting.Msg/CastVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CastVote(ctx, req.(*MsgCastVote))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CloseElection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCloseElection)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CloseElection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phi.voting.Msg/CloseElection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CloseElection(ctx, req.(*MsgCloseElection))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CancelElection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCancelElection)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CancelElection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phi.voting.Msg/CancelElection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CancelElection(ctx, req.(*MsgCancelElection))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phi.voting.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "phi.voting.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateElection",
			Handler:    _Msg_CreateElection_Handler,
		},
		{
			MethodName: "CastVote",
			Handler:    _Msg_CastVote_Handler,
		},
		{
			MethodName: "CloseElection",
			Handler:    _Msg_CloseElection_Handler,
		},
		{
			MethodName: "CancelElection",
			Handler:    _Msg_CancelElection_Handler,
		},
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "phi/voting/tx.proto",
}

func (m *MsgCreateElection) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateElection) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateElection) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.VotingEnd != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.VotingEnd))
		i--
		dAtA[i] = 0x40
	}
	if m.VotingStart != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.VotingStart))
		i--
		dAtA[i] = 0x38
	}
	if len(m.RequiredIssuerDid) > 0 {
		i -= len(m.RequiredIssuerDid)
		copy(dAtA[i:], m.RequiredIssuerDid)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RequiredIssuerDid)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.RequiredTemplateId) > 0 {
		i -= len(m.RequiredTemplateId)
		copy(dAtA[i:], m.RequiredTemplateId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RequiredTemplateId)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Options) > 0 {
		for iNdEx := len(m.Options) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Options[iNdEx])
			copy(dAtA[i:], m.Options[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Options[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateElectionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateElectionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateElectionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCastVote) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCastVote) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCastVote) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.OptionIndex != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.OptionIndex))
		i--
		dAtA[i] = 0x28
	}
	if len(m.EligibilityProof) > 0 {
		i -= len(m.EligibilityProof)
		copy(dAtA[i:], m.EligibilityProof)
		i = encodeVarintTx(dAtA, i, uint64(len(m.EligibilityProof)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Nullifier) > 0 {
		i -= len(m.Nullifier)
		copy(dAtA[i:], m.Nullifier)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Nullifier)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ElectionId) > 0 {
		i -= len(m.ElectionId)
		copy(dAtA[i:], m.ElectionId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ElectionId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Voter) > 0 {
		i -= len(m.Voter)
		copy(dAtA[i:], m.Voter)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Voter)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCastVoteResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCastVoteResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCastVoteResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCloseElection) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCloseElection) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCloseElection) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ElectionId) > 0 {
		i -= len(m.ElectionId)
		copy(dAtA[i:], m.ElectionId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ElectionId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCloseElectionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCloseElectionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCloseElectionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCancelElection) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelElection) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelElection) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ElectionId) > 0 {
		i -= len(m.ElectionId)
		copy(dAtA[i:], m.ElectionId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ElectionId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCancelElectionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelElectionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelElectionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateElection) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Options) > 0 {
		for _, s := range m.Options {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	l = len(m.RequiredTemplateId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.RequiredIssuerDid)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.VotingStart != 0 {
		n += 1 + sovTx(uint64(m.VotingStart))
	}
	if m.VotingEnd != 0 {
		n += 1 + sovTx(uint64(m.VotingEnd))
	}
	return n
}

func (m *MsgCreateElectionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCastVote) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Voter)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ElectionId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Nullifier)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.EligibilityProof)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.OptionIndex != 0 {
		n += 1 + sovTx(uint64(m.OptionIndex))
	}
	return n
}

func (m *MsgCastVoteResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCloseElection) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ElectionId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCloseElectionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCancelElection) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ElectionId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCancelElectionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateElection) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateElection: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateElection: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Options", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Options = append(m.Options, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequiredTemplateId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequiredTemplateId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequiredIssuerDid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequiredIssuerDid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VotingStart", wireType)
			}
			m.VotingStart = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VotingStart |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VotingEnd", wireType)
			}
			m.VotingEnd = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VotingEnd |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateElectionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateElectionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateElectionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCastVote) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCastVote: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCastVote: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Voter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Voter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ElectionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ElectionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nullifier", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nullifier = append(m.Nullifier[:0], dAtA[iNdEx:postIndex]...)
			if m.Nullifier == nil {
				m.Nullifier = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EligibilityProof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EligibilityProof = append(m.EligibilityProof[:0], dAtA[iNdEx:postIndex]...)
			if m.EligibilityProof == nil {
				m.EligibilityProof = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OptionIndex", wireType)
			}
			m.OptionIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OptionIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCastVoteResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCastVoteResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCastVoteResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCloseElection) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCloseElection: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCloseElection: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ElectionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ElectionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCloseElectionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCloseElectionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCloseElectionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelElection) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelElection: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelElection: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ElectionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ElectionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelElectionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelElectionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelElectionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
