// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: phi/voting/voting.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ElectionStatus is the lifecycle state of an election (poll).
type ElectionStatus int32

const (
	ELECTION_STATUS_UNSPECIFIED ElectionStatus = 0
	ELECTION_STATUS_OPEN        ElectionStatus = 1
	ELECTION_STATUS_CLOSED      ElectionStatus = 2
	ELECTION_STATUS_CANCELLED   ElectionStatus = 3
)

var ElectionStatus_name = map[int32]string{
	0: "ELECTION_STATUS_UNSPECIFIED",
	1: "ELECTION_STATUS_OPEN",
	2: "ELECTION_STATUS_CLOSED",
	3: "ELECTION_STATUS_CANCELLED",
}

var ElectionStatus_value = map[string]int32{
	"ELECTION_STATUS_UNSPECIFIED": 0,
	"ELECTION_STATUS_OPEN":        1,
	"ELECTION_STATUS_CLOSED":      2,
	"ELECTION_STATUS_CANCELLED":   3,
}

func (x ElectionStatus) String() string {
	return proto.EnumName(ElectionStatus_name, int32(x))
}

func (ElectionStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1c7165a2d1b92f04, []int{0}
}

// Election is a general-purpose on-chain poll (organizational / referendum /
// party / DAO). Eligibility is gated by a credential template; a ballot is cast
// anonymously by proving credential possession (BBS+) plus a per-election
// nullifier for one-vote-per-(eligible)-nullifier.
//
// SECURITY: the eligibility proof is bound to (election, nullifier) by the Semaphore binding layer,
// so a proof is accepted only for the nullifier it was bound to (one proof yields at most one accepted
// nullifier per election) and reused nullifiers are deduplicated. The remaining one-human-one-vote
// step is the zero-knowledge derivation proof that nullifier = H(secret, election) for a signed-claim
// secret; without it, a holder able to produce multiple eligibility proofs from one credential can mint
// distinct nullifiers. Ballot secrecy (encrypted ballots + threshold decryption) is out of scope here:
// tallies are public and live.
type Election struct {
	// Election id (primary key), caller-supplied and unique.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Address that created the election (bech32).
	Creator string `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	// Human-readable question/title.
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// Ordered choice labels; a ballot's option_index points into this list.
	Options []string `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
	// Credential template that gates eligibility (its issuer BBS+ key verifies
	// proofs). Eligibility is checked at the TEMPLATE level, never a per-credential
	// anchor: the verifier checks the proof against the template issuer key without
	// learning which specific credential the voter holds, preserving anonymity. A
	// per-credential anchor lookup would deanonymize the voter.
	RequiredTemplateId string `protobuf:"bytes,5,opt,name=required_template_id,json=requiredTemplateId,proto3" json:"required_template_id,omitempty"`
	// Issuer DID expected for that template (binding/clarity).
	RequiredIssuerDid string `protobuf:"bytes,6,opt,name=required_issuer_did,json=requiredIssuerDid,proto3" json:"required_issuer_did,omitempty"`
	// Voting window (Unix seconds).
	VotingStart int64 `protobuf:"varint,7,opt,name=voting_start,json=votingStart,proto3" json:"voting_start,omitempty"`
	VotingEnd   int64 `protobuf:"varint,8,opt,name=voting_end,json=votingEnd,proto3" json:"voting_end,omitempty"`
	// Lifecycle status.
	Status ElectionStatus `protobuf:"varint,9,opt,name=status,proto3,enum=phi.voting.ElectionStatus" json:"status,omitempty"`
	// Running public tally, one count per entry in options.
	OptionTallies []uint64 `protobuf:"varint,10,rep,packed,name=option_tallies,json=optionTallies,proto3" json:"option_tallies,omitempty"`
	// Total accepted ballots.
	TotalVotes uint64 `protobuf:"varint,11,opt,name=total_votes,json=totalVotes,proto3" json:"total_votes,omitempty"`
	// Creation time (Unix seconds).
	CreatedAt int64 `protobuf:"varint,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (m *Election) Reset()         { *m = Election{} }
func (m *Election) String() string { return proto.CompactTextString(m) }
func (*Election) ProtoMessage()    {}
func (*Election) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c7165a2d1b92f04, []int{0}
}
func (m *Election) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Election) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Election.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Election) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Election.Merge(m, src)
}
func (m *Election) XXX_Size() int {
	return m.Size()
}
func (m *Election) XXX_DiscardUnknown() {
	xxx_messageInfo_Election.DiscardUnknown(m)
}

var xxx_messageInfo_Election proto.InternalMessageInfo

func (m *Election) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Election) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Election) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Election) GetOptions() []string {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *Election) GetRequiredTemplateId() string {
	if m != nil {
		return m.RequiredTemplateId
	}
	return ""
}

func (m *Election) GetRequiredIssuerDid() string {
	if m != nil {
		return m.RequiredIssuerDid
	}
	return ""
}

func (m *Election) GetVotingStart() int64 {
	if m != nil {
		return m.VotingStart
	}
	return 0
}

func (m *Election) GetVotingEnd() int64 {
	if m != nil {
		return m.VotingEnd
	}
	return 0
}

func (m *Election) GetStatus() ElectionStatus {
	if m != nil {
		return m.Status
	}
	return ELECTION_STATUS_UNSPECIFIED
}

func (m *Election) GetOptionTallies() []uint64 {
	if m != nil {
		return m.OptionTallies
	}
	return nil
}

func (m *Election) GetTotalVotes() uint64 {
	if m != nil {
		return m.TotalVotes
	}
	return 0
}

func (m *Election) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

// Ballot is one accepted anonymous vote, keyed by (election_id, nullifier). Its
// existence also serves as the nullifier-used marker (double-vote prevention).
type Ballot struct {
	// Election the ballot belongs to.
	ElectionId string `protobuf:"bytes,1,opt,name=election_id,json=electionId,proto3" json:"election_id,omitempty"`
	// Per-election nullifier (unlinkable across elections); unique within an election.
	Nullifier []byte `protobuf:"bytes,2,opt,name=nullifier,proto3" json:"nullifier,omitempty"`
	// Chosen option index into Election.options.
	OptionIndex uint32 `protobuf:"varint,3,opt,name=option_index,json=optionIndex,proto3" json:"option_index,omitempty"`
	// Cast time (Unix seconds).
	CastAt int64 `protobuf:"varint,4,opt,name=cast_at,json=castAt,proto3" json:"cast_at,omitempty"`
}

func (m *Ballot) Reset()         { *m = Ballot{} }
func (m *Ballot) String() string { return proto.CompactTextString(m) }
func (*Ballot) ProtoMessage()    {}
func (*Ballot) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c7165a2d1b92f04, []int{1}
}
func (m *Ballot) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Ballot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Ballot.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Ballot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ballot.Merge(m, src)
}
func (m *Ballot) XXX_Size() int {
	return m.Size()
}
func (m *Ballot) XXX_DiscardUnknown() {
	xxx_messageInfo_Ballot.DiscardUnknown(m)
}

var xxx_messageInfo_Ballot proto.InternalMessageInfo

func (m *Ballot) GetElectionId() string {
	if m != nil {
		return m.ElectionId
	}
	return ""
}

func (m *Ballot) GetNullifier() []byte {
	if m != nil {
		return m.Nullifier
	}
	return nil
}

func (m *Ballot) GetOptionIndex() uint32 {
	if m != nil {
		return m.OptionIndex
	}
	return 0
}

func (m *Ballot) GetCastAt() int64 {
	if m != nil {
		return m.CastAt
	}
	return 0
}

// Params are the voting module parameters; changed only via governance.
type Params struct {
	// Maximum number of options an election may declare.
	MaxOptions uint32 `protobuf:"varint,1,opt,name=max_options,json=maxOptions,proto3" json:"max_options,omitempty"`
	// Minimum voting window length (seconds) an election must allow.
	MinVotingPeriodSeconds int64 `protobuf:"varint,2,opt,name=min_voting_period_seconds,json=minVotingPeriodSeconds,proto3" json:"min_voting_period_seconds,omitempty"`
	// Upper bound on the eligibility proof blob a vote may carry (anti-DoS).
	MaxProofSizeBytes uint32 `protobuf:"varint,3,opt,name=max_proof_size_bytes,json=maxProofSizeBytes,proto3" json:"max_proof_size_bytes,omitempty"`
	// Maximum voting window length (seconds) an election may declare; 0 disables the upper bound. Bounds
	// far-future elections and the resulting open-election state bloat.
	MaxVotingPeriodSeconds int64 `protobuf:"varint,4,opt,name=max_voting_period_seconds,json=maxVotingPeriodSeconds,proto3" json:"max_voting_period_seconds,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c7165a2d1b92f04, []int{2}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMaxOptions() uint32 {
	if m != nil {
		return m.MaxOptions
	}
	return 0
}

func (m *Params) GetMinVotingPeriodSeconds() int64 {
	if m != nil {
		return m.MinVotingPeriodSeconds
	}
	return 0
}

func (m *Params) GetMaxProofSizeBytes() uint32 {
	if m != nil {
		return m.MaxProofSizeBytes
	}
	return 0
}

func (m *Params) GetMaxVotingPeriodSeconds() int64 {
	if m != nil {
		return m.MaxVotingPeriodSeconds
	}
	return 0
}

func init() {
	proto.RegisterEnum("phi.voting.ElectionStatus", ElectionStatus_name, ElectionStatus_value)
	proto.RegisterType((*Election)(nil), "phi.voting.Election")
	proto.RegisterType((*Ballot)(nil), "phi.voting.Ballot")
	proto.RegisterType((*Params)(nil), "phi.voting.Params")
}

func init() { proto.RegisterFile("phi/voting/voting.proto", fileDescriptor_1c7165a2d1b92f04) }

var fileDescriptor_1c7165a2d1b92f04 = []byte{
	// 679 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0xc1, 0x4e, 0x1b, 0x39,
	0x18, 0xc7, 0x33, 0x49, 0x08, 0xc4, 0x81, 0x28, 0x98, 0x08, 0x4c, 0x76, 0x09, 0x59, 0xa4, 0x95,
	0x22, 0xb4, 0x24, 0x2b, 0xf6, 0xb4, 0xbd, 0x85, 0x64, 0x50, 0x47, 0x8a, 0x92, 0x68, 0x26, 0x70,
	0xe8, 0xc5, 0x32, 0xb1, 0x49, 0x2c, 0xcd, 0x8c, 0xa7, 0x33, 0x0e, 0x0a, 0x5c, 0x7b, 0xa9, 0xaa,
	0x1e, 0xfa, 0x0e, 0xbc, 0x40, 0x1f, 0xa3, 0x47, 0x8e, 0x3d, 0x56, 0x70, 0xa8, 0xd4, 0xa7, 0xa8,
	0x6c, 0x4f, 0x40, 0xa5, 0xed, 0x25, 0x19, 0xff, 0xfe, 0x7f, 0xdb, 0xff, 0xef, 0xfb, 0x64, 0xb0,
	0x13, 0xcd, 0x78, 0xfb, 0x4a, 0x48, 0x1e, 0x4e, 0xd3, 0xbf, 0x56, 0x14, 0x0b, 0x29, 0x20, 0x88,
	0x66, 0xbc, 0x65, 0x48, 0xad, 0x3a, 0x15, 0x53, 0xa1, 0x71, 0x5b, 0x7d, 0x19, 0x47, 0x6d, 0x93,
	0x04, 0x3c, 0x14, 0x6d, 0xfd, 0x6b, 0xd0, 0xc1, 0x6d, 0x0e, 0xac, 0xd9, 0x3e, 0x9b, 0x48, 0x2e,
	0x42, 0x58, 0x06, 0x59, 0x4e, 0x91, 0xd5, 0xb0, 0x9a, 0x45, 0x37, 0xcb, 0x29, 0x44, 0x60, 0x75,
	0x12, 0x33, 0x22, 0x45, 0x8c, 0xb2, 0x1a, 0x2e, 0x97, 0xb0, 0x0a, 0x56, 0x24, 0x97, 0x3e, 0x43,
	0x39, 0xcd, 0xcd, 0x42, 0xf9, 0x45, 0xa4, 0x4e, 0x4a, 0x50, 0xbe, 0x91, 0x53, 0xfe, 0x74, 0x09,
	0xff, 0x05, 0xd5, 0x98, 0xbd, 0x9e, 0xf3, 0x98, 0x51, 0x2c, 0x59, 0x10, 0xf9, 0x44, 0x32, 0xcc,
	0x29, 0x5a, 0xd1, 0xdb, 0xe1, 0x52, 0x1b, 0xa7, 0x92, 0x43, 0x61, 0x0b, 0x6c, 0x3d, 0xee, 0xe0,
	0x49, 0x32, 0x67, 0x31, 0xa6, 0x9c, 0xa2, 0x82, 0xde, 0xb0, 0xb9, 0x94, 0x1c, 0xad, 0xf4, 0x38,
	0x85, 0x7f, 0x81, 0x75, 0x53, 0x3b, 0x4e, 0x24, 0x89, 0x25, 0x5a, 0x6d, 0x58, 0xcd, 0x9c, 0x5b,
	0x32, 0xcc, 0x53, 0x08, 0xee, 0x01, 0x90, 0x5a, 0x58, 0x48, 0xd1, 0x9a, 0x36, 0x14, 0x0d, 0xb1,
	0x43, 0x0a, 0x8f, 0x41, 0x21, 0x91, 0x44, 0xce, 0x13, 0x54, 0x6c, 0x58, 0xcd, 0xf2, 0x71, 0xad,
	0xf5, 0xd4, 0xd0, 0xd6, 0xb2, 0x47, 0x9e, 0x76, 0xb8, 0xa9, 0x13, 0xfe, 0x0d, 0xca, 0xa6, 0x44,
	0x2c, 0x89, 0xef, 0x73, 0x96, 0x20, 0xd0, 0xc8, 0x35, 0xf3, 0xee, 0x86, 0xa1, 0x63, 0x03, 0xe1,
	0x3e, 0x28, 0x49, 0x21, 0x89, 0x8f, 0xaf, 0x84, 0x64, 0x09, 0x2a, 0x35, 0xac, 0x66, 0xde, 0x05,
	0x1a, 0x9d, 0x2b, 0xa2, 0xa2, 0xe9, 0xd6, 0x32, 0x8a, 0x89, 0x44, 0xeb, 0x26, 0x5a, 0x4a, 0x3a,
	0xf2, 0xe0, 0x8d, 0x05, 0x0a, 0x27, 0xc4, 0xf7, 0x85, 0x54, 0x47, 0xb1, 0x34, 0x0b, 0x7e, 0x1c,
	0x16, 0x58, 0x22, 0x87, 0xc2, 0x3f, 0x41, 0x31, 0x9c, 0xfb, 0x3e, 0xbf, 0xe4, 0xcc, 0x8c, 0x6d,
	0xdd, 0x7d, 0x02, 0xaa, 0x4d, 0x69, 0x60, 0x1e, 0x52, 0xb6, 0xd0, 0xf3, 0xdb, 0x70, 0x4b, 0x86,
	0x39, 0x0a, 0xc1, 0x1d, 0xb0, 0x3a, 0x21, 0x89, 0x54, 0x41, 0xf2, 0x3a, 0x48, 0x41, 0x2d, 0x3b,
	0xf2, 0xe0, 0x9b, 0x05, 0x0a, 0x23, 0x12, 0x93, 0x40, 0x17, 0x14, 0x90, 0x05, 0x5e, 0x4e, 0xdb,
	0xd2, 0xa7, 0x80, 0x80, 0x2c, 0x86, 0xe9, 0xc0, 0xff, 0x07, 0xbb, 0x01, 0x0f, 0x71, 0xda, 0xef,
	0x88, 0xc5, 0x5c, 0x50, 0x9c, 0xb0, 0x89, 0x08, 0x69, 0xa2, 0x53, 0xe5, 0xdc, 0xed, 0x80, 0x87,
	0xe7, 0x5a, 0x1f, 0x69, 0xd9, 0x33, 0x2a, 0x6c, 0x83, 0xaa, 0x3a, 0x3b, 0x8a, 0x85, 0xb8, 0xc4,
	0x09, 0xbf, 0x61, 0xf8, 0xe2, 0x5a, 0x75, 0xcd, 0x44, 0xdd, 0x0c, 0xc8, 0x62, 0xa4, 0x24, 0x8f,
	0xdf, 0xb0, 0x13, 0x25, 0xe8, 0xbb, 0xc8, 0xe2, 0x37, 0x77, 0xe5, 0xd3, 0xbb, 0xc8, 0xe2, 0x17,
	0x77, 0xbd, 0x40, 0xef, 0xbe, 0x7e, 0x3c, 0xdc, 0x52, 0x2f, 0x6a, 0xb1, 0x7c, 0x53, 0xa6, 0xc2,
	0xc3, 0xf7, 0x16, 0x28, 0xff, 0x38, 0x74, 0xb8, 0x0f, 0xfe, 0xb0, 0xfb, 0x76, 0x77, 0xec, 0x0c,
	0x07, 0xd8, 0x1b, 0x77, 0xc6, 0x67, 0x1e, 0x3e, 0x1b, 0x78, 0x23, 0xbb, 0xeb, 0x9c, 0x3a, 0x76,
	0xaf, 0x92, 0x81, 0x08, 0x54, 0x9f, 0x1b, 0x86, 0x23, 0x7b, 0x50, 0xb1, 0x60, 0x0d, 0x6c, 0x3f,
	0x57, 0xba, 0xfd, 0xa1, 0x67, 0xf7, 0x2a, 0x59, 0xb8, 0x07, 0x76, 0x7f, 0xd2, 0x3a, 0x83, 0xae,
	0xdd, 0xef, 0xdb, 0xbd, 0x4a, 0xae, 0x96, 0x7f, 0x7b, 0x5b, 0xcf, 0x9c, 0x9c, 0x7e, 0xba, 0xaf,
	0x5b, 0x77, 0xf7, 0x75, 0xeb, 0xcb, 0x7d, 0xdd, 0xfa, 0xf0, 0x50, 0xcf, 0xdc, 0x3d, 0xd4, 0x33,
	0x9f, 0x1f, 0xea, 0x99, 0x57, 0xff, 0x4c, 0xb9, 0x9c, 0xcd, 0x2f, 0x5a, 0x13, 0x11, 0xb4, 0x47,
	0x22, 0x96, 0x47, 0xa3, 0x97, 0x4e, 0x3b, 0x9a, 0xf1, 0xa3, 0xc9, 0x8c, 0xf0, 0xf0, 0xa9, 0x2e,
	0x79, 0x1d, 0xb1, 0xe4, 0xa2, 0xa0, 0x9f, 0xfd, 0x7f, 0xdf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x3f,
	0x4a, 0x33, 0xde, 0x46, 0x04, 0x00, 0x00,
}

func (m *Election) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Election) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Election) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CreatedAt != 0 {
		i = encodeVarintVoting(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x60
	}
	if m.TotalVotes != 0 {
		i = encodeVarintVoting(dAtA, i, uint64(m.TotalVotes))
		i--
		dAtA[i] = 0x58
	}
	if len(m.OptionTallies) > 0 {
		dAtA2 := make([]byte, len(m.OptionTallies)*10)
		var j1 int
		for _, num := range m.OptionTallies {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintVoting(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x52
	}
	if m.Status != 0 {
		i = encodeVarintVoting(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x48
	}
	if m.VotingEnd != 0 {
		i = encodeVarintVoting(dAtA, i, uint64(m.VotingEnd))
		i--
		dAtA[i] = 0x40
	}
	if m.VotingStart != 0 {
		i = encodeVarintVoting(dAtA, i, uint64(m.VotingStart))
		i--
		dAtA[i] = 0x38
	}
	if len(m.RequiredIssuerDid) > 0 {
		i -= len(m.RequiredIssuerDid)
		copy(dAtA[i:], m.RequiredIssuerDid)
		i = encodeVarintVoting(dAtA, i, uint64(len(m.RequiredIssuerDid)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.RequiredTemplateId) > 0 {
		i -= len(m.RequiredTemplateId)
		copy(dAtA[i:], m.RequiredTemplateId)
		i = encodeVarintVoting(dAtA, i, uint64(len(m.RequiredTemplateId)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Options) > 0 {
		for iNdEx := len(m.Options) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Options[iNdEx])
			copy(dAtA[i:], m.Options[iNdEx])
			i = encodeVarintVoting(dAtA, i, uint64(len(m.Options[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintVoting(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintVoting(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintVoting(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Ballot) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Ballot) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Ballot) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CastAt != 0 {
		i = encodeVarintVoting(dAtA, i, uint64(m.CastAt))
		i--
		dAtA[i] = 0x20
	}
	if m.OptionIndex != 0 {
		i = encodeVarintVoting(dAtA, i, uint64(m.OptionIndex))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Nullifier) > 0 {
		i -= len(m.Nullifier)
		copy(dAtA[i:], m.Nullifier)
		i = encodeVarintVoting(dAtA, i, uint64(len(m.Nullifier)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ElectionId) > 0 {
		i -= len(m.ElectionId)
		copy(dAtA[i:], m.ElectionId)
		i = encodeVarintVoting(dAtA, i, uint64(len(m.ElectionId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxVotingPeriodSeconds != 0 {
		i = encodeVarintVoting(dAtA, i, uint64(m.MaxVotingPeriodSeconds))
		i--
		dAtA[i] = 0x20
	}
	if m.MaxProofSizeBytes != 0 {
		i = encodeVarintVoting(dAtA, i, uint64(m.MaxProofSizeBytes))
		i--
		dAtA[i] = 0x18
	}
	if m.MinVotingPeriodSeconds != 0 {
		i = encodeVarintVoting(dAtA, i, uint64(m.MinVotingPeriodSeconds))
		i--
		dAtA[i] = 0x10
	}
	if m.MaxOptions != 0 {
		i = encodeVarintVoting(dAtA, i, uint64(m.MaxOptions))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintVoting(dAtA []byte, offset int, v uint64) int {
	offset -= sovVoting(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Election) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovVoting(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovVoting(uint64(l))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovVoting(uint64(l))
	}
	if len(m.Options) > 0 {
		for _, s := range m.Options {
			l = len(s)
			n += 1 + l + sovVoting(uint64(l))
		}
	}
	l = len(m.RequiredTemplateId)
	if l > 0 {
		n += 1 + l + sovVoting(uint64(l))
	}
	l = len(m.RequiredIssuerDid)
	if l > 0 {
		n += 1 + l + sovVoting(uint64(l))
	}
	if m.VotingStart != 0 {
		n += 1 + sovVoting(uint64(m.VotingStart))
	}
	if m.VotingEnd != 0 {
		n += 1 + sovVoting(uint64(m.VotingEnd))
	}
	if m.Status != 0 {
		n += 1 + sovVoting(uint64(m.Status))
	}
	if len(m.OptionTallies) > 0 {
		l = 0
		for _, e := range m.OptionTallies {
			l += sovVoting(uint64(e))
		}
		n += 1 + sovVoting(uint64(l)) + l
	}
	if m.TotalVotes != 0 {
		n += 1 + sovVoting(uint64(m.TotalVotes))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovVoting(uint64(m.CreatedAt))
	}
	return n
}

func (m *Ballot) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ElectionId)
	if l > 0 {
		n += 1 + l + sovVoting(uint64(l))
	}
	l = len(m.Nullifier)
	if l > 0 {
		n += 1 + l + sovVoting(uint64(l))
	}
	if m.OptionIndex != 0 {
		n += 1 + sovVoting(uint64(m.OptionIndex))
	}
	if m.CastAt != 0 {
		n += 1 + sovVoting(uint64(m.CastAt))
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxOptions != 0 {
		n += 1 + sovVoting(uint64(m.MaxOptions))
	}
	if m.MinVotingPeriodSeconds != 0 {
		n += 1 + sovVoting(uint64(m.MinVotingPeriodSeconds))
	}
	if m.MaxProofSizeBytes != 0 {
		n += 1 + sovVoting(uint64(m.MaxProofSizeBytes))
	}
	if m.MaxVotingPeriodSeconds != 0 {
		n += 1 + sovVoting(uint64(m.MaxVotingPeriodSeconds))
	}
	return n
}

func sovVoting(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozVoting(x uint64) (n int) {
	return sovVoting(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Election) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVoting
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Election: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Election: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVoting
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVoting
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVoting
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVoting
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVoting
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVoting
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Options", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVoting
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVoting
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Options = append(m.Options, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequiredTemplateId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVoting
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVoting
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequiredTemplateId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequiredIssuerDid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVoting
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVoting
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequiredIssuerDid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VotingStart", wireType)
			}
			m.VotingStart = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VotingStart |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VotingEnd", wireType)
			}
			m.VotingEnd = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VotingEnd |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= ElectionStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowVoting
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.OptionTallies = append(m.OptionTallies, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowVoting
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthVoting
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthVoting
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.OptionTallies) == 0 {
					m.OptionTallies = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowVoting
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.OptionTallies = append(m.OptionTallies, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field OptionTallies", wireType)
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalVotes", wireType)
			}
			m.TotalVotes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalVotes |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipVoting(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVoting
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Ballot) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVoting
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Ballot: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Ballot: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ElectionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVoting
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVoting
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ElectionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nullifier", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVoting
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVoting
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nullifier = append(m.Nullifier[:0], dAtA[iNdEx:postIndex]...)
			if m.Nullifier == nil {
				m.Nullifier = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OptionIndex", wireType)
			}
			m.OptionIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OptionIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CastAt", wireType)
			}
			m.CastAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CastAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipVoting(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVoting
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVoting
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxOptions", wireType)
			}
			m.MaxOptions = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxOptions |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinVotingPeriodSeconds", wireType)
			}
			m.MinVotingPeriodSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinVotingPeriodSeconds |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxProofSizeBytes", wireType)
			}
			m.MaxProofSizeBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxProofSizeBytes |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxVotingPeriodSeconds", wireType)
			}
			m.MaxVotingPeriodSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxVotingPeriodSeconds |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipVoting(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVoting
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipVoting(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowVoting
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVoting
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVoting
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthVoting
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupVoting
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthVoting
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthVoting        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowVoting          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupVoting = fmt.Errorf("proto: unexpected end of group")
)
