// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: phi/coin/coin.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// FeeEntry is one row of the per-message-type fixed-fee table.
type FeeEntry struct {
	// Message type (Msg type URL), e.g. /phi.coin.MsgTransfer
	MsgTypeUrl string `protobuf:"bytes,1,opt,name=msg_type_url,json=msgTypeUrl,proto3" json:"msg_type_url,omitempty"`
	// Fixed fee (uphi)
	Fee string `protobuf:"bytes,2,opt,name=fee,proto3" json:"fee,omitempty"`
}

func (m *FeeEntry) Reset()         { *m = FeeEntry{} }
func (m *FeeEntry) String() string { return proto.CompactTextString(m) }
func (*FeeEntry) ProtoMessage()    {}
func (*FeeEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_87c3c64ab5dc5a1b, []int{0}
}
func (m *FeeEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FeeEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FeeEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FeeEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeEntry.Merge(m, src)
}
func (m *FeeEntry) XXX_Size() int {
	return m.Size()
}
func (m *FeeEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeEntry.DiscardUnknown(m)
}

var xxx_messageInfo_FeeEntry proto.InternalMessageInfo

func (m *FeeEntry) GetMsgTypeUrl() string {
	if m != nil {
		return m.MsgTypeUrl
	}
	return ""
}

func (m *FeeEntry) GetFee() string {
	if m != nil {
		return m.Fee
	}
	return ""
}

// Params holds the coin module's economic parameters; changeable only via governance.
type Params struct {
	// Per-message-type fixed-fee table (uphi)
	Fees []FeeEntry `protobuf:"bytes,1,rep,name=fees,proto3" json:"fees"`
	// Default fee when the message type is not in the table (uphi)
	DefaultFee string `protobuf:"bytes,2,opt,name=default_fee,json=defaultFee,proto3" json:"default_fee,omitempty"`
	// Micro-exemption threshold (uphi); a transaction smaller than this draws from the free quota
	MicroThreshold string `protobuf:"bytes,3,opt,name=micro_threshold,json=microThreshold,proto3" json:"micro_threshold,omitempty"`
	// Daily micro-exemption quota per DID
	MicroDailyQuota uint64 `protobuf:"varint,4,opt,name=micro_daily_quota,json=microDailyQuota,proto3" json:"micro_daily_quota,omitempty"`
	// Coin-age threshold duration (seconds): below it "young", above it "old"
	CoinAgeThresholdSeconds int64 `protobuf:"varint,5,opt,name=coin_age_threshold_seconds,json=coinAgeThresholdSeconds,proto3" json:"coin_age_threshold_seconds,omitempty"`
	// Young-coin burn rate (bps; 1bp=0.01%) — default 1% = 100
	YoungBurnBps uint32 `protobuf:"varint,6,opt,name=young_burn_bps,json=youngBurnBps,proto3" json:"young_burn_bps,omitempty"`
	// Old-coin burn rate (bps) — default 0.2% = 20
	OldBurnBps uint32 `protobuf:"varint,7,opt,name=old_burn_bps,json=oldBurnBps,proto3" json:"old_burn_bps,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_87c3c64ab5dc5a1b, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetFees() []FeeEntry {
	if m != nil {
		return m.Fees
	}
	return nil
}

func (m *Params) GetDefaultFee() string {
	if m != nil {
		return m.DefaultFee
	}
	return ""
}

func (m *Params) GetMicroThreshold() string {
	if m != nil {
		return m.MicroThreshold
	}
	return ""
}

func (m *Params) GetMicroDailyQuota() uint64 {
	if m != nil {
		return m.MicroDailyQuota
	}
	return 0
}

func (m *Params) GetCoinAgeThresholdSeconds() int64 {
	if m != nil {
		return m.CoinAgeThresholdSeconds
	}
	return 0
}

func (m *Params) GetYoungBurnBps() uint32 {
	if m != nil {
		return m.YoungBurnBps
	}
	return 0
}

func (m *Params) GetOldBurnBps() uint32 {
	if m != nil {
		return m.OldBurnBps
	}
	return 0
}

// CoinAge keeps the two coin-age buckets of each address (anti-circumvention of stepped burn).
// The bucket label is carried across transfers, so a transfer does not reset the age.
type CoinAge struct {
	// Owner address (bech32)
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Young-coin amount (uphi) — below the age threshold
	YoungAmount string `protobuf:"bytes,2,opt,name=young_amount,json=youngAmount,proto3" json:"young_amount,omitempty"`
	// Old-coin amount (uphi) — above the age threshold
	OldAmount string `protobuf:"bytes,3,opt,name=old_amount,json=oldAmount,proto3" json:"old_amount,omitempty"`
	// Start time of the young-bucket counter (Unix seconds)
	YoungSince int64 `protobuf:"varint,4,opt,name=young_since,json=youngSince,proto3" json:"young_since,omitempty"`
}

func (m *CoinAge) Reset()         { *m = CoinAge{} }
func (m *CoinAge) String() string { return proto.CompactTextString(m) }
func (*CoinAge) ProtoMessage()    {}
func (*CoinAge) Descriptor() ([]byte, []int) {
	return fileDescriptor_87c3c64ab5dc5a1b, []int{2}
}
func (m *CoinAge) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CoinAge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CoinAge.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CoinAge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoinAge.Merge(m, src)
}
func (m *CoinAge) XXX_Size() int {
	return m.Size()
}
func (m *CoinAge) XXX_DiscardUnknown() {
	xxx_messageInfo_CoinAge.DiscardUnknown(m)
}

var xxx_messageInfo_CoinAge proto.InternalMessageInfo

func (m *CoinAge) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CoinAge) GetYoungAmount() string {
	if m != nil {
		return m.YoungAmount
	}
	return ""
}

func (m *CoinAge) GetOldAmount() string {
	if m != nil {
		return m.OldAmount
	}
	return ""
}

func (m *CoinAge) GetYoungSince() int64 {
	if m != nil {
		return m.YoungSince
	}
	return 0
}

func init() {
	proto.RegisterType((*FeeEntry)(nil), "phi.coin.FeeEntry")
	proto.RegisterType((*Params)(nil), "phi.coin.Params")
	proto.RegisterType((*CoinAge)(nil), "phi.coin.CoinAge")
}

func init() { proto.RegisterFile("phi/coin/coin.proto", fileDescriptor_87c3c64ab5dc5a1b) }

var fileDescriptor_87c3c64ab5dc5a1b = []byte{
	// 453 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x92, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0xeb, 0xa5, 0xb4, 0xdb, 0xeb, 0x18, 0xab, 0x41, 0x10, 0x55, 0x22, 0x0d, 0x15, 0x12,
	0x51, 0x85, 0x5a, 0x09, 0x6e, 0x20, 0x21, 0xad, 0xc0, 0xce, 0x90, 0x8d, 0x0b, 0x17, 0x2b, 0x6d,
	0x5e, 0xd3, 0x48, 0x89, 0x1d, 0xec, 0x44, 0x22, 0x5f, 0x80, 0x03, 0x27, 0x3e, 0x0a, 0x1f, 0x63,
	0xdc, 0x76, 0xe4, 0x84, 0x50, 0x7b, 0xe0, 0x6b, 0x20, 0xdb, 0xc9, 0xba, 0x8b, 0x65, 0xff, 0xde,
	0x5f, 0xef, 0xff, 0xf4, 0x7f, 0x86, 0xfb, 0xc5, 0x26, 0x9d, 0xaf, 0x44, 0xca, 0xcd, 0x31, 0x2b,
	0xa4, 0x28, 0x05, 0x3d, 0x2c, 0x36, 0xe9, 0x4c, 0xbf, 0x47, 0x0f, 0x12, 0x91, 0x08, 0x03, 0xe7,
	0xfa, 0x66, 0xeb, 0xa3, 0x61, 0x94, 0xa7, 0x5c, 0xcc, 0xcd, 0x69, 0xd1, 0xe4, 0x0d, 0x1c, 0x9e,
	0x23, 0xbe, 0xe7, 0xa5, 0xac, 0xa9, 0x0f, 0xc7, 0xb9, 0x4a, 0x58, 0x59, 0x17, 0xc8, 0x2a, 0x99,
	0xb9, 0xc4, 0x27, 0xc1, 0x51, 0x08, 0xb9, 0x4a, 0x2e, 0xeb, 0x02, 0x3f, 0xc9, 0x8c, 0x9e, 0x82,
	0xb3, 0x46, 0x74, 0x0f, 0x4c, 0x41, 0x5f, 0x27, 0xbf, 0x0e, 0xa0, 0xf7, 0x21, 0x92, 0x51, 0xae,
	0xe8, 0x73, 0xe8, 0xae, 0x11, 0x95, 0x4b, 0x7c, 0x27, 0x18, 0xbc, 0xa0, 0xb3, 0x76, 0x98, 0x59,
	0x6b, 0xb0, 0xe8, 0x5e, 0xfd, 0x19, 0x77, 0x42, 0xa3, 0xa2, 0x63, 0x18, 0xc4, 0xb8, 0x8e, 0xaa,
	0xac, 0x64, 0xfb, 0x96, 0xd0, 0xa0, 0x73, 0x44, 0xfa, 0x0c, 0xee, 0xe5, 0xe9, 0x4a, 0x0a, 0x56,
	0x6e, 0x24, 0xaa, 0x8d, 0xc8, 0x62, 0xd7, 0x31, 0xa2, 0x13, 0x83, 0x2f, 0x5b, 0x4a, 0xa7, 0x30,
	0xb4, 0xc2, 0x38, 0x4a, 0xb3, 0x9a, 0x7d, 0xa9, 0x44, 0x19, 0xb9, 0x5d, 0x9f, 0x04, 0xdd, 0xd0,
	0x76, 0x78, 0xa7, 0xf9, 0x47, 0x8d, 0xe9, 0x6b, 0x18, 0xe9, 0x91, 0x58, 0x94, 0xe0, 0xbe, 0x2f,
	0x53, 0xb8, 0x12, 0x3c, 0x56, 0xee, 0x1d, 0x9f, 0x04, 0x4e, 0xf8, 0x48, 0x2b, 0xce, 0x12, 0xbc,
	0x71, 0xb8, 0xb0, 0x65, 0xfa, 0x14, 0x4e, 0x6a, 0x51, 0xf1, 0x84, 0x2d, 0x2b, 0xc9, 0xd9, 0xb2,
	0x50, 0x6e, 0xcf, 0x27, 0xc1, 0xdd, 0xf0, 0xd8, 0xd0, 0x45, 0x25, 0xf9, 0xa2, 0x50, 0x3a, 0x45,
	0xdd, 0xf3, 0x46, 0xd3, 0x37, 0x1a, 0x10, 0x59, 0xdc, 0x28, 0x5e, 0x3d, 0xfc, 0xfe, 0xef, 0xe7,
	0x74, 0xa8, 0x17, 0xf8, 0xd5, 0xae, 0xd0, 0x06, 0x38, 0xf9, 0x46, 0xa0, 0xff, 0xd6, 0x7a, 0x53,
	0x17, 0xfa, 0x51, 0x1c, 0x4b, 0x54, 0xaa, 0x59, 0x43, 0xfb, 0xa4, 0x4f, 0xc0, 0xfa, 0xb1, 0x28,
	0x17, 0x15, 0x2f, 0x9b, 0xe4, 0x06, 0x86, 0x9d, 0x19, 0x44, 0x1f, 0x83, 0xb6, 0x6b, 0x05, 0x36,
	0xb5, 0x23, 0x91, 0xc5, 0x4d, 0x79, 0x0c, 0x56, 0xcd, 0x54, 0xca, 0x57, 0x68, 0xa2, 0x72, 0x42,
	0x30, 0xe8, 0x42, 0x93, 0xc5, 0xf4, 0x6a, 0xeb, 0x91, 0xeb, 0xad, 0x47, 0xfe, 0x6e, 0x3d, 0xf2,
	0x63, 0xe7, 0x75, 0xae, 0x77, 0x5e, 0xe7, 0xf7, 0xce, 0xeb, 0x7c, 0x3e, 0xbd, 0x35, 0xb5, 0xfe,
	0x27, 0x6a, 0xd9, 0x33, 0xff, 0xe8, 0xe5, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x92, 0xf0, 0x40,
	0xe5, 0x91, 0x02, 0x00, 0x00,
}

func (m *FeeEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FeeEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FeeEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Fee) > 0 {
		i -= len(m.Fee)
		copy(dAtA[i:], m.Fee)
		i = encodeVarintCoin(dAtA, i, uint64(len(m.Fee)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.MsgTypeUrl) > 0 {
		i -= len(m.MsgTypeUrl)
		copy(dAtA[i:], m.MsgTypeUrl)
		i = encodeVarintCoin(dAtA, i, uint64(len(m.MsgTypeUrl)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.OldBurnBps != 0 {
		i = encodeVarintCoin(dAtA, i, uint64(m.OldBurnBps))
		i--
		dAtA[i] = 0x38
	}
	if m.YoungBurnBps != 0 {
		i = encodeVarintCoin(dAtA, i, uint64(m.YoungBurnBps))
		i--
		dAtA[i] = 0x30
	}
	if m.CoinAgeThresholdSeconds != 0 {
		i = encodeVarintCoin(dAtA, i, uint64(m.CoinAgeThresholdSeconds))
		i--
		dAtA[i] = 0x28
	}
	if m.MicroDailyQuota != 0 {
		i = encodeVarintCoin(dAtA, i, uint64(m.MicroDailyQuota))
		i--
		dAtA[i] = 0x20
	}
	if len(m.MicroThreshold) > 0 {
		i -= len(m.MicroThreshold)
		copy(dAtA[i:], m.MicroThreshold)
		i = encodeVarintCoin(dAtA, i, uint64(len(m.MicroThreshold)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.DefaultFee) > 0 {
		i -= len(m.DefaultFee)
		copy(dAtA[i:], m.DefaultFee)
		i = encodeVarintCoin(dAtA, i, uint64(len(m.DefaultFee)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Fees) > 0 {
		for iNdEx := len(m.Fees) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Fees[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCoin(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *CoinAge) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CoinAge) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CoinAge) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.YoungSince != 0 {
		i = encodeVarintCoin(dAtA, i, uint64(m.YoungSince))
		i--
		dAtA[i] = 0x20
	}
	if len(m.OldAmount) > 0 {
		i -= len(m.OldAmount)
		copy(dAtA[i:], m.OldAmount)
		i = encodeVarintCoin(dAtA, i, uint64(len(m.OldAmount)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.YoungAmount) > 0 {
		i -= len(m.YoungAmount)
		copy(dAtA[i:], m.YoungAmount)
		i = encodeVarintCoin(dAtA, i, uint64(len(m.YoungAmount)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintCoin(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintCoin(dAtA []byte, offset int, v uint64) int {
	offset -= sovCoin(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *FeeEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MsgTypeUrl)
	if l > 0 {
		n += 1 + l + sovCoin(uint64(l))
	}
	l = len(m.Fee)
	if l > 0 {
		n += 1 + l + sovCoin(uint64(l))
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Fees) > 0 {
		for _, e := range m.Fees {
			l = e.Size()
			n += 1 + l + sovCoin(uint64(l))
		}
	}
	l = len(m.DefaultFee)
	if l > 0 {
		n += 1 + l + sovCoin(uint64(l))
	}
	l = len(m.MicroThreshold)
	if l > 0 {
		n += 1 + l + sovCoin(uint64(l))
	}
	if m.MicroDailyQuota != 0 {
		n += 1 + sovCoin(uint64(m.MicroDailyQuota))
	}
	if m.CoinAgeThresholdSeconds != 0 {
		n += 1 + sovCoin(uint64(m.CoinAgeThresholdSeconds))
	}
	if m.YoungBurnBps != 0 {
		n += 1 + sovCoin(uint64(m.YoungBurnBps))
	}
	if m.OldBurnBps != 0 {
		n += 1 + sovCoin(uint64(m.OldBurnBps))
	}
	return n
}

func (m *CoinAge) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovCoin(uint64(l))
	}
	l = len(m.YoungAmount)
	if l > 0 {
		n += 1 + l + sovCoin(uint64(l))
	}
	l = len(m.OldAmount)
	if l > 0 {
		n += 1 + l + sovCoin(uint64(l))
	}
	if m.YoungSince != 0 {
		n += 1 + sovCoin(uint64(m.YoungSince))
	}
	return n
}

func sovCoin(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCoin(x uint64) (n int) {
	return sovCoin(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *FeeEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCoin
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FeeEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FeeEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgTypeUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCoin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCoin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MsgTypeUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCoin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCoin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Fee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCoin(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCoin
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCoin
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fees", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCoin
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCoin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Fees = append(m.Fees, FeeEntry{})
			if err := m.Fees[len(m.Fees)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCoin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCoin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DefaultFee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MicroThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCoin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCoin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MicroThreshold = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MicroDailyQuota", wireType)
			}
			m.MicroDailyQuota = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MicroDailyQuota |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoinAgeThresholdSeconds", wireType)
			}
			m.CoinAgeThresholdSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CoinAgeThresholdSeconds |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field YoungBurnBps", wireType)
			}
			m.YoungBurnBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.YoungBurnBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OldBurnBps", wireType)
			}
			m.OldBurnBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OldBurnBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCoin(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCoin
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CoinAge) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCoin
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CoinAge: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CoinAge: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCoin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCoin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field YoungAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCoin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCoin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.YoungAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OldAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCoin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCoin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OldAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field YoungSince", wireType)
			}
			m.YoungSince = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.YoungSince |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCoin(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCoin
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCoin(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCoin
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCoin
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCoin
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCoin
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCoin
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCoin
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCoin        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCoin          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCoin = fmt.Errorf("proto: unexpected end of group")
)
