// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: phi/coin/coin.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// FeeEntry is one row of the per-message-type fixed-fee table.
type FeeEntry struct {
	// Message type (Msg type URL), e.g. /phi.coin.MsgTransfer
	MsgTypeUrl string `protobuf:"bytes,1,opt,name=msg_type_url,json=msgTypeUrl,proto3" json:"msg_type_url,omitempty"`
	// Fixed fee (uphi)
	Fee string `protobuf:"bytes,2,opt,name=fee,proto3" json:"fee,omitempty"`
}

func (m *FeeEntry) Reset()         { *m = FeeEntry{} }
func (m *FeeEntry) String() string { return proto.CompactTextString(m) }
func (*FeeEntry) ProtoMessage()    {}
func (*FeeEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_87c3c64ab5dc5a1b, []int{0}
}
func (m *FeeEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FeeEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FeeEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FeeEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeEntry.Merge(m, src)
}
func (m *FeeEntry) XXX_Size() int {
	return m.Size()
}
func (m *FeeEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeEntry.DiscardUnknown(m)
}

var xxx_messageInfo_FeeEntry proto.InternalMessageInfo

func (m *FeeEntry) GetMsgTypeUrl() string {
	if m != nil {
		return m.MsgTypeUrl
	}
	return ""
}

func (m *FeeEntry) GetFee() string {
	if m != nil {
		return m.Fee
	}
	return ""
}

// SplitEntry is one row of the revenue-split table: how the fixed fee charged for a message type is
// divided between the validator set and the company. The company share is computed from company_bps
// and the validator leg takes the remainder, so the two parts always sum to the fee exactly.
// validator_bps is therefore the nominal validator share; any bps shortfall accrues to it.
type SplitEntry struct {
	// Message type (Msg type URL), e.g. /phi.coin.MsgTransfer
	MsgTypeUrl string `protobuf:"bytes,1,opt,name=msg_type_url,json=msgTypeUrl,proto3" json:"msg_type_url,omitempty"`
	// Validator share (bps; 1bp=0.01%) — routed to the standard fee collector
	ValidatorBps uint32 `protobuf:"varint,2,opt,name=validator_bps,json=validatorBps,proto3" json:"validator_bps,omitempty"`
	// Company share (bps) — routed to the keyless phi_revenue module account
	CompanyBps uint32 `protobuf:"varint,3,opt,name=company_bps,json=companyBps,proto3" json:"company_bps,omitempty"`
}

func (m *SplitEntry) Reset()         { *m = SplitEntry{} }
func (m *SplitEntry) String() string { return proto.CompactTextString(m) }
func (*SplitEntry) ProtoMessage()    {}
func (*SplitEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_87c3c64ab5dc5a1b, []int{1}
}
func (m *SplitEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SplitEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SplitEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SplitEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SplitEntry.Merge(m, src)
}
func (m *SplitEntry) XXX_Size() int {
	return m.Size()
}
func (m *SplitEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_SplitEntry.DiscardUnknown(m)
}

var xxx_messageInfo_SplitEntry proto.InternalMessageInfo

func (m *SplitEntry) GetMsgTypeUrl() string {
	if m != nil {
		return m.MsgTypeUrl
	}
	return ""
}

func (m *SplitEntry) GetValidatorBps() uint32 {
	if m != nil {
		return m.ValidatorBps
	}
	return 0
}

func (m *SplitEntry) GetCompanyBps() uint32 {
	if m != nil {
		return m.CompanyBps
	}
	return 0
}

// Params holds the coin module's economic parameters; changeable only via governance.
type Params struct {
	// Per-message-type fixed-fee table (uphi)
	Fees []FeeEntry `protobuf:"bytes,1,rep,name=fees,proto3" json:"fees"`
	// Default fee when the message type is not in the table (uphi)
	DefaultFee string `protobuf:"bytes,2,opt,name=default_fee,json=defaultFee,proto3" json:"default_fee,omitempty"`
	// Micro-exemption threshold (uphi); a transaction smaller than this draws from the free quota
	MicroThreshold string `protobuf:"bytes,3,opt,name=micro_threshold,json=microThreshold,proto3" json:"micro_threshold,omitempty"`
	// Daily micro-exemption quota per DID
	MicroDailyQuota uint64 `protobuf:"varint,4,opt,name=micro_daily_quota,json=microDailyQuota,proto3" json:"micro_daily_quota,omitempty"`
	// Coin-age threshold duration (seconds): below it "young", above it "old"
	CoinAgeThresholdSeconds int64 `protobuf:"varint,5,opt,name=coin_age_threshold_seconds,json=coinAgeThresholdSeconds,proto3" json:"coin_age_threshold_seconds,omitempty"`
	// Early-redeem penalty rate for YOUNG coin (bps; 1bp=0.01%) — default 1% = 100.
	// Nothing is burned by this: the penalty is carved out of the redeemed uphi and routed to
	// phi_revenue as network revenue (it was misnamed "burn" while it was an off-chain payout cut).
	YoungPenaltyBps uint32 `protobuf:"varint,6,opt,name=young_penalty_bps,json=youngPenaltyBps,proto3" json:"young_penalty_bps,omitempty"`
	// Early-redeem penalty rate for OLD coin (bps) — default 0.2% = 20.
	OldPenaltyBps uint32 `protobuf:"varint,7,opt,name=old_penalty_bps,json=oldPenaltyBps,proto3" json:"old_penalty_bps,omitempty"`
	// Revenue-split table; a message type absent from it pays its whole fee to the fee collector
	Splits []SplitEntry `protobuf:"bytes,8,rep,name=splits,proto3" json:"splits"`
	// Destination of a governance-authorised revenue withdrawal from phi_revenue (bech32).
	// Empty disables withdrawals; it is never a fee sink, only a withdrawal target.
	CompanyPayoutAddress string `protobuf:"bytes,9,opt,name=company_payout_address,json=companyPayoutAddress,proto3" json:"company_payout_address,omitempty"`
	// Surcharge (uphi) per required signer of an agreement beyond agreement_free_signers.
	// Empty or "0" disables the surcharge. This is the only CONTENT-dependent fee: an agreement's
	// price depends on how many signers its own message declares.
	AgreementExtraSignerFee string `protobuf:"bytes,10,opt,name=agreement_extra_signer_fee,json=agreementExtraSignerFee,proto3" json:"agreement_extra_signer_fee,omitempty"`
	// Number of an agreement's required signers that carry no surcharge (the 6th signer is the first
	// charged when this is 5).
	AgreementFreeSigners uint32 `protobuf:"varint,11,opt,name=agreement_free_signers,json=agreementFreeSigners,proto3" json:"agreement_free_signers,omitempty"`
	// Maximum coin-age lots a holder's FIFO queue may hold (state/gas bound; default 64). On overflow
	// the two OLDEST lots are merged, so a dust-spammer only ever fills their victim's queue up to
	// this bound and can never dilute the victim's aged coin.
	MaxCoinAgeLots uint32 `protobuf:"varint,12,opt,name=max_coin_age_lots,json=maxCoinAgeLots,proto3" json:"max_coin_age_lots,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_87c3c64ab5dc5a1b, []int{2}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetFees() []FeeEntry {
	if m != nil {
		return m.Fees
	}
	return nil
}

func (m *Params) GetDefaultFee() string {
	if m != nil {
		return m.DefaultFee
	}
	return ""
}

func (m *Params) GetMicroThreshold() string {
	if m != nil {
		return m.MicroThreshold
	}
	return ""
}

func (m *Params) GetMicroDailyQuota() uint64 {
	if m != nil {
		return m.MicroDailyQuota
	}
	return 0
}

func (m *Params) GetCoinAgeThresholdSeconds() int64 {
	if m != nil {
		return m.CoinAgeThresholdSeconds
	}
	return 0
}

func (m *Params) GetYoungPenaltyBps() uint32 {
	if m != nil {
		return m.YoungPenaltyBps
	}
	return 0
}

func (m *Params) GetOldPenaltyBps() uint32 {
	if m != nil {
		return m.OldPenaltyBps
	}
	return 0
}

func (m *Params) GetSplits() []SplitEntry {
	if m != nil {
		return m.Splits
	}
	return nil
}

func (m *Params) GetCompanyPayoutAddress() string {
	if m != nil {
		return m.CompanyPayoutAddress
	}
	return ""
}

func (m *Params) GetAgreementExtraSignerFee() string {
	if m != nil {
		return m.AgreementExtraSignerFee
	}
	return ""
}

func (m *Params) GetAgreementFreeSigners() uint32 {
	if m != nil {
		return m.AgreementFreeSigners
	}
	return 0
}

func (m *Params) GetMaxCoinAgeLots() uint32 {
	if m != nil {
		return m.MaxCoinAgeLots
	}
	return 0
}

// CoinLot is one parcel of coin a holder acquired at a single moment. The lot is the unit the
// early-redeem penalty is priced on: its age decides its tier, so age is a property of the COIN, not
// of the account.
type CoinLot struct {
	// Amount (uphi)
	Amount string `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	// When this coin was acquired (Unix seconds, from block time — never a wall clock)
	AcquiredAt int64 `protobuf:"varint,2,opt,name=acquired_at,json=acquiredAt,proto3" json:"acquired_at,omitempty"`
}

func (m *CoinLot) Reset()         { *m = CoinLot{} }
func (m *CoinLot) String() string { return proto.CompactTextString(m) }
func (*CoinLot) ProtoMessage()    {}
func (*CoinLot) Descriptor() ([]byte, []int) {
	return fileDescriptor_87c3c64ab5dc5a1b, []int{3}
}
func (m *CoinLot) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CoinLot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CoinLot.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CoinLot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoinLot.Merge(m, src)
}
func (m *CoinLot) XXX_Size() int {
	return m.Size()
}
func (m *CoinLot) XXX_DiscardUnknown() {
	xxx_messageInfo_CoinLot.DiscardUnknown(m)
}

var xxx_messageInfo_CoinLot proto.InternalMessageInfo

func (m *CoinLot) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *CoinLot) GetAcquiredAt() int64 {
	if m != nil {
		return m.AcquiredAt
	}
	return 0
}

// CoinAge is a holder's FIFO queue of coin lots, ordered OLDEST → NEWEST.
//
// Coin is consumed oldest-first, so a holder's aged coin leaves (and is priced) before their fresh
// coin. Age travels with the coin across transfers: the recipient inherits the sender's acquired_at,
// so a transfer cannot rejuvenate coin.
//
// The queue is bounded by params.max_coin_age_lots. On overflow the two OLDEST adjacent lots are
// merged (keeping the older timestamp) — never the youngest. Merging at the young end would let an
// attacker dust a victim with fresh coin and drag the victim's aged balance younger; merging at the
// old end makes that attack pointless.
type CoinAge struct {
	// Owner address (bech32)
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Lots, ordered oldest → newest
	Lots []CoinLot `protobuf:"bytes,5,rep,name=lots,proto3" json:"lots"`
}

func (m *CoinAge) Reset()         { *m = CoinAge{} }
func (m *CoinAge) String() string { return proto.CompactTextString(m) }
func (*CoinAge) ProtoMessage()    {}
func (*CoinAge) Descriptor() ([]byte, []int) {
	return fileDescriptor_87c3c64ab5dc5a1b, []int{4}
}
func (m *CoinAge) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CoinAge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CoinAge.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CoinAge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoinAge.Merge(m, src)
}
func (m *CoinAge) XXX_Size() int {
	return m.Size()
}
func (m *CoinAge) XXX_DiscardUnknown() {
	xxx_messageInfo_CoinAge.DiscardUnknown(m)
}

var xxx_messageInfo_CoinAge proto.InternalMessageInfo

func (m *CoinAge) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CoinAge) GetLots() []CoinLot {
	if m != nil {
		return m.Lots
	}
	return nil
}

func init() {
	proto.RegisterType((*FeeEntry)(nil), "phi.coin.FeeEntry")
	proto.RegisterType((*SplitEntry)(nil), "phi.coin.SplitEntry")
	proto.RegisterType((*Params)(nil), "phi.coin.Params")
	proto.RegisterType((*CoinLot)(nil), "phi.coin.CoinLot")
	proto.RegisterType((*CoinAge)(nil), "phi.coin.CoinAge")
}

func init() { proto.RegisterFile("phi/coin/coin.proto", fileDescriptor_87c3c64ab5dc5a1b) }

var fileDescriptor_87c3c64ab5dc5a1b = []byte{
	// 684 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xc1, 0x4e, 0xdb, 0x4c,
	0x10, 0x8e, 0x89, 0x09, 0x61, 0x12, 0x20, 0xf1, 0x1f, 0x05, 0x8b, 0x43, 0x88, 0xf2, 0x4b, 0x6d,
	0x4a, 0x4b, 0x22, 0x51, 0x4e, 0xad, 0x54, 0x29, 0x29, 0xa0, 0x16, 0x71, 0x48, 0x0d, 0xbd, 0xf4,
	0x62, 0x2d, 0xf6, 0xc4, 0xb1, 0x64, 0x7b, 0xcd, 0xee, 0xba, 0x4a, 0x1e, 0xa1, 0x3d, 0xf5, 0x51,
	0xfa, 0x18, 0x1c, 0x39, 0xf6, 0xd2, 0xaa, 0x82, 0x43, 0x5f, 0xa3, 0xda, 0x5d, 0x3b, 0xe1, 0xd8,
	0x8b, 0xb5, 0xfb, 0x7d, 0xdf, 0xcc, 0xee, 0x7c, 0x33, 0x6b, 0xf8, 0x2f, 0x9d, 0x85, 0x43, 0x8f,
	0x86, 0x89, 0xfa, 0x0c, 0x52, 0x46, 0x05, 0xb5, 0xaa, 0xe9, 0x2c, 0x1c, 0xc8, 0xfd, 0x5e, 0x2b,
	0xa0, 0x01, 0x55, 0xe0, 0x50, 0xae, 0x34, 0xbf, 0xd7, 0x24, 0x71, 0x98, 0xd0, 0xa1, 0xfa, 0x6a,
	0xa8, 0xf7, 0x06, 0xaa, 0x67, 0x88, 0xa7, 0x89, 0x60, 0x0b, 0xab, 0x0b, 0xf5, 0x98, 0x07, 0xae,
	0x58, 0xa4, 0xe8, 0x66, 0x2c, 0xb2, 0x8d, 0xae, 0xd1, 0xdf, 0x74, 0x20, 0xe6, 0xc1, 0xd5, 0x22,
	0xc5, 0x8f, 0x2c, 0xb2, 0x1a, 0x50, 0x9e, 0x22, 0xda, 0x6b, 0x8a, 0x90, 0xcb, 0x9e, 0x00, 0xb8,
	0x4c, 0xa3, 0x50, 0xfc, 0x6b, 0x86, 0xff, 0x61, 0xeb, 0x33, 0x89, 0x42, 0x9f, 0x08, 0xca, 0xdc,
	0xeb, 0x94, 0xab, 0x5c, 0x5b, 0x4e, 0x7d, 0x09, 0x8e, 0x53, 0x6e, 0xed, 0x43, 0xcd, 0xa3, 0x71,
	0x4a, 0x92, 0x85, 0x92, 0x94, 0x95, 0x04, 0x72, 0x68, 0x9c, 0xf2, 0xde, 0x4f, 0x13, 0x2a, 0x13,
	0xc2, 0x48, 0xcc, 0xad, 0x17, 0x60, 0x4e, 0x11, 0xb9, 0x6d, 0x74, 0xcb, 0xfd, 0xda, 0x91, 0x35,
	0x28, 0x2c, 0x18, 0x14, 0x65, 0x8d, 0xcd, 0xdb, 0x5f, 0xfb, 0x25, 0x47, 0xa9, 0x64, 0x66, 0x1f,
	0xa7, 0x24, 0x8b, 0x84, 0xbb, 0x2a, 0x04, 0x72, 0xe8, 0x0c, 0xd1, 0x7a, 0x0a, 0x3b, 0x71, 0xe8,
	0x31, 0xea, 0x8a, 0x19, 0x43, 0x3e, 0xa3, 0x91, 0xaf, 0x8e, 0xdf, 0x74, 0xb6, 0x15, 0x7c, 0x55,
	0xa0, 0xd6, 0x01, 0x34, 0xb5, 0xd0, 0x27, 0x61, 0xb4, 0x70, 0x6f, 0x32, 0x2a, 0x88, 0x6d, 0x76,
	0x8d, 0xbe, 0xe9, 0xe8, 0x0c, 0x27, 0x12, 0xff, 0x20, 0x61, 0xeb, 0x35, 0xec, 0xc9, 0x2b, 0xb9,
	0x24, 0xc0, 0x55, 0x5e, 0x97, 0xa3, 0x47, 0x13, 0x9f, 0xdb, 0xeb, 0x5d, 0xa3, 0x5f, 0x76, 0x76,
	0xa5, 0x62, 0x14, 0xe0, 0xf2, 0x84, 0x4b, 0x4d, 0xcb, 0x83, 0x16, 0x34, 0x4b, 0x02, 0x37, 0xc5,
	0x84, 0x44, 0x42, 0x5b, 0x52, 0x51, 0x96, 0xec, 0x28, 0x62, 0xa2, 0x71, 0x69, 0xdc, 0x13, 0xd8,
	0x91, 0x99, 0x1f, 0x2b, 0x37, 0x94, 0x72, 0x8b, 0x46, 0xfe, 0x23, 0xdd, 0x11, 0x54, 0xb8, 0xec,
	0x1a, 0xb7, 0xab, 0xca, 0xb6, 0xd6, 0xca, 0xb6, 0x55, 0x37, 0x73, 0xe3, 0x72, 0xa5, 0x75, 0x0c,
	0xed, 0xa2, 0x29, 0x29, 0x59, 0xd0, 0x4c, 0xb8, 0xc4, 0xf7, 0x19, 0x72, 0x6e, 0x6f, 0x2a, 0x83,
	0x5a, 0x39, 0x3b, 0x51, 0xe4, 0x48, 0x73, 0xb2, 0x74, 0x12, 0x30, 0xc4, 0x18, 0x13, 0xe1, 0xe2,
	0x5c, 0x30, 0xe2, 0xf2, 0x30, 0x48, 0x90, 0x29, 0xff, 0x41, 0x45, 0xee, 0x2e, 0x15, 0xa7, 0x52,
	0x70, 0xa9, 0x78, 0xd9, 0x8c, 0x63, 0x68, 0xaf, 0x82, 0xa7, 0x0c, 0x31, 0x8f, 0xe5, 0x76, 0x4d,
	0x55, 0xd5, 0x5a, 0xb2, 0x67, 0x0c, 0x51, 0xc7, 0x71, 0xeb, 0x19, 0x34, 0x63, 0x32, 0x77, 0x97,
	0x8e, 0x47, 0x54, 0x70, 0xbb, 0xae, 0x02, 0xb6, 0x63, 0x32, 0x7f, 0xab, 0x7d, 0xbe, 0xa0, 0x82,
	0xbf, 0x6a, 0x7f, 0xfd, 0xf3, 0xfd, 0xa0, 0x29, 0x9f, 0xd2, 0x5c, 0x3f, 0x26, 0x3d, 0x54, 0xbd,
	0x31, 0x6c, 0x48, 0xd9, 0x05, 0x15, 0x56, 0x1b, 0x2a, 0x24, 0xa6, 0x59, 0x22, 0xf2, 0x61, 0xce,
	0x77, 0x72, 0x92, 0x88, 0x77, 0x93, 0x85, 0x0c, 0x7d, 0x97, 0x08, 0x35, 0x49, 0x65, 0x07, 0x0a,
	0x68, 0x24, 0x7a, 0x5f, 0x0c, 0x9d, 0x64, 0x14, 0xa0, 0x65, 0xc3, 0x46, 0x61, 0x96, 0xce, 0x52,
	0x6c, 0xad, 0xe7, 0x60, 0xaa, 0xfb, 0xad, 0xab, 0x3e, 0x34, 0x57, 0x7d, 0xc8, 0xcf, 0x2f, 0xa6,
	0x57, 0x8a, 0xce, 0xcd, 0xea, 0x5a, 0xa3, 0x7c, 0x6e, 0x56, 0xcb, 0x0d, 0xf3, 0xdc, 0xac, 0x9a,
	0x8d, 0x75, 0xa7, 0xae, 0x47, 0x43, 0xdf, 0xc9, 0x01, 0xd9, 0xfc, 0x7c, 0x5d, 0xd3, 0x0c, 0x0f,
	0x13, 0x0f, 0xc7, 0x27, 0xb7, 0xf7, 0x1d, 0xe3, 0xee, 0xbe, 0x63, 0xfc, 0xbe, 0xef, 0x18, 0xdf,
	0x1e, 0x3a, 0xa5, 0xbb, 0x87, 0x4e, 0xe9, 0xc7, 0x43, 0xa7, 0xf4, 0xe9, 0x20, 0x08, 0xc5, 0x2c,
	0xbb, 0x1e, 0x78, 0x34, 0x1e, 0x4e, 0x28, 0x13, 0x87, 0x93, 0x77, 0xef, 0x87, 0xe9, 0x2c, 0x3c,
	0xf4, 0x66, 0x24, 0x4c, 0x0a, 0x5b, 0xe4, 0x83, 0xe6, 0xd7, 0x15, 0xf5, 0xcb, 0x78, 0xf9, 0x37,
	0x00, 0x00, 0xff, 0xff, 0x89, 0x51, 0x59, 0x75, 0x7c, 0x04, 0x00, 0x00,
}

func (m *FeeEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FeeEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FeeEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Fee) > 0 {
		i -= len(m.Fee)
		copy(dAtA[i:], m.Fee)
		i = encodeVarintCoin(dAtA, i, uint64(len(m.Fee)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.MsgTypeUrl) > 0 {
		i -= len(m.MsgTypeUrl)
		copy(dAtA[i:], m.MsgTypeUrl)
		i = encodeVarintCoin(dAtA, i, uint64(len(m.MsgTypeUrl)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SplitEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SplitEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SplitEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CompanyBps != 0 {
		i = encodeVarintCoin(dAtA, i, uint64(m.CompanyBps))
		i--
		dAtA[i] = 0x18
	}
	if m.ValidatorBps != 0 {
		i = encodeVarintCoin(dAtA, i, uint64(m.ValidatorBps))
		i--
		dAtA[i] = 0x10
	}
	if len(m.MsgTypeUrl) > 0 {
		i -= len(m.MsgTypeUrl)
		copy(dAtA[i:], m.MsgTypeUrl)
		i = encodeVarintCoin(dAtA, i, uint64(len(m.MsgTypeUrl)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxCoinAgeLots != 0 {
		i = encodeVarintCoin(dAtA, i, uint64(m.MaxCoinAgeLots))
		i--
		dAtA[i] = 0x60
	}
	if m.AgreementFreeSigners != 0 {
		i = encodeVarintCoin(dAtA, i, uint64(m.AgreementFreeSigners))
		i--
		dAtA[i] = 0x58
	}
	if len(m.AgreementExtraSignerFee) > 0 {
		i -= len(m.AgreementExtraSignerFee)
		copy(dAtA[i:], m.AgreementExtraSignerFee)
		i = encodeVarintCoin(dAtA, i, uint64(len(m.AgreementExtraSignerFee)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.CompanyPayoutAddress) > 0 {
		i -= len(m.CompanyPayoutAddress)
		copy(dAtA[i:], m.CompanyPayoutAddress)
		i = encodeVarintCoin(dAtA, i, uint64(len(m.CompanyPayoutAddress)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Splits) > 0 {
		for iNdEx := len(m.Splits) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Splits[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCoin(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if m.OldPenaltyBps != 0 {
		i = encodeVarintCoin(dAtA, i, uint64(m.OldPenaltyBps))
		i--
		dAtA[i] = 0x38
	}
	if m.YoungPenaltyBps != 0 {
		i = encodeVarintCoin(dAtA, i, uint64(m.YoungPenaltyBps))
		i--
		dAtA[i] = 0x30
	}
	if m.CoinAgeThresholdSeconds != 0 {
		i = encodeVarintCoin(dAtA, i, uint64(m.CoinAgeThresholdSeconds))
		i--
		dAtA[i] = 0x28
	}
	if m.MicroDailyQuota != 0 {
		i = encodeVarintCoin(dAtA, i, uint64(m.MicroDailyQuota))
		i--
		dAtA[i] = 0x20
	}
	if len(m.MicroThreshold) > 0 {
		i -= len(m.MicroThreshold)
		copy(dAtA[i:], m.MicroThreshold)
		i = encodeVarintCoin(dAtA, i, uint64(len(m.MicroThreshold)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.DefaultFee) > 0 {
		i -= len(m.DefaultFee)
		copy(dAtA[i:], m.DefaultFee)
		i = encodeVarintCoin(dAtA, i, uint64(len(m.DefaultFee)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Fees) > 0 {
		for iNdEx := len(m.Fees) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Fees[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCoin(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *CoinLot) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CoinLot) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CoinLot) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AcquiredAt != 0 {
		i = encodeVarintCoin(dAtA, i, uint64(m.AcquiredAt))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintCoin(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CoinAge) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CoinAge) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CoinAge) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Lots) > 0 {
		for iNdEx := len(m.Lots) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Lots[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCoin(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintCoin(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintCoin(dAtA []byte, offset int, v uint64) int {
	offset -= sovCoin(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *FeeEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MsgTypeUrl)
	if l > 0 {
		n += 1 + l + sovCoin(uint64(l))
	}
	l = len(m.Fee)
	if l > 0 {
		n += 1 + l + sovCoin(uint64(l))
	}
	return n
}

func (m *SplitEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MsgTypeUrl)
	if l > 0 {
		n += 1 + l + sovCoin(uint64(l))
	}
	if m.ValidatorBps != 0 {
		n += 1 + sovCoin(uint64(m.ValidatorBps))
	}
	if m.CompanyBps != 0 {
		n += 1 + sovCoin(uint64(m.CompanyBps))
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Fees) > 0 {
		for _, e := range m.Fees {
			l = e.Size()
			n += 1 + l + sovCoin(uint64(l))
		}
	}
	l = len(m.DefaultFee)
	if l > 0 {
		n += 1 + l + sovCoin(uint64(l))
	}
	l = len(m.MicroThreshold)
	if l > 0 {
		n += 1 + l + sovCoin(uint64(l))
	}
	if m.MicroDailyQuota != 0 {
		n += 1 + sovCoin(uint64(m.MicroDailyQuota))
	}
	if m.CoinAgeThresholdSeconds != 0 {
		n += 1 + sovCoin(uint64(m.CoinAgeThresholdSeconds))
	}
	if m.YoungPenaltyBps != 0 {
		n += 1 + sovCoin(uint64(m.YoungPenaltyBps))
	}
	if m.OldPenaltyBps != 0 {
		n += 1 + sovCoin(uint64(m.OldPenaltyBps))
	}
	if len(m.Splits) > 0 {
		for _, e := range m.Splits {
			l = e.Size()
			n += 1 + l + sovCoin(uint64(l))
		}
	}
	l = len(m.CompanyPayoutAddress)
	if l > 0 {
		n += 1 + l + sovCoin(uint64(l))
	}
	l = len(m.AgreementExtraSignerFee)
	if l > 0 {
		n += 1 + l + sovCoin(uint64(l))
	}
	if m.AgreementFreeSigners != 0 {
		n += 1 + sovCoin(uint64(m.AgreementFreeSigners))
	}
	if m.MaxCoinAgeLots != 0 {
		n += 1 + sovCoin(uint64(m.MaxCoinAgeLots))
	}
	return n
}

func (m *CoinLot) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovCoin(uint64(l))
	}
	if m.AcquiredAt != 0 {
		n += 1 + sovCoin(uint64(m.AcquiredAt))
	}
	return n
}

func (m *CoinAge) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovCoin(uint64(l))
	}
	if len(m.Lots) > 0 {
		for _, e := range m.Lots {
			l = e.Size()
			n += 1 + l + sovCoin(uint64(l))
		}
	}
	return n
}

func sovCoin(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCoin(x uint64) (n int) {
	return sovCoin(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *FeeEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCoin
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FeeEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FeeEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgTypeUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCoin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCoin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MsgTypeUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCoin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCoin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Fee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCoin(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCoin
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SplitEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCoin
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SplitEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SplitEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgTypeUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCoin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCoin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MsgTypeUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorBps", wireType)
			}
			m.ValidatorBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidatorBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompanyBps", wireType)
			}
			m.CompanyBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CompanyBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCoin(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCoin
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCoin
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fees", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCoin
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCoin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Fees = append(m.Fees, FeeEntry{})
			if err := m.Fees[len(m.Fees)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCoin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCoin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DefaultFee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MicroThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCoin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCoin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MicroThreshold = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MicroDailyQuota", wireType)
			}
			m.MicroDailyQuota = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MicroDailyQuota |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoinAgeThresholdSeconds", wireType)
			}
			m.CoinAgeThresholdSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CoinAgeThresholdSeconds |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field YoungPenaltyBps", wireType)
			}
			m.YoungPenaltyBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.YoungPenaltyBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OldPenaltyBps", wireType)
			}
			m.OldPenaltyBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OldPenaltyBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Splits", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCoin
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCoin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Splits = append(m.Splits, SplitEntry{})
			if err := m.Splits[len(m.Splits)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompanyPayoutAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCoin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCoin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CompanyPayoutAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AgreementExtraSignerFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCoin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCoin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AgreementExtraSignerFee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AgreementFreeSigners", wireType)
			}
			m.AgreementFreeSigners = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AgreementFreeSigners |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxCoinAgeLots", wireType)
			}
			m.MaxCoinAgeLots = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxCoinAgeLots |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCoin(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCoin
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CoinLot) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCoin
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CoinLot: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CoinLot: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCoin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCoin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AcquiredAt", wireType)
			}
			m.AcquiredAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AcquiredAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCoin(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCoin
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CoinAge) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCoin
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CoinAge: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CoinAge: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCoin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCoin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lots", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCoin
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCoin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Lots = append(m.Lots, CoinLot{})
			if err := m.Lots[len(m.Lots)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCoin(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCoin
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCoin(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCoin
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCoin
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCoin
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCoin
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCoin
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCoin
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCoin        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCoin          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCoin = fmt.Errorf("proto: unexpected end of group")
)
