// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: phi/credentials/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState is the credentials module genesis state.
type GenesisState struct {
	// Module parameters.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// Credential templates.
	Templates []CredentialTemplate `protobuf:"bytes,2,rep,name=templates,proto3" json:"templates"`
	// Credential anchors.
	Anchors []CredentialAnchor `protobuf:"bytes,3,rep,name=anchors,proto3" json:"anchors"`
	// Agreements.
	Agreements []Agreement `protobuf:"bytes,4,rep,name=agreements,proto3" json:"agreements"`
	// Personal anchors.
	PersonalAnchors []PersonalAnchor `protobuf:"bytes,5,rep,name=personal_anchors,json=personalAnchors,proto3" json:"personal_anchors"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fe58ddaed71f687, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetTemplates() []CredentialTemplate {
	if m != nil {
		return m.Templates
	}
	return nil
}

func (m *GenesisState) GetAnchors() []CredentialAnchor {
	if m != nil {
		return m.Anchors
	}
	return nil
}

func (m *GenesisState) GetAgreements() []Agreement {
	if m != nil {
		return m.Agreements
	}
	return nil
}

func (m *GenesisState) GetPersonalAnchors() []PersonalAnchor {
	if m != nil {
		return m.PersonalAnchors
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "phi.credentials.GenesisState")
}

func init() { proto.RegisterFile("phi/credentials/genesis.proto", fileDescriptor_3fe58ddaed71f687) }

var fileDescriptor_3fe58ddaed71f687 = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xcd, 0x4a, 0x33, 0x31,
	0x14, 0x86, 0x67, 0xda, 0x7e, 0xfd, 0x30, 0x15, 0x2a, 0x83, 0xe0, 0x50, 0x30, 0x6d, 0x75, 0xd3,
	0x4d, 0x27, 0x58, 0x71, 0x6f, 0xeb, 0xa2, 0x8a, 0x9b, 0x41, 0x5d, 0xb9, 0x91, 0x74, 0x3c, 0x4c,
	0x02, 0x9d, 0x24, 0x24, 0x11, 0xf4, 0x2e, 0xbc, 0xac, 0x2e, 0xbb, 0x74, 0x25, 0xd2, 0xe2, 0x7d,
	0x88, 0x69, 0xaa, 0xfd, 0x01, 0x77, 0x87, 0x79, 0x9f, 0xf7, 0x99, 0x43, 0x0e, 0x3a, 0x54, 0x8c,
	0x93, 0x4c, 0xc3, 0x23, 0x08, 0xcb, 0xe9, 0xd8, 0x90, 0x1c, 0x04, 0x18, 0x6e, 0x12, 0xa5, 0xa5,
	0x95, 0x51, 0x5d, 0x31, 0x9e, 0xac, 0xc4, 0x8d, 0xfd, 0x5c, 0xe6, 0xd2, 0x65, 0xe4, 0x7b, 0x5a,
	0x60, 0x8d, 0xf6, 0xa6, 0x65, 0x65, 0x5e, 0x20, 0x47, 0x9f, 0x25, 0xb4, 0x3b, 0x5c, 0xb8, 0x6f,
	0x2d, 0xb5, 0x10, 0x9d, 0xa1, 0xaa, 0xa2, 0x9a, 0x16, 0x26, 0x0e, 0x5b, 0x61, 0xa7, 0xd6, 0x3b,
	0x48, 0x36, 0xfe, 0x95, 0xa4, 0x2e, 0x1e, 0x54, 0x26, 0xef, 0xcd, 0xe0, 0xc6, 0xc3, 0xd1, 0x10,
	0xed, 0x58, 0x28, 0xd4, 0x98, 0x5a, 0x30, 0x71, 0xa9, 0x55, 0xee, 0xd4, 0x7a, 0xc7, 0x5b, 0xcd,
	0x8b, 0x9f, 0xf9, 0xce, 0xb3, 0xde, 0xf2, 0xdb, 0x8d, 0xfa, 0xe8, 0x3f, 0x15, 0x19, 0x93, 0xda,
	0xc4, 0x65, 0xa7, 0x69, 0xff, 0xa1, 0xe9, 0x3b, 0xd2, 0x4b, 0x96, 0xbd, 0xe8, 0x1c, 0x21, 0x9a,
	0x6b, 0x80, 0x02, 0x84, 0x35, 0x71, 0xc5, 0x59, 0x1a, 0x5b, 0x96, 0xfe, 0x12, 0xf1, 0xf5, 0x95,
	0x4e, 0x94, 0xa2, 0x3d, 0x05, 0xda, 0x48, 0x41, 0xc7, 0x0f, 0xcb, 0x6d, 0xfe, 0x39, 0x4f, 0x73,
	0xfb, 0x39, 0x3c, 0xb8, 0xb6, 0x4b, 0x5d, 0xad, 0x7d, 0x35, 0x83, 0xeb, 0xc9, 0x0c, 0x87, 0xd3,
	0x19, 0x0e, 0x3f, 0x66, 0x38, 0x7c, 0x9d, 0xe3, 0x60, 0x3a, 0xc7, 0xc1, 0xdb, 0x1c, 0x07, 0xf7,
	0x27, 0x39, 0xb7, 0xec, 0x69, 0x94, 0x64, 0xb2, 0x20, 0xa9, 0xd4, 0xb6, 0x9b, 0x5e, 0x5e, 0x11,
	0xc5, 0x78, 0x37, 0x63, 0x94, 0x0b, 0xf2, 0xbc, 0x76, 0x40, 0xfb, 0xa2, 0xc0, 0x8c, 0xaa, 0xee,
	0x76, 0xa7, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5c, 0x85, 0xa7, 0xd2, 0x26, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PersonalAnchors) > 0 {
		for iNdEx := len(m.PersonalAnchors) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PersonalAnchors[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Agreements) > 0 {
		for iNdEx := len(m.Agreements) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Agreements[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Anchors) > 0 {
		for iNdEx := len(m.Anchors) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Anchors[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Templates) > 0 {
		for iNdEx := len(m.Templates) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Templates[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.Templates) > 0 {
		for _, e := range m.Templates {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Anchors) > 0 {
		for _, e := range m.Anchors {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Agreements) > 0 {
		for _, e := range m.Agreements {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PersonalAnchors) > 0 {
		for _, e := range m.PersonalAnchors {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Templates", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Templates = append(m.Templates, CredentialTemplate{})
			if err := m.Templates[len(m.Templates)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Anchors", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Anchors = append(m.Anchors, CredentialAnchor{})
			if err := m.Anchors[len(m.Anchors)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Agreements", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Agreements = append(m.Agreements, Agreement{})
			if err := m.Agreements[len(m.Agreements)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PersonalAnchors", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PersonalAnchors = append(m.PersonalAnchors, PersonalAnchor{})
			if err := m.PersonalAnchors[len(m.PersonalAnchors)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
