// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: phi/credentials/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a453f00c63949feb, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

type QueryParamsResponse struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a453f00c63949feb, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryTemplateRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryTemplateRequest) Reset()         { *m = QueryTemplateRequest{} }
func (m *QueryTemplateRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTemplateRequest) ProtoMessage()    {}
func (*QueryTemplateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a453f00c63949feb, []int{2}
}
func (m *QueryTemplateRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTemplateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTemplateRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTemplateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTemplateRequest.Merge(m, src)
}
func (m *QueryTemplateRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTemplateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTemplateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTemplateRequest proto.InternalMessageInfo

func (m *QueryTemplateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type QueryTemplateResponse struct {
	Template CredentialTemplate `protobuf:"bytes,1,opt,name=template,proto3" json:"template"`
}

func (m *QueryTemplateResponse) Reset()         { *m = QueryTemplateResponse{} }
func (m *QueryTemplateResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTemplateResponse) ProtoMessage()    {}
func (*QueryTemplateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a453f00c63949feb, []int{3}
}
func (m *QueryTemplateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTemplateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTemplateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTemplateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTemplateResponse.Merge(m, src)
}
func (m *QueryTemplateResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTemplateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTemplateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTemplateResponse proto.InternalMessageInfo

func (m *QueryTemplateResponse) GetTemplate() CredentialTemplate {
	if m != nil {
		return m.Template
	}
	return CredentialTemplate{}
}

type QueryCredentialRequest struct {
	CredentialHashHex string `protobuf:"bytes,1,opt,name=credential_hash_hex,json=credentialHashHex,proto3" json:"credential_hash_hex,omitempty"`
}

func (m *QueryCredentialRequest) Reset()         { *m = QueryCredentialRequest{} }
func (m *QueryCredentialRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCredentialRequest) ProtoMessage()    {}
func (*QueryCredentialRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a453f00c63949feb, []int{4}
}
func (m *QueryCredentialRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCredentialRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCredentialRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCredentialRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCredentialRequest.Merge(m, src)
}
func (m *QueryCredentialRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCredentialRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCredentialRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCredentialRequest proto.InternalMessageInfo

func (m *QueryCredentialRequest) GetCredentialHashHex() string {
	if m != nil {
		return m.CredentialHashHex
	}
	return ""
}

type QueryCredentialResponse struct {
	Anchor CredentialAnchor `protobuf:"bytes,1,opt,name=anchor,proto3" json:"anchor"`
}

func (m *QueryCredentialResponse) Reset()         { *m = QueryCredentialResponse{} }
func (m *QueryCredentialResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCredentialResponse) ProtoMessage()    {}
func (*QueryCredentialResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a453f00c63949feb, []int{5}
}
func (m *QueryCredentialResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCredentialResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCredentialResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCredentialResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCredentialResponse.Merge(m, src)
}
func (m *QueryCredentialResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryCredentialResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCredentialResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCredentialResponse proto.InternalMessageInfo

func (m *QueryCredentialResponse) GetAnchor() CredentialAnchor {
	if m != nil {
		return m.Anchor
	}
	return CredentialAnchor{}
}

type QueryAgreementRequest struct {
	HashHex string `protobuf:"bytes,1,opt,name=hash_hex,json=hashHex,proto3" json:"hash_hex,omitempty"`
}

func (m *QueryAgreementRequest) Reset()         { *m = QueryAgreementRequest{} }
func (m *QueryAgreementRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAgreementRequest) ProtoMessage()    {}
func (*QueryAgreementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a453f00c63949feb, []int{6}
}
func (m *QueryAgreementRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAgreementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAgreementRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAgreementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAgreementRequest.Merge(m, src)
}
func (m *QueryAgreementRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAgreementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAgreementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAgreementRequest proto.InternalMessageInfo

func (m *QueryAgreementRequest) GetHashHex() string {
	if m != nil {
		return m.HashHex
	}
	return ""
}

type QueryAgreementResponse struct {
	Agreement Agreement `protobuf:"bytes,1,opt,name=agreement,proto3" json:"agreement"`
}

func (m *QueryAgreementResponse) Reset()         { *m = QueryAgreementResponse{} }
func (m *QueryAgreementResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAgreementResponse) ProtoMessage()    {}
func (*QueryAgreementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a453f00c63949feb, []int{7}
}
func (m *QueryAgreementResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAgreementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAgreementResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAgreementResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAgreementResponse.Merge(m, src)
}
func (m *QueryAgreementResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAgreementResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAgreementResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAgreementResponse proto.InternalMessageInfo

func (m *QueryAgreementResponse) GetAgreement() Agreement {
	if m != nil {
		return m.Agreement
	}
	return Agreement{}
}

type QueryPersonalAnchorRequest struct {
	OwnerDid      string `protobuf:"bytes,1,opt,name=owner_did,json=ownerDid,proto3" json:"owner_did,omitempty"`
	AnchorHashHex string `protobuf:"bytes,2,opt,name=anchor_hash_hex,json=anchorHashHex,proto3" json:"anchor_hash_hex,omitempty"`
}

func (m *QueryPersonalAnchorRequest) Reset()         { *m = QueryPersonalAnchorRequest{} }
func (m *QueryPersonalAnchorRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPersonalAnchorRequest) ProtoMessage()    {}
func (*QueryPersonalAnchorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a453f00c63949feb, []int{8}
}
func (m *QueryPersonalAnchorRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPersonalAnchorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPersonalAnchorRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPersonalAnchorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPersonalAnchorRequest.Merge(m, src)
}
func (m *QueryPersonalAnchorRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPersonalAnchorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPersonalAnchorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPersonalAnchorRequest proto.InternalMessageInfo

func (m *QueryPersonalAnchorRequest) GetOwnerDid() string {
	if m != nil {
		return m.OwnerDid
	}
	return ""
}

func (m *QueryPersonalAnchorRequest) GetAnchorHashHex() string {
	if m != nil {
		return m.AnchorHashHex
	}
	return ""
}

type QueryPersonalAnchorResponse struct {
	Anchor PersonalAnchor `protobuf:"bytes,1,opt,name=anchor,proto3" json:"anchor"`
}

func (m *QueryPersonalAnchorResponse) Reset()         { *m = QueryPersonalAnchorResponse{} }
func (m *QueryPersonalAnchorResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPersonalAnchorResponse) ProtoMessage()    {}
func (*QueryPersonalAnchorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a453f00c63949feb, []int{9}
}
func (m *QueryPersonalAnchorResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPersonalAnchorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPersonalAnchorResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPersonalAnchorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPersonalAnchorResponse.Merge(m, src)
}
func (m *QueryPersonalAnchorResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryPersonalAnchorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPersonalAnchorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPersonalAnchorResponse proto.InternalMessageInfo

func (m *QueryPersonalAnchorResponse) GetAnchor() PersonalAnchor {
	if m != nil {
		return m.Anchor
	}
	return PersonalAnchor{}
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "phi.credentials.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "phi.credentials.QueryParamsResponse")
	proto.RegisterType((*QueryTemplateRequest)(nil), "phi.credentials.QueryTemplateRequest")
	proto.RegisterType((*QueryTemplateResponse)(nil), "phi.credentials.QueryTemplateResponse")
	proto.RegisterType((*QueryCredentialRequest)(nil), "phi.credentials.QueryCredentialRequest")
	proto.RegisterType((*QueryCredentialResponse)(nil), "phi.credentials.QueryCredentialResponse")
	proto.RegisterType((*QueryAgreementRequest)(nil), "phi.credentials.QueryAgreementRequest")
	proto.RegisterType((*QueryAgreementResponse)(nil), "phi.credentials.QueryAgreementResponse")
	proto.RegisterType((*QueryPersonalAnchorRequest)(nil), "phi.credentials.QueryPersonalAnchorRequest")
	proto.RegisterType((*QueryPersonalAnchorResponse)(nil), "phi.credentials.QueryPersonalAnchorResponse")
}

func init() { proto.RegisterFile("phi/credentials/query.proto", fileDescriptor_a453f00c63949feb) }

var fileDescriptor_a453f00c63949feb = []byte{
	// 653 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x95, 0xc1, 0x6e, 0xd3, 0x4c,
	0x10, 0xc7, 0xe3, 0xe8, 0x6b, 0xbe, 0x64, 0x10, 0xad, 0xd8, 0x16, 0x4a, 0x5d, 0xe4, 0x50, 0x03,
	0x69, 0x25, 0xa8, 0x57, 0x04, 0x10, 0x02, 0x09, 0xaa, 0x16, 0x90, 0x82, 0xe0, 0x50, 0x22, 0x0e,
	0xa8, 0x42, 0x44, 0xdb, 0x78, 0x65, 0x5b, 0x4a, 0xbc, 0xae, 0xd7, 0x11, 0xa9, 0xa2, 0x5c, 0x7a,
	0xe6, 0x80, 0xc4, 0x91, 0x57, 0xe0, 0x41, 0x7a, 0xac, 0xc4, 0x85, 0x53, 0x85, 0x12, 0x1e, 0x04,
	0x65, 0xbd, 0xb6, 0x13, 0x3b, 0x4d, 0xb8, 0xad, 0x66, 0xff, 0x33, 0xf3, 0xdb, 0xc9, 0x7f, 0x62,
	0x58, 0xf7, 0x6c, 0x07, 0x37, 0x7d, 0x6a, 0x52, 0x37, 0x70, 0x48, 0x8b, 0xe3, 0xa3, 0x0e, 0xf5,
	0x8f, 0x0d, 0xcf, 0x67, 0x01, 0x43, 0x4b, 0x9e, 0xed, 0x18, 0x63, 0x97, 0xea, 0x8a, 0xc5, 0x2c,
	0x26, 0xee, 0xf0, 0xe8, 0x14, 0xca, 0xd4, 0x1b, 0x16, 0x63, 0x56, 0x8b, 0x62, 0xe2, 0x39, 0x98,
	0xb8, 0x2e, 0x0b, 0x48, 0xe0, 0x30, 0x97, 0xcb, 0xdb, 0x8d, 0x74, 0x87, 0xb1, 0x73, 0x28, 0xd1,
	0x57, 0x00, 0xbd, 0x1b, 0xb5, 0xdd, 0x27, 0x3e, 0x69, 0xf3, 0x3a, 0x3d, 0xea, 0x50, 0x1e, 0xe8,
	0x6f, 0x61, 0x79, 0x22, 0xca, 0x3d, 0xe6, 0x72, 0x8a, 0x1e, 0x41, 0xc1, 0x13, 0x91, 0xeb, 0xca,
	0x4d, 0x65, 0xeb, 0x52, 0x75, 0xd5, 0x48, 0x51, 0x1a, 0x61, 0xc2, 0xde, 0x7f, 0xa7, 0xe7, 0xe5,
	0x5c, 0x5d, 0x8a, 0xf5, 0x0a, 0xac, 0x88, 0x6a, 0xef, 0x69, 0xdb, 0x6b, 0x91, 0x80, 0xca, 0x2e,
	0x68, 0x11, 0xf2, 0x8e, 0x29, 0x4a, 0x95, 0xea, 0x79, 0xc7, 0xd4, 0x3f, 0xc1, 0xd5, 0x94, 0x4e,
	0xf6, 0x7d, 0x05, 0xc5, 0x40, 0xc6, 0x64, 0xe7, 0x5b, 0x99, 0xce, 0x2f, 0xe2, 0x73, 0x94, 0x2e,
	0x29, 0xe2, 0x54, 0xbd, 0x06, 0xd7, 0x44, 0xfd, 0x44, 0x1a, 0x91, 0x18, 0xb0, 0x9c, 0xd4, 0x6a,
	0xd8, 0x84, 0xdb, 0x0d, 0x9b, 0x76, 0x25, 0xda, 0x95, 0xe4, 0xaa, 0x46, 0xb8, 0x5d, 0xa3, 0x5d,
	0xfd, 0x00, 0x56, 0x33, 0x95, 0x24, 0xeb, 0x0e, 0x14, 0x88, 0xdb, 0xb4, 0x99, 0x2f, 0x49, 0x37,
	0x66, 0x90, 0xee, 0x0a, 0x61, 0x34, 0xad, 0x30, 0x4d, 0xaf, 0xca, 0x29, 0xec, 0x5a, 0x3e, 0xa5,
	0x6d, 0xea, 0x06, 0x11, 0xe4, 0x1a, 0x14, 0x53, 0x64, 0xff, 0xdb, 0x92, 0xe7, 0x83, 0x7c, 0xd9,
	0x58, 0x8e, 0xc4, 0x79, 0x0e, 0x25, 0x12, 0x05, 0x25, 0x91, 0x9a, 0x21, 0x8a, 0xd3, 0x24, 0x4a,
	0x92, 0xa2, 0x13, 0x50, 0x43, 0x27, 0x50, 0x9f, 0x33, 0x37, 0x42, 0x8e, 0x90, 0xd6, 0xa1, 0xc4,
	0x3e, 0xbb, 0xd4, 0x6f, 0x98, 0xf1, 0x0f, 0x59, 0x14, 0x81, 0x97, 0x8e, 0x89, 0x2a, 0xb0, 0x14,
	0x3e, 0x29, 0x19, 0x68, 0x5e, 0x48, 0x2e, 0x87, 0xe1, 0x68, 0x98, 0x1f, 0x61, 0x7d, 0x6a, 0x0b,
	0xf9, 0x82, 0x67, 0xa9, 0x81, 0x96, 0xb3, 0xa6, 0x9b, 0x48, 0x9c, 0x1c, 0x67, 0xf5, 0x7c, 0x01,
	0x16, 0x44, 0x79, 0x14, 0x40, 0x21, 0xb4, 0x27, 0xca, 0xba, 0x27, 0xbb, 0x03, 0xea, 0xed, 0xd9,
	0xa2, 0x90, 0x4e, 0x2f, 0x9f, 0xfc, 0xfc, 0xf3, 0x2d, 0xbf, 0x86, 0x56, 0x71, 0x7a, 0xd7, 0x42,
	0xf3, 0xa3, 0x13, 0x05, 0x8a, 0x91, 0x23, 0xd1, 0x9d, 0xe9, 0x35, 0x53, 0x8b, 0xa1, 0x56, 0xe6,
	0xc9, 0x64, 0xf3, 0x4d, 0xd1, 0x7c, 0x03, 0x95, 0x33, 0xcd, 0x23, 0xcf, 0x73, 0xdc, 0x73, 0xcc,
	0x3e, 0xfa, 0xae, 0x00, 0x24, 0xb6, 0x43, 0x9b, 0xd3, 0xeb, 0x67, 0xf6, 0x42, 0xdd, 0x9a, 0x2f,
	0x94, 0x28, 0x4f, 0x05, 0xca, 0x43, 0x54, 0xc5, 0x33, 0xfe, 0x73, 0x70, 0x6f, 0xca, 0x96, 0xf5,
	0xd1, 0x17, 0x05, 0x4a, 0xb1, 0x05, 0xd1, 0x05, 0x8f, 0x4f, 0xaf, 0x83, 0xba, 0x39, 0x57, 0x27,
	0xd1, 0x0c, 0x81, 0xb6, 0x85, 0x2a, 0x19, 0xb4, 0xd8, 0xe6, 0x1c, 0xf7, 0x12, 0x9c, 0x1f, 0x0a,
	0x2c, 0x4e, 0x5a, 0x0a, 0xdd, 0xbd, 0xc0, 0x0b, 0xd3, 0x96, 0x42, 0xbd, 0xf7, 0x6f, 0x62, 0x49,
	0xb7, 0x23, 0xe8, 0x9e, 0xa0, 0xc7, 0x59, 0x03, 0xc9, 0x04, 0xdc, 0x8b, 0x77, 0xac, 0x8f, 0x7b,
	0xa9, 0x95, 0xea, 0xef, 0xbd, 0x39, 0x1d, 0x68, 0xca, 0xd9, 0x40, 0x53, 0x7e, 0x0f, 0x34, 0xe5,
	0xeb, 0x50, 0xcb, 0x9d, 0x0d, 0xb5, 0xdc, 0xaf, 0xa1, 0x96, 0x3b, 0xb8, 0x6f, 0x39, 0x81, 0xdd,
	0x39, 0x34, 0x9a, 0xac, 0x8d, 0xf7, 0x99, 0x1f, 0x6c, 0xef, 0xd7, 0x5e, 0x8f, 0xba, 0x6c, 0x37,
	0x6d, 0xe2, 0xb8, 0xb8, 0x3b, 0xe9, 0x98, 0x63, 0x8f, 0xf2, 0xc3, 0x82, 0xf8, 0x2a, 0x3c, 0xf8,
	0x1b, 0x00, 0x00, 0xff, 0xff, 0x0d, 0xe0, 0x12, 0xab, 0x9c, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Params returns the current module parameters.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Template returns a credential template by id.
	Template(ctx context.Context, in *QueryTemplateRequest, opts ...grpc.CallOption) (*QueryTemplateResponse, error)
	// Credential returns a credential anchor by hex-encoded credential hash.
	Credential(ctx context.Context, in *QueryCredentialRequest, opts ...grpc.CallOption) (*QueryCredentialResponse, error)
	// Agreement returns an agreement by hex-encoded hash.
	Agreement(ctx context.Context, in *QueryAgreementRequest, opts ...grpc.CallOption) (*QueryAgreementResponse, error)
	// PersonalAnchor returns a personal anchor by owner DID and hex-encoded hash.
	PersonalAnchor(ctx context.Context, in *QueryPersonalAnchorRequest, opts ...grpc.CallOption) (*QueryPersonalAnchorResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/phi.credentials.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Template(ctx context.Context, in *QueryTemplateRequest, opts ...grpc.CallOption) (*QueryTemplateResponse, error) {
	out := new(QueryTemplateResponse)
	err := c.cc.Invoke(ctx, "/phi.credentials.Query/Template", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Credential(ctx context.Context, in *QueryCredentialRequest, opts ...grpc.CallOption) (*QueryCredentialResponse, error) {
	out := new(QueryCredentialResponse)
	err := c.cc.Invoke(ctx, "/phi.credentials.Query/Credential", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Agreement(ctx context.Context, in *QueryAgreementRequest, opts ...grpc.CallOption) (*QueryAgreementResponse, error) {
	out := new(QueryAgreementResponse)
	err := c.cc.Invoke(ctx, "/phi.credentials.Query/Agreement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PersonalAnchor(ctx context.Context, in *QueryPersonalAnchorRequest, opts ...grpc.CallOption) (*QueryPersonalAnchorResponse, error) {
	out := new(QueryPersonalAnchorResponse)
	err := c.cc.Invoke(ctx, "/phi.credentials.Query/PersonalAnchor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Params returns the current module parameters.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Template returns a credential template by id.
	Template(context.Context, *QueryTemplateRequest) (*QueryTemplateResponse, error)
	// Credential returns a credential anchor by hex-encoded credential hash.
	Credential(context.Context, *QueryCredentialRequest) (*QueryCredentialResponse, error)
	// Agreement returns an agreement by hex-encoded hash.
	Agreement(context.Context, *QueryAgreementRequest) (*QueryAgreementResponse, error)
	// PersonalAnchor returns a personal anchor by owner DID and hex-encoded hash.
	PersonalAnchor(context.Context, *QueryPersonalAnchorRequest) (*QueryPersonalAnchorResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Template(ctx context.Context, req *QueryTemplateRequest) (*QueryTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Template not implemented")
}
func (*UnimplementedQueryServer) Credential(ctx context.Context, req *QueryCredentialRequest) (*QueryCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Credential not implemented")
}
func (*UnimplementedQueryServer) Agreement(ctx context.Context, req *QueryAgreementRequest) (*QueryAgreementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Agreement not implemented")
}
func (*UnimplementedQueryServer) PersonalAnchor(ctx context.Context, req *QueryPersonalAnchorRequest) (*QueryPersonalAnchorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PersonalAnchor not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phi.credentials.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Template_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Template(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phi.credentials.Query/Template",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Template(ctx, req.(*QueryTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Credential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Credential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phi.credentials.Query/Credential",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Credential(ctx, req.(*QueryCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Agreement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAgreementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Agreement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phi.credentials.Query/Agreement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Agreement(ctx, req.(*QueryAgreementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PersonalAnchor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPersonalAnchorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PersonalAnchor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phi.credentials.Query/PersonalAnchor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PersonalAnchor(ctx, req.(*QueryPersonalAnchorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "phi.credentials.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Template",
			Handler:    _Query_Template_Handler,
		},
		{
			MethodName: "Credential",
			Handler:    _Query_Credential_Handler,
		},
		{
			MethodName: "Agreement",
			Handler:    _Query_Agreement_Handler,
		},
		{
			MethodName: "PersonalAnchor",
			Handler:    _Query_PersonalAnchor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "phi/credentials/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryTemplateRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTemplateRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTemplateRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryTemplateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTemplateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTemplateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Template.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryCredentialRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCredentialRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCredentialRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CredentialHashHex) > 0 {
		i -= len(m.CredentialHashHex)
		copy(dAtA[i:], m.CredentialHashHex)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.CredentialHashHex)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryCredentialResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCredentialResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCredentialResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Anchor.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAgreementRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAgreementRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAgreementRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.HashHex) > 0 {
		i -= len(m.HashHex)
		copy(dAtA[i:], m.HashHex)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.HashHex)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAgreementResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAgreementResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAgreementResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Agreement.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryPersonalAnchorRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPersonalAnchorRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPersonalAnchorRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AnchorHashHex) > 0 {
		i -= len(m.AnchorHashHex)
		copy(dAtA[i:], m.AnchorHashHex)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.AnchorHashHex)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.OwnerDid) > 0 {
		i -= len(m.OwnerDid)
		copy(dAtA[i:], m.OwnerDid)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.OwnerDid)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryPersonalAnchorResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPersonalAnchorResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPersonalAnchorResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Anchor.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryTemplateRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryTemplateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Template.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryCredentialRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CredentialHashHex)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryCredentialResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Anchor.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAgreementRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.HashHex)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAgreementResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Agreement.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryPersonalAnchorRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OwnerDid)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.AnchorHashHex)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryPersonalAnchorResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Anchor.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTemplateRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTemplateRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTemplateRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTemplateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTemplateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTemplateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Template", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Template.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCredentialRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCredentialRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCredentialRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CredentialHashHex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CredentialHashHex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCredentialResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCredentialResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCredentialResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Anchor", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Anchor.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAgreementRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAgreementRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAgreementRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HashHex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HashHex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAgreementResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAgreementResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAgreementResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Agreement", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Agreement.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPersonalAnchorRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPersonalAnchorRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPersonalAnchorRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerDid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OwnerDid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AnchorHashHex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AnchorHashHex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPersonalAnchorResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPersonalAnchorResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPersonalAnchorResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Anchor", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Anchor.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
