// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: phi/identity/identity.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Status of a Phi identity (DID).
type DIDStatus int32

const (
	DID_STATUS_UNSPECIFIED DIDStatus = 0
	DID_STATUS_ACTIVE      DIDStatus = 1
	DID_STATUS_REVOKED     DIDStatus = 2
)

var DIDStatus_name = map[int32]string{
	0: "DID_STATUS_UNSPECIFIED",
	1: "DID_STATUS_ACTIVE",
	2: "DID_STATUS_REVOKED",
}

var DIDStatus_value = map[string]int32{
	"DID_STATUS_UNSPECIFIED": 0,
	"DID_STATUS_ACTIVE":      1,
	"DID_STATUS_REVOKED":     2,
}

func (x DIDStatus) String() string {
	return proto.EnumName(DIDStatus_name, int32(x))
}

func (DIDStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_134696c073a369e5, []int{0}
}

// DIDDocument is the on-chain provable identity record of a human.
// "Verify and forget": only hash/key/signature — never raw or biometric data.
type DIDDocument struct {
	// Unique Phi identity (DID) — primary key
	Did string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	// Controller address (bech32 with phi prefix)
	Controller string `protobuf:"bytes,2,opt,name=controller,proto3" json:"controller,omitempty"`
	// P-256 public key (passkey/Secure Enclave) — raw
	PubKey []byte `protobuf:"bytes,3,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	// Biometric uniqueness marker — hash only (enforces one-human-one-DID)
	UniquenessHash []byte `protobuf:"bytes,4,opt,name=uniqueness_hash,json=uniquenessHash,proto3" json:"uniqueness_hash,omitempty"`
	// Registration time (Unix seconds) — basis for min_identity_age and vote snapshot
	CreatedAt int64 `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Identity health status
	Status DIDStatus `protobuf:"varint,6,opt,name=status,proto3,enum=phi.identity.DIDStatus" json:"status,omitempty"`
}

func (m *DIDDocument) Reset()         { *m = DIDDocument{} }
func (m *DIDDocument) String() string { return proto.CompactTextString(m) }
func (*DIDDocument) ProtoMessage()    {}
func (*DIDDocument) Descriptor() ([]byte, []int) {
	return fileDescriptor_134696c073a369e5, []int{0}
}
func (m *DIDDocument) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DIDDocument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DIDDocument.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DIDDocument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DIDDocument.Merge(m, src)
}
func (m *DIDDocument) XXX_Size() int {
	return m.Size()
}
func (m *DIDDocument) XXX_DiscardUnknown() {
	xxx_messageInfo_DIDDocument.DiscardUnknown(m)
}

var xxx_messageInfo_DIDDocument proto.InternalMessageInfo

func (m *DIDDocument) GetDid() string {
	if m != nil {
		return m.Did
	}
	return ""
}

func (m *DIDDocument) GetController() string {
	if m != nil {
		return m.Controller
	}
	return ""
}

func (m *DIDDocument) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *DIDDocument) GetUniquenessHash() []byte {
	if m != nil {
		return m.UniquenessHash
	}
	return nil
}

func (m *DIDDocument) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *DIDDocument) GetStatus() DIDStatus {
	if m != nil {
		return m.Status
	}
	return DID_STATUS_UNSPECIFIED
}

// TrustedIssuer is a governance-managed identity issuer authorized to attest registrations. Its
// signature over the canonical attestation message is verified on-chain in RegisterIdentity.
type TrustedIssuer struct {
	// did:phi:... of the issuer
	Did string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	// P-256 (SEC1) public key used to verify issuer_sig
	PubKey []byte `protobuf:"bytes,2,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	// active issuers may attest; revoked ones are kept for audit but rejected
	Active bool `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
}

func (m *TrustedIssuer) Reset()         { *m = TrustedIssuer{} }
func (m *TrustedIssuer) String() string { return proto.CompactTextString(m) }
func (*TrustedIssuer) ProtoMessage()    {}
func (*TrustedIssuer) Descriptor() ([]byte, []int) {
	return fileDescriptor_134696c073a369e5, []int{1}
}
func (m *TrustedIssuer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TrustedIssuer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TrustedIssuer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TrustedIssuer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrustedIssuer.Merge(m, src)
}
func (m *TrustedIssuer) XXX_Size() int {
	return m.Size()
}
func (m *TrustedIssuer) XXX_DiscardUnknown() {
	xxx_messageInfo_TrustedIssuer.DiscardUnknown(m)
}

var xxx_messageInfo_TrustedIssuer proto.InternalMessageInfo

func (m *TrustedIssuer) GetDid() string {
	if m != nil {
		return m.Did
	}
	return ""
}

func (m *TrustedIssuer) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *TrustedIssuer) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

// Params are the identity module parameters; changeable only via governance.
type Params struct {
	// Minimum DID age (seconds) to be eligible for public voting
	MinIdentityAgeSeconds int64 `protobuf:"varint,1,opt,name=min_identity_age_seconds,json=minIdentityAgeSeconds,proto3" json:"min_identity_age_seconds,omitempty"`
	// Bootstrap lock threshold for institution onboarding (total registered identities)
	BootstrapThreshold uint64 `protobuf:"varint,2,opt,name=bootstrap_threshold,json=bootstrapThreshold,proto3" json:"bootstrap_threshold,omitempty"`
	// Bootstrap phase — one-way: becomes false forever once the threshold is crossed
	BootstrapPhase bool `protobuf:"varint,3,opt,name=bootstrap_phase,json=bootstrapPhase,proto3" json:"bootstrap_phase,omitempty"`
	// WebAuthn relying-party origin allow-list (anti-phishing). The on-chain passkey verifier accepts an
	// assertion only if its clientDataJSON.origin is in this set. Governed (gov-update) with a genesis
	// default; supports multiple origins (web + native app). Consumed by the WebAuthn ante once the live
	// router lands; WebAuthn stays gated until then.
	WebauthnAllowedOrigins []string `protobuf:"bytes,4,rep,name=webauthn_allowed_origins,json=webauthnAllowedOrigins,proto3" json:"webauthn_allowed_origins,omitempty"`
	// WebAuthn relying-party id (rpId); the verifier checks rpIdHash == SHA256(rpId).
	WebauthnRpId string `protobuf:"bytes,5,opt,name=webauthn_rp_id,json=webauthnRpId,proto3" json:"webauthn_rp_id,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_134696c073a369e5, []int{2}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMinIdentityAgeSeconds() int64 {
	if m != nil {
		return m.MinIdentityAgeSeconds
	}
	return 0
}

func (m *Params) GetBootstrapThreshold() uint64 {
	if m != nil {
		return m.BootstrapThreshold
	}
	return 0
}

func (m *Params) GetBootstrapPhase() bool {
	if m != nil {
		return m.BootstrapPhase
	}
	return false
}

func (m *Params) GetWebauthnAllowedOrigins() []string {
	if m != nil {
		return m.WebauthnAllowedOrigins
	}
	return nil
}

func (m *Params) GetWebauthnRpId() string {
	if m != nil {
		return m.WebauthnRpId
	}
	return ""
}

func init() {
	proto.RegisterEnum("phi.identity.DIDStatus", DIDStatus_name, DIDStatus_value)
	proto.RegisterType((*DIDDocument)(nil), "phi.identity.DIDDocument")
	proto.RegisterType((*TrustedIssuer)(nil), "phi.identity.TrustedIssuer")
	proto.RegisterType((*Params)(nil), "phi.identity.Params")
}

func init() { proto.RegisterFile("phi/identity/identity.proto", fileDescriptor_134696c073a369e5) }

var fileDescriptor_134696c073a369e5 = []byte{
	// 537 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xc1, 0x8e, 0xd2, 0x40,
	0x18, 0xc7, 0x29, 0x60, 0x95, 0x4f, 0x44, 0x76, 0x5c, 0xd8, 0x06, 0x63, 0x43, 0x88, 0x89, 0x64,
	0x0f, 0x90, 0xe8, 0x41, 0xe3, 0x0d, 0xb7, 0x18, 0x9b, 0x4d, 0x5c, 0x32, 0xb0, 0x7b, 0x30, 0x26,
	0x93, 0x81, 0x4e, 0xe8, 0x44, 0x98, 0xa9, 0x33, 0x53, 0x57, 0xde, 0xc0, 0x78, 0xf2, 0xe6, 0x03,
	0xf8, 0x02, 0x3e, 0x86, 0xc7, 0xf5, 0xe6, 0xd1, 0xc0, 0xc1, 0xd7, 0x30, 0xb4, 0x14, 0xd0, 0xec,
	0xa5, 0x99, 0xfe, 0x7e, 0xdf, 0xa4, 0xff, 0xef, 0xeb, 0x07, 0xf7, 0xa3, 0x90, 0x77, 0x79, 0xc0,
	0x84, 0xe1, 0x66, 0xb1, 0x3d, 0x74, 0x22, 0x25, 0x8d, 0x44, 0xe5, 0x28, 0xe4, 0x9d, 0x8c, 0x35,
	0x0e, 0xa7, 0x72, 0x2a, 0x13, 0xd1, 0x5d, 0x9f, 0xd2, 0x9a, 0xc6, 0x01, 0x9d, 0x73, 0x21, 0xbb,
	0xc9, 0x33, 0x45, 0xad, 0x9f, 0x16, 0xdc, 0xf6, 0x7c, 0xcf, 0x93, 0x93, 0x78, 0xce, 0x84, 0x41,
	0x55, 0x28, 0x04, 0x3c, 0x70, 0xac, 0xa6, 0xd5, 0x2e, 0xe1, 0xf5, 0x11, 0xb9, 0x00, 0x13, 0x29,
	0x8c, 0x92, 0xb3, 0x19, 0x53, 0x4e, 0x3e, 0x11, 0x7b, 0x04, 0x1d, 0xc1, 0xcd, 0x28, 0x1e, 0x93,
	0x77, 0x6c, 0xe1, 0x14, 0x9a, 0x56, 0xbb, 0x8c, 0xed, 0x28, 0x1e, 0x9f, 0xb2, 0x05, 0x7a, 0x04,
	0x77, 0x63, 0xc1, 0xdf, 0xc7, 0x4c, 0x30, 0xad, 0x49, 0x48, 0x75, 0xe8, 0x14, 0x93, 0x82, 0xca,
	0x0e, 0xbf, 0xa2, 0x3a, 0x44, 0x0f, 0x00, 0x26, 0x8a, 0x51, 0xc3, 0x02, 0x42, 0x8d, 0x73, 0xa3,
	0x69, 0xb5, 0x0b, 0xb8, 0xb4, 0x21, 0x3d, 0x83, 0xba, 0x60, 0x6b, 0x43, 0x4d, 0xac, 0x1d, 0xbb,
	0x69, 0xb5, 0x2b, 0x8f, 0x8f, 0x3a, 0xfb, 0xad, 0x76, 0x3c, 0xdf, 0x1b, 0x26, 0x1a, 0x6f, 0xca,
	0x5a, 0x18, 0xee, 0x8c, 0x54, 0xac, 0x0d, 0x0b, 0x7c, 0xad, 0x63, 0xa6, 0xae, 0x69, 0x6a, 0x2f,
	0x74, 0xfe, 0x9f, 0xd0, 0x75, 0xb0, 0xe9, 0xc4, 0xf0, 0x0f, 0x2c, 0x69, 0xe6, 0x16, 0xde, 0xbc,
	0xb5, 0xbe, 0xe6, 0xc1, 0x1e, 0x50, 0x45, 0xe7, 0x1a, 0x3d, 0x05, 0x67, 0xce, 0x05, 0xc9, 0x02,
	0x10, 0x3a, 0x65, 0x44, 0xb3, 0x89, 0x14, 0x81, 0x4e, 0x3e, 0x51, 0xc0, 0xb5, 0x39, 0x17, 0xfe,
	0x46, 0xf7, 0xa6, 0x6c, 0x98, 0x4a, 0xd4, 0x85, 0x7b, 0x63, 0x29, 0x8d, 0x36, 0x8a, 0x46, 0xc4,
	0x84, 0x8a, 0xe9, 0x50, 0xce, 0x82, 0x24, 0x40, 0x11, 0xa3, 0xad, 0x1a, 0x65, 0x66, 0x3d, 0xc1,
	0xdd, 0x85, 0x28, 0xa4, 0x3a, 0x4b, 0x55, 0xd9, 0xe2, 0xc1, 0x9a, 0xa2, 0x67, 0xe0, 0x5c, 0xb2,
	0x31, 0x8d, 0x4d, 0x28, 0x08, 0x9d, 0xcd, 0xe4, 0x25, 0x0b, 0x88, 0x54, 0x7c, 0xca, 0x85, 0x76,
	0x8a, 0xcd, 0x42, 0xbb, 0x84, 0xeb, 0x99, 0xef, 0xa5, 0xfa, 0x2c, 0xb5, 0xe8, 0x21, 0x54, 0xb6,
	0x37, 0x55, 0x44, 0x78, 0x90, 0xcc, 0xbf, 0x84, 0xcb, 0x19, 0xc5, 0x91, 0x1f, 0x3c, 0x6f, 0x7c,
	0xfe, 0xf3, 0xfd, 0xb8, 0xb6, 0x5e, 0xbf, 0x8f, 0xbb, 0x05, 0x4c, 0xc7, 0x71, 0xfc, 0x16, 0x4a,
	0xdb, 0x5f, 0x80, 0x1a, 0x50, 0xf7, 0x7c, 0x8f, 0x0c, 0x47, 0xbd, 0xd1, 0xf9, 0x90, 0x9c, 0xbf,
	0x1e, 0x0e, 0xfa, 0x27, 0xfe, 0x4b, 0xbf, 0xef, 0x55, 0x73, 0xa8, 0x06, 0x07, 0x7b, 0xae, 0x77,
	0x32, 0xf2, 0x2f, 0xfa, 0x55, 0x0b, 0xd5, 0x01, 0xed, 0x61, 0xdc, 0xbf, 0x38, 0x3b, 0xed, 0x7b,
	0xd5, 0x7c, 0xa3, 0xf8, 0xe9, 0x9b, 0x9b, 0x7b, 0xd1, 0xf9, 0xb1, 0x74, 0xad, 0xab, 0xa5, 0x6b,
	0xfd, 0x5e, 0xba, 0xd6, 0x97, 0x95, 0x9b, 0xbb, 0x5a, 0xb9, 0xb9, 0x5f, 0x2b, 0x37, 0xf7, 0xe6,
	0xf0, 0xbf, 0x38, 0x66, 0x11, 0x31, 0x3d, 0xb6, 0x93, 0xb5, 0x7e, 0xf2, 0x37, 0x00, 0x00, 0xff,
	0xff, 0x1d, 0x59, 0x98, 0x25, 0x2c, 0x03, 0x00, 0x00,
}

func (m *DIDDocument) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DIDDocument) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DIDDocument) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintIdentity(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x30
	}
	if m.CreatedAt != 0 {
		i = encodeVarintIdentity(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x28
	}
	if len(m.UniquenessHash) > 0 {
		i -= len(m.UniquenessHash)
		copy(dAtA[i:], m.UniquenessHash)
		i = encodeVarintIdentity(dAtA, i, uint64(len(m.UniquenessHash)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.PubKey) > 0 {
		i -= len(m.PubKey)
		copy(dAtA[i:], m.PubKey)
		i = encodeVarintIdentity(dAtA, i, uint64(len(m.PubKey)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Controller) > 0 {
		i -= len(m.Controller)
		copy(dAtA[i:], m.Controller)
		i = encodeVarintIdentity(dAtA, i, uint64(len(m.Controller)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Did) > 0 {
		i -= len(m.Did)
		copy(dAtA[i:], m.Did)
		i = encodeVarintIdentity(dAtA, i, uint64(len(m.Did)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TrustedIssuer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TrustedIssuer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TrustedIssuer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Active {
		i--
		if m.Active {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.PubKey) > 0 {
		i -= len(m.PubKey)
		copy(dAtA[i:], m.PubKey)
		i = encodeVarintIdentity(dAtA, i, uint64(len(m.PubKey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Did) > 0 {
		i -= len(m.Did)
		copy(dAtA[i:], m.Did)
		i = encodeVarintIdentity(dAtA, i, uint64(len(m.Did)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.WebauthnRpId) > 0 {
		i -= len(m.WebauthnRpId)
		copy(dAtA[i:], m.WebauthnRpId)
		i = encodeVarintIdentity(dAtA, i, uint64(len(m.WebauthnRpId)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.WebauthnAllowedOrigins) > 0 {
		for iNdEx := len(m.WebauthnAllowedOrigins) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.WebauthnAllowedOrigins[iNdEx])
			copy(dAtA[i:], m.WebauthnAllowedOrigins[iNdEx])
			i = encodeVarintIdentity(dAtA, i, uint64(len(m.WebauthnAllowedOrigins[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if m.BootstrapPhase {
		i--
		if m.BootstrapPhase {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.BootstrapThreshold != 0 {
		i = encodeVarintIdentity(dAtA, i, uint64(m.BootstrapThreshold))
		i--
		dAtA[i] = 0x10
	}
	if m.MinIdentityAgeSeconds != 0 {
		i = encodeVarintIdentity(dAtA, i, uint64(m.MinIdentityAgeSeconds))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintIdentity(dAtA []byte, offset int, v uint64) int {
	offset -= sovIdentity(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DIDDocument) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Did)
	if l > 0 {
		n += 1 + l + sovIdentity(uint64(l))
	}
	l = len(m.Controller)
	if l > 0 {
		n += 1 + l + sovIdentity(uint64(l))
	}
	l = len(m.PubKey)
	if l > 0 {
		n += 1 + l + sovIdentity(uint64(l))
	}
	l = len(m.UniquenessHash)
	if l > 0 {
		n += 1 + l + sovIdentity(uint64(l))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovIdentity(uint64(m.CreatedAt))
	}
	if m.Status != 0 {
		n += 1 + sovIdentity(uint64(m.Status))
	}
	return n
}

func (m *TrustedIssuer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Did)
	if l > 0 {
		n += 1 + l + sovIdentity(uint64(l))
	}
	l = len(m.PubKey)
	if l > 0 {
		n += 1 + l + sovIdentity(uint64(l))
	}
	if m.Active {
		n += 2
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MinIdentityAgeSeconds != 0 {
		n += 1 + sovIdentity(uint64(m.MinIdentityAgeSeconds))
	}
	if m.BootstrapThreshold != 0 {
		n += 1 + sovIdentity(uint64(m.BootstrapThreshold))
	}
	if m.BootstrapPhase {
		n += 2
	}
	if len(m.WebauthnAllowedOrigins) > 0 {
		for _, s := range m.WebauthnAllowedOrigins {
			l = len(s)
			n += 1 + l + sovIdentity(uint64(l))
		}
	}
	l = len(m.WebauthnRpId)
	if l > 0 {
		n += 1 + l + sovIdentity(uint64(l))
	}
	return n
}

func sovIdentity(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozIdentity(x uint64) (n int) {
	return sovIdentity(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DIDDocument) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIdentity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DIDDocument: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DIDDocument: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Did", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIdentity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIdentity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Did = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Controller", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIdentity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIdentity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Controller = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthIdentity
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthIdentity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PubKey = append(m.PubKey[:0], dAtA[iNdEx:postIndex]...)
			if m.PubKey == nil {
				m.PubKey = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UniquenessHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthIdentity
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthIdentity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UniquenessHash = append(m.UniquenessHash[:0], dAtA[iNdEx:postIndex]...)
			if m.UniquenessHash == nil {
				m.UniquenessHash = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= DIDStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipIdentity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIdentity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TrustedIssuer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIdentity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TrustedIssuer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TrustedIssuer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Did", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIdentity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIdentity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Did = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthIdentity
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthIdentity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PubKey = append(m.PubKey[:0], dAtA[iNdEx:postIndex]...)
			if m.PubKey == nil {
				m.PubKey = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Active", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Active = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipIdentity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIdentity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIdentity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinIdentityAgeSeconds", wireType)
			}
			m.MinIdentityAgeSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinIdentityAgeSeconds |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BootstrapThreshold", wireType)
			}
			m.BootstrapThreshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BootstrapThreshold |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BootstrapPhase", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.BootstrapPhase = bool(v != 0)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WebauthnAllowedOrigins", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIdentity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIdentity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WebauthnAllowedOrigins = append(m.WebauthnAllowedOrigins, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WebauthnRpId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIdentity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIdentity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WebauthnRpId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIdentity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIdentity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipIdentity(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowIdentity
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthIdentity
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupIdentity
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthIdentity
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthIdentity        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowIdentity          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupIdentity = fmt.Errorf("proto: unexpected end of group")
)
