// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: phi/identity/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9053d599a41f938, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

type QueryParamsResponse struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9053d599a41f938, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryIdentityRequest struct {
	Did string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
}

func (m *QueryIdentityRequest) Reset()         { *m = QueryIdentityRequest{} }
func (m *QueryIdentityRequest) String() string { return proto.CompactTextString(m) }
func (*QueryIdentityRequest) ProtoMessage()    {}
func (*QueryIdentityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9053d599a41f938, []int{2}
}
func (m *QueryIdentityRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIdentityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIdentityRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIdentityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIdentityRequest.Merge(m, src)
}
func (m *QueryIdentityRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryIdentityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIdentityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIdentityRequest proto.InternalMessageInfo

func (m *QueryIdentityRequest) GetDid() string {
	if m != nil {
		return m.Did
	}
	return ""
}

type QueryIdentityResponse struct {
	Identity DIDDocument `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity"`
}

func (m *QueryIdentityResponse) Reset()         { *m = QueryIdentityResponse{} }
func (m *QueryIdentityResponse) String() string { return proto.CompactTextString(m) }
func (*QueryIdentityResponse) ProtoMessage()    {}
func (*QueryIdentityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9053d599a41f938, []int{3}
}
func (m *QueryIdentityResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIdentityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIdentityResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIdentityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIdentityResponse.Merge(m, src)
}
func (m *QueryIdentityResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryIdentityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIdentityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIdentityResponse proto.InternalMessageInfo

func (m *QueryIdentityResponse) GetIdentity() DIDDocument {
	if m != nil {
		return m.Identity
	}
	return DIDDocument{}
}

type QueryIdentityCountRequest struct {
}

func (m *QueryIdentityCountRequest) Reset()         { *m = QueryIdentityCountRequest{} }
func (m *QueryIdentityCountRequest) String() string { return proto.CompactTextString(m) }
func (*QueryIdentityCountRequest) ProtoMessage()    {}
func (*QueryIdentityCountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9053d599a41f938, []int{4}
}
func (m *QueryIdentityCountRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIdentityCountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIdentityCountRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIdentityCountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIdentityCountRequest.Merge(m, src)
}
func (m *QueryIdentityCountRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryIdentityCountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIdentityCountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIdentityCountRequest proto.InternalMessageInfo

type QueryIdentityCountResponse struct {
	Count uint64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (m *QueryIdentityCountResponse) Reset()         { *m = QueryIdentityCountResponse{} }
func (m *QueryIdentityCountResponse) String() string { return proto.CompactTextString(m) }
func (*QueryIdentityCountResponse) ProtoMessage()    {}
func (*QueryIdentityCountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9053d599a41f938, []int{5}
}
func (m *QueryIdentityCountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIdentityCountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIdentityCountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIdentityCountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIdentityCountResponse.Merge(m, src)
}
func (m *QueryIdentityCountResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryIdentityCountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIdentityCountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIdentityCountResponse proto.InternalMessageInfo

func (m *QueryIdentityCountResponse) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type QueryGuardiansRequest struct {
	Did string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
}

func (m *QueryGuardiansRequest) Reset()         { *m = QueryGuardiansRequest{} }
func (m *QueryGuardiansRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGuardiansRequest) ProtoMessage()    {}
func (*QueryGuardiansRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9053d599a41f938, []int{6}
}
func (m *QueryGuardiansRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGuardiansRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGuardiansRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGuardiansRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGuardiansRequest.Merge(m, src)
}
func (m *QueryGuardiansRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGuardiansRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGuardiansRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGuardiansRequest proto.InternalMessageInfo

func (m *QueryGuardiansRequest) GetDid() string {
	if m != nil {
		return m.Did
	}
	return ""
}

type QueryGuardiansResponse struct {
	// How many guardians are configured (the commitments themselves are not exposed)
	CommitmentCount uint32 `protobuf:"varint,1,opt,name=commitment_count,json=commitmentCount,proto3" json:"commitment_count,omitempty"`
	// Approvals required to recover
	Threshold uint32 `protobuf:"varint,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
	// Last update time (Unix seconds)
	UpdatedAt int64 `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (m *QueryGuardiansResponse) Reset()         { *m = QueryGuardiansResponse{} }
func (m *QueryGuardiansResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGuardiansResponse) ProtoMessage()    {}
func (*QueryGuardiansResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9053d599a41f938, []int{7}
}
func (m *QueryGuardiansResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGuardiansResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGuardiansResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGuardiansResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGuardiansResponse.Merge(m, src)
}
func (m *QueryGuardiansResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGuardiansResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGuardiansResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGuardiansResponse proto.InternalMessageInfo

func (m *QueryGuardiansResponse) GetCommitmentCount() uint32 {
	if m != nil {
		return m.CommitmentCount
	}
	return 0
}

func (m *QueryGuardiansResponse) GetThreshold() uint32 {
	if m != nil {
		return m.Threshold
	}
	return 0
}

func (m *QueryGuardiansResponse) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type QueryRecoveryRequestRequest struct {
	RecoveryId []byte `protobuf:"bytes,1,opt,name=recovery_id,json=recoveryId,proto3" json:"recovery_id,omitempty"`
}

func (m *QueryRecoveryRequestRequest) Reset()         { *m = QueryRecoveryRequestRequest{} }
func (m *QueryRecoveryRequestRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRecoveryRequestRequest) ProtoMessage()    {}
func (*QueryRecoveryRequestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9053d599a41f938, []int{8}
}
func (m *QueryRecoveryRequestRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRecoveryRequestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRecoveryRequestRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRecoveryRequestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRecoveryRequestRequest.Merge(m, src)
}
func (m *QueryRecoveryRequestRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRecoveryRequestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRecoveryRequestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRecoveryRequestRequest proto.InternalMessageInfo

func (m *QueryRecoveryRequestRequest) GetRecoveryId() []byte {
	if m != nil {
		return m.RecoveryId
	}
	return nil
}

type QueryRecoveryRequestResponse struct {
	Request RecoveryRequest `protobuf:"bytes,1,opt,name=request,proto3" json:"request"`
}

func (m *QueryRecoveryRequestResponse) Reset()         { *m = QueryRecoveryRequestResponse{} }
func (m *QueryRecoveryRequestResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRecoveryRequestResponse) ProtoMessage()    {}
func (*QueryRecoveryRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9053d599a41f938, []int{9}
}
func (m *QueryRecoveryRequestResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRecoveryRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRecoveryRequestResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRecoveryRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRecoveryRequestResponse.Merge(m, src)
}
func (m *QueryRecoveryRequestResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRecoveryRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRecoveryRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRecoveryRequestResponse proto.InternalMessageInfo

func (m *QueryRecoveryRequestResponse) GetRequest() RecoveryRequest {
	if m != nil {
		return m.Request
	}
	return RecoveryRequest{}
}

type QueryRecoveryRequestsByDIDRequest struct {
	Did string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
}

func (m *QueryRecoveryRequestsByDIDRequest) Reset()         { *m = QueryRecoveryRequestsByDIDRequest{} }
func (m *QueryRecoveryRequestsByDIDRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRecoveryRequestsByDIDRequest) ProtoMessage()    {}
func (*QueryRecoveryRequestsByDIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9053d599a41f938, []int{10}
}
func (m *QueryRecoveryRequestsByDIDRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRecoveryRequestsByDIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRecoveryRequestsByDIDRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRecoveryRequestsByDIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRecoveryRequestsByDIDRequest.Merge(m, src)
}
func (m *QueryRecoveryRequestsByDIDRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRecoveryRequestsByDIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRecoveryRequestsByDIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRecoveryRequestsByDIDRequest proto.InternalMessageInfo

func (m *QueryRecoveryRequestsByDIDRequest) GetDid() string {
	if m != nil {
		return m.Did
	}
	return ""
}

type QueryRecoveryRequestsByDIDResponse struct {
	Requests []RecoveryRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests"`
}

func (m *QueryRecoveryRequestsByDIDResponse) Reset()         { *m = QueryRecoveryRequestsByDIDResponse{} }
func (m *QueryRecoveryRequestsByDIDResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRecoveryRequestsByDIDResponse) ProtoMessage()    {}
func (*QueryRecoveryRequestsByDIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9053d599a41f938, []int{11}
}
func (m *QueryRecoveryRequestsByDIDResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRecoveryRequestsByDIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRecoveryRequestsByDIDResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRecoveryRequestsByDIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRecoveryRequestsByDIDResponse.Merge(m, src)
}
func (m *QueryRecoveryRequestsByDIDResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRecoveryRequestsByDIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRecoveryRequestsByDIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRecoveryRequestsByDIDResponse proto.InternalMessageInfo

func (m *QueryRecoveryRequestsByDIDResponse) GetRequests() []RecoveryRequest {
	if m != nil {
		return m.Requests
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "phi.identity.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "phi.identity.QueryParamsResponse")
	proto.RegisterType((*QueryIdentityRequest)(nil), "phi.identity.QueryIdentityRequest")
	proto.RegisterType((*QueryIdentityResponse)(nil), "phi.identity.QueryIdentityResponse")
	proto.RegisterType((*QueryIdentityCountRequest)(nil), "phi.identity.QueryIdentityCountRequest")
	proto.RegisterType((*QueryIdentityCountResponse)(nil), "phi.identity.QueryIdentityCountResponse")
	proto.RegisterType((*QueryGuardiansRequest)(nil), "phi.identity.QueryGuardiansRequest")
	proto.RegisterType((*QueryGuardiansResponse)(nil), "phi.identity.QueryGuardiansResponse")
	proto.RegisterType((*QueryRecoveryRequestRequest)(nil), "phi.identity.QueryRecoveryRequestRequest")
	proto.RegisterType((*QueryRecoveryRequestResponse)(nil), "phi.identity.QueryRecoveryRequestResponse")
	proto.RegisterType((*QueryRecoveryRequestsByDIDRequest)(nil), "phi.identity.QueryRecoveryRequestsByDIDRequest")
	proto.RegisterType((*QueryRecoveryRequestsByDIDResponse)(nil), "phi.identity.QueryRecoveryRequestsByDIDResponse")
}

func init() { proto.RegisterFile("phi/identity/query.proto", fileDescriptor_d9053d599a41f938) }

var fileDescriptor_d9053d599a41f938 = []byte{
	// 697 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0x5f, 0x4f, 0xd3, 0x5e,
	0x18, 0x5e, 0x19, 0xec, 0xc7, 0x5e, 0x20, 0x90, 0xc3, 0x20, 0xa3, 0x1b, 0x65, 0x94, 0x3f, 0xbf,
	0xa1, 0xb2, 0x9a, 0x19, 0xaf, 0x8c, 0x1a, 0x71, 0x89, 0xec, 0x0e, 0x1b, 0xaf, 0x4c, 0x0c, 0x29,
	0xeb, 0xc9, 0x76, 0x22, 0xeb, 0x29, 0xed, 0xa9, 0x71, 0x21, 0x44, 0xe3, 0x27, 0x30, 0x31, 0xf1,
	0x2b, 0xf8, 0x05, 0xfc, 0x10, 0x5c, 0x92, 0x78, 0xe3, 0x95, 0x31, 0xe0, 0x07, 0x31, 0x3d, 0x7d,
	0xcb, 0x68, 0x2d, 0x83, 0xab, 0x75, 0xef, 0xfb, 0xbc, 0xcf, 0xf3, 0x9c, 0x9e, 0xf7, 0xd9, 0xa0,
	0xec, 0xf6, 0x98, 0xc1, 0x6c, 0xea, 0x08, 0x26, 0x06, 0xc6, 0x51, 0x40, 0xbd, 0x41, 0xc3, 0xf5,
	0xb8, 0xe0, 0x64, 0xda, 0xed, 0xb1, 0x46, 0xdc, 0x51, 0x4b, 0x5d, 0xde, 0xe5, 0xb2, 0x61, 0x84,
	0x4f, 0x11, 0x46, 0xad, 0x76, 0x39, 0xef, 0x1e, 0x52, 0xc3, 0x72, 0x99, 0x61, 0x39, 0x0e, 0x17,
	0x96, 0x60, 0xdc, 0xf1, 0xb1, 0x5b, 0x49, 0x70, 0xc7, 0x0f, 0x51, 0x53, 0x2f, 0x01, 0x79, 0x19,
	0xaa, 0xed, 0x59, 0x9e, 0xd5, 0xf7, 0x4d, 0x7a, 0x14, 0x50, 0x5f, 0xe8, 0x6d, 0x98, 0x4f, 0x54,
	0x7d, 0x97, 0x3b, 0x3e, 0x25, 0x4d, 0x28, 0xb8, 0xb2, 0x52, 0x56, 0x6a, 0x4a, 0x7d, 0xaa, 0x59,
	0x6a, 0x5c, 0x35, 0xd7, 0x88, 0xd0, 0x3b, 0xe3, 0xa7, 0xbf, 0x56, 0x72, 0x26, 0x22, 0xf5, 0x3a,
	0x94, 0x24, 0x55, 0x1b, 0x51, 0x28, 0x41, 0xe6, 0x20, 0x6f, 0x33, 0x5b, 0x12, 0x15, 0xcd, 0xf0,
	0x51, 0x7f, 0x05, 0x0b, 0x29, 0x24, 0xca, 0x3e, 0x82, 0xc9, 0x58, 0x03, 0x85, 0x97, 0x92, 0xc2,
	0xad, 0x76, 0xab, 0xc5, 0x3b, 0x41, 0x9f, 0x3a, 0x02, 0xd5, 0x2f, 0x07, 0xf4, 0x0a, 0x2c, 0x25,
	0x58, 0x9f, 0xf3, 0xc0, 0x11, 0xf1, 0x39, 0x9b, 0xa0, 0x66, 0x35, 0x51, 0xb7, 0x04, 0x13, 0x9d,
	0xb0, 0x20, 0x45, 0xc7, 0xcd, 0xe8, 0x8b, 0xbe, 0x85, 0x36, 0x5f, 0x04, 0x96, 0x67, 0x33, 0xcb,
	0xf1, 0xaf, 0x3f, 0xd1, 0x47, 0x05, 0x16, 0xd3, 0x58, 0xe4, 0xde, 0x82, 0xb9, 0x0e, 0xef, 0xf7,
	0x99, 0x08, 0x4d, 0xef, 0x0f, 0x65, 0x66, 0xcc, 0xd9, 0x61, 0x5d, 0xda, 0x21, 0x55, 0x28, 0x8a,
	0x9e, 0x47, 0xfd, 0x1e, 0x3f, 0xb4, 0xcb, 0x63, 0x12, 0x33, 0x2c, 0x90, 0x65, 0x80, 0xc0, 0xb5,
	0x2d, 0x41, 0xed, 0x7d, 0x4b, 0x94, 0xf3, 0x35, 0xa5, 0x9e, 0x37, 0x8b, 0x58, 0x79, 0x26, 0xf4,
	0x27, 0x50, 0x91, 0x0e, 0x4c, 0xda, 0xe1, 0xef, 0xe4, 0xa7, 0x34, 0x1b, 0x7b, 0x5e, 0x81, 0x29,
	0x0f, 0x3b, 0xfb, 0xe8, 0x7d, 0xda, 0x84, 0xb8, 0xd4, 0xb6, 0xf5, 0x37, 0x50, 0xcd, 0x9e, 0xc7,
	0x73, 0x3c, 0x86, 0xff, 0xbc, 0xa8, 0x84, 0x57, 0xb3, 0x9c, 0xbc, 0x9a, 0xd4, 0x1c, 0x5e, 0x4f,
	0x3c, 0xa3, 0x3f, 0x84, 0xd5, 0x2c, 0x7a, 0x7f, 0x67, 0xd0, 0x6a, 0xb7, 0xae, 0x7f, 0xb1, 0x14,
	0xf4, 0x51, 0x63, 0xe8, 0xed, 0x29, 0x4c, 0xa2, 0x4e, 0xb8, 0xb0, 0xf9, 0xdb, 0x9a, 0xbb, 0x1c,
	0x6a, 0x7e, 0x2f, 0xc0, 0x84, 0xd4, 0x21, 0x6f, 0xa1, 0x10, 0x6d, 0x37, 0xa9, 0x25, 0x29, 0xfe,
	0x0d, 0x8f, 0xba, 0x3a, 0x02, 0x11, 0x39, 0xd3, 0xab, 0x9f, 0x7e, 0xfc, 0xf9, 0x32, 0xb6, 0x48,
	0x4a, 0x46, 0x22, 0x9b, 0x51, 0x64, 0xc8, 0x31, 0x4c, 0xc6, 0x0b, 0x49, 0xf4, 0x0c, 0xb2, 0x54,
	0x94, 0xd4, 0xb5, 0x91, 0x18, 0x94, 0xdc, 0x94, 0x92, 0x35, 0xa2, 0x19, 0x59, 0x3f, 0x07, 0x8c,
	0xfa, 0xc6, 0xb1, 0xcd, 0xec, 0x13, 0xf2, 0x01, 0x66, 0x12, 0x69, 0x20, 0xff, 0x8f, 0x60, 0xbf,
	0x1a, 0x26, 0xb5, 0x7e, 0x33, 0x10, 0xbd, 0x54, 0xa4, 0x97, 0x05, 0x32, 0x9f, 0xf4, 0x22, 0x53,
	0x40, 0x4e, 0xa0, 0x78, 0x19, 0x17, 0x92, 0x75, 0xb4, 0x74, 0xf0, 0xd4, 0xf5, 0xd1, 0x20, 0x14,
	0xdd, 0x90, 0xa2, 0x2b, 0x64, 0x39, 0x29, 0xda, 0x8d, 0x81, 0x78, 0xfe, 0xaf, 0x0a, 0xcc, 0xa6,
	0xf6, 0x82, 0x6c, 0x65, 0x08, 0x64, 0x07, 0x4a, 0xbd, 0x73, 0x1b, 0x28, 0x3a, 0xba, 0x27, 0x1d,
	0x6d, 0x92, 0xf5, 0xa4, 0xa3, 0x38, 0x7d, 0xc6, 0xf1, 0x95, 0x68, 0x9e, 0x90, 0x6f, 0x0a, 0x2c,
	0x64, 0xee, 0x3b, 0x31, 0x6e, 0xd6, 0x4c, 0x04, 0x4a, 0xbd, 0x7f, 0xfb, 0x01, 0xb4, 0x7a, 0x57,
	0x5a, 0xdd, 0x20, 0x6b, 0xd7, 0x58, 0x3d, 0x18, 0x6c, 0xdb, 0xcc, 0x8e, 0x5e, 0xe1, 0xce, 0xee,
	0xe9, 0xb9, 0xa6, 0x9c, 0x9d, 0x6b, 0xca, 0xef, 0x73, 0x4d, 0xf9, 0x7c, 0xa1, 0xe5, 0xce, 0x2e,
	0xb4, 0xdc, 0xcf, 0x0b, 0x2d, 0xf7, 0xba, 0xd1, 0x65, 0xa2, 0x17, 0x1c, 0x34, 0x3a, 0xbc, 0x6f,
	0xec, 0x71, 0x4f, 0x6c, 0xef, 0xed, 0xb6, 0x43, 0xc6, 0xed, 0x4e, 0xcf, 0x62, 0x8e, 0xf1, 0x7e,
	0xc8, 0x2c, 0x06, 0x2e, 0xf5, 0x0f, 0x0a, 0xf2, 0x4f, 0xea, 0xc1, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x07, 0x22, 0x4f, 0x3e, 0x1f, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Params returns the current module parameters.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Identity returns a DIDDocument by DID.
	Identity(ctx context.Context, in *QueryIdentityRequest, opts ...grpc.CallOption) (*QueryIdentityResponse, error)
	// IdentityCount returns the total count of registered identities (basis for the bootstrap lock).
	IdentityCount(ctx context.Context, in *QueryIdentityCountRequest, opts ...grpc.CallOption) (*QueryIdentityCountResponse, error)
	// Guardians returns a DID's guardian configuration SHAPE only — how many guardians and the
	// threshold. It deliberately does NOT return the commitments or any guardian identity: the whole
	// point of the commitment scheme is that the guardian graph is not readable.
	Guardians(ctx context.Context, in *QueryGuardiansRequest, opts ...grpc.CallOption) (*QueryGuardiansResponse, error)
	// RecoveryRequest returns one recovery request by id.
	RecoveryRequest(ctx context.Context, in *QueryRecoveryRequestRequest, opts ...grpc.CallOption) (*QueryRecoveryRequestResponse, error)
	// RecoveryRequestsByDID returns every recovery request recorded for a DID (open and terminal).
	RecoveryRequestsByDID(ctx context.Context, in *QueryRecoveryRequestsByDIDRequest, opts ...grpc.CallOption) (*QueryRecoveryRequestsByDIDResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/phi.identity.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Identity(ctx context.Context, in *QueryIdentityRequest, opts ...grpc.CallOption) (*QueryIdentityResponse, error) {
	out := new(QueryIdentityResponse)
	err := c.cc.Invoke(ctx, "/phi.identity.Query/Identity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) IdentityCount(ctx context.Context, in *QueryIdentityCountRequest, opts ...grpc.CallOption) (*QueryIdentityCountResponse, error) {
	out := new(QueryIdentityCountResponse)
	err := c.cc.Invoke(ctx, "/phi.identity.Query/IdentityCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Guardians(ctx context.Context, in *QueryGuardiansRequest, opts ...grpc.CallOption) (*QueryGuardiansResponse, error) {
	out := new(QueryGuardiansResponse)
	err := c.cc.Invoke(ctx, "/phi.identity.Query/Guardians", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RecoveryRequest(ctx context.Context, in *QueryRecoveryRequestRequest, opts ...grpc.CallOption) (*QueryRecoveryRequestResponse, error) {
	out := new(QueryRecoveryRequestResponse)
	err := c.cc.Invoke(ctx, "/phi.identity.Query/RecoveryRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RecoveryRequestsByDID(ctx context.Context, in *QueryRecoveryRequestsByDIDRequest, opts ...grpc.CallOption) (*QueryRecoveryRequestsByDIDResponse, error) {
	out := new(QueryRecoveryRequestsByDIDResponse)
	err := c.cc.Invoke(ctx, "/phi.identity.Query/RecoveryRequestsByDID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Params returns the current module parameters.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Identity returns a DIDDocument by DID.
	Identity(context.Context, *QueryIdentityRequest) (*QueryIdentityResponse, error)
	// IdentityCount returns the total count of registered identities (basis for the bootstrap lock).
	IdentityCount(context.Context, *QueryIdentityCountRequest) (*QueryIdentityCountResponse, error)
	// Guardians returns a DID's guardian configuration SHAPE only — how many guardians and the
	// threshold. It deliberately does NOT return the commitments or any guardian identity: the whole
	// point of the commitment scheme is that the guardian graph is not readable.
	Guardians(context.Context, *QueryGuardiansRequest) (*QueryGuardiansResponse, error)
	// RecoveryRequest returns one recovery request by id.
	RecoveryRequest(context.Context, *QueryRecoveryRequestRequest) (*QueryRecoveryRequestResponse, error)
	// RecoveryRequestsByDID returns every recovery request recorded for a DID (open and terminal).
	RecoveryRequestsByDID(context.Context, *QueryRecoveryRequestsByDIDRequest) (*QueryRecoveryRequestsByDIDResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Identity(ctx context.Context, req *QueryIdentityRequest) (*QueryIdentityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Identity not implemented")
}
func (*UnimplementedQueryServer) IdentityCount(ctx context.Context, req *QueryIdentityCountRequest) (*QueryIdentityCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IdentityCount not implemented")
}
func (*UnimplementedQueryServer) Guardians(ctx context.Context, req *QueryGuardiansRequest) (*QueryGuardiansResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Guardians not implemented")
}
func (*UnimplementedQueryServer) RecoveryRequest(ctx context.Context, req *QueryRecoveryRequestRequest) (*QueryRecoveryRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecoveryRequest not implemented")
}
func (*UnimplementedQueryServer) RecoveryRequestsByDID(ctx context.Context, req *QueryRecoveryRequestsByDIDRequest) (*QueryRecoveryRequestsByDIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecoveryRequestsByDID not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phi.identity.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Identity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Identity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phi.identity.Query/Identity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Identity(ctx, req.(*QueryIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_IdentityCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryIdentityCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).IdentityCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phi.identity.Query/IdentityCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).IdentityCount(ctx, req.(*QueryIdentityCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Guardians_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGuardiansRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Guardians(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phi.identity.Query/Guardians",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Guardians(ctx, req.(*QueryGuardiansRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RecoveryRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRecoveryRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RecoveryRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phi.identity.Query/RecoveryRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RecoveryRequest(ctx, req.(*QueryRecoveryRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RecoveryRequestsByDID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRecoveryRequestsByDIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RecoveryRequestsByDID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phi.identity.Query/RecoveryRequestsByDID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RecoveryRequestsByDID(ctx, req.(*QueryRecoveryRequestsByDIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "phi.identity.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Identity",
			Handler:    _Query_Identity_Handler,
		},
		{
			MethodName: "IdentityCount",
			Handler:    _Query_IdentityCount_Handler,
		},
		{
			MethodName: "Guardians",
			Handler:    _Query_Guardians_Handler,
		},
		{
			MethodName: "RecoveryRequest",
			Handler:    _Query_RecoveryRequest_Handler,
		},
		{
			MethodName: "RecoveryRequestsByDID",
			Handler:    _Query_RecoveryRequestsByDID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "phi/identity/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryIdentityRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIdentityRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIdentityRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Did) > 0 {
		i -= len(m.Did)
		copy(dAtA[i:], m.Did)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Did)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryIdentityResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIdentityResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIdentityResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Identity.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryIdentityCountRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIdentityCountRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIdentityCountRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryIdentityCountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIdentityCountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIdentityCountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Count != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGuardiansRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGuardiansRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGuardiansRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Did) > 0 {
		i -= len(m.Did)
		copy(dAtA[i:], m.Did)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Did)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGuardiansResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGuardiansResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGuardiansResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UpdatedAt != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.UpdatedAt))
		i--
		dAtA[i] = 0x18
	}
	if m.Threshold != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Threshold))
		i--
		dAtA[i] = 0x10
	}
	if m.CommitmentCount != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.CommitmentCount))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryRecoveryRequestRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRecoveryRequestRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRecoveryRequestRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RecoveryId) > 0 {
		i -= len(m.RecoveryId)
		copy(dAtA[i:], m.RecoveryId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.RecoveryId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRecoveryRequestResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRecoveryRequestResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRecoveryRequestResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Request.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryRecoveryRequestsByDIDRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRecoveryRequestsByDIDRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRecoveryRequestsByDIDRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Did) > 0 {
		i -= len(m.Did)
		copy(dAtA[i:], m.Did)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Did)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRecoveryRequestsByDIDResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRecoveryRequestsByDIDResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRecoveryRequestsByDIDResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Requests) > 0 {
		for iNdEx := len(m.Requests) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Requests[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryIdentityRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Did)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryIdentityResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Identity.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryIdentityCountRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryIdentityCountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Count != 0 {
		n += 1 + sovQuery(uint64(m.Count))
	}
	return n
}

func (m *QueryGuardiansRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Did)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGuardiansResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CommitmentCount != 0 {
		n += 1 + sovQuery(uint64(m.CommitmentCount))
	}
	if m.Threshold != 0 {
		n += 1 + sovQuery(uint64(m.Threshold))
	}
	if m.UpdatedAt != 0 {
		n += 1 + sovQuery(uint64(m.UpdatedAt))
	}
	return n
}

func (m *QueryRecoveryRequestRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RecoveryId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRecoveryRequestResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Request.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryRecoveryRequestsByDIDRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Did)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRecoveryRequestsByDIDResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Requests) > 0 {
		for _, e := range m.Requests {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryIdentityRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIdentityRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIdentityRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Did", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Did = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryIdentityResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIdentityResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIdentityResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Identity", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Identity.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryIdentityCountRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIdentityCountRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIdentityCountRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryIdentityCountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIdentityCountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIdentityCountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGuardiansRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGuardiansRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGuardiansRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Did", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Did = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGuardiansResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGuardiansResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGuardiansResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitmentCount", wireType)
			}
			m.CommitmentCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CommitmentCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Threshold", wireType)
			}
			m.Threshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Threshold |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			m.UpdatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRecoveryRequestRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRecoveryRequestRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRecoveryRequestRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecoveryId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RecoveryId = append(m.RecoveryId[:0], dAtA[iNdEx:postIndex]...)
			if m.RecoveryId == nil {
				m.RecoveryId = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRecoveryRequestResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRecoveryRequestResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRecoveryRequestResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Request", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Request.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRecoveryRequestsByDIDRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRecoveryRequestsByDIDRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRecoveryRequestsByDIDRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Did", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Did = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRecoveryRequestsByDIDResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRecoveryRequestsByDIDResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRecoveryRequestsByDIDResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Requests", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Requests = append(m.Requests, RecoveryRequest{})
			if err := m.Requests[len(m.Requests)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
