// SPDX-License-Identifier: Apache-2.0

package types

// Event keys for the institutions module.
const (
	EventTypeInstitutionRegistered = "institution_registered"
	EventTypeInstitutionRemoved    = "institution_removed"
	EventTypeInstitutionMinted     = "institution_minted"
	EventTypeInstitutionRedeemed   = "institution_redeemed"
	EventTypeAttestationPublished  = "attestation_published"
	EventTypeInstitutionFrozen     = "institution_frozen"
	EventTypeBackingShortfall      = "institution_backing_shortfall"
	EventTypeRoleGranted           = "institution_role_granted"
	EventTypeRoleRevoked           = "institution_role_revoked"
	EventTypeAppConfigSet          = "institution_app_config_set"
	EventTypeParamsSet             = "institution_params_set"
	EventTypeActionPending         = "institution_action_pending"
	EventTypeDepositKeySet         = "institution_deposit_key_set"
	EventTypeEmergencyRedemption   = "emergency_redemption_set"
	EventTypePenaltyEscrowed       = "institution_penalty_escrowed"
	EventTypeFxEntryRequested      = "fx_entry_requested"
	EventTypeFxEntryGuaranteed     = "fx_entry_guaranteed"
	EventTypeFxEntryDeclined       = "fx_entry_declined"
	EventTypeFxEntryFinalized      = "fx_entry_finalized"

	AttributeKeyInstitution = "institution"
	AttributeKeyGrantee     = "grantee"
	AttributeKeyRole        = "role"
	AttributeKeyAction      = "action"
	AttributeKeyApprovals   = "approvals"
	AttributeKeyThreshold   = "threshold"
	AttributeKeyDepositRef  = "deposit_ref"
	AttributeKeyAdmin       = "admin"
	AttributeKeyRecipient   = "recipient"
	AttributeKeyHolder      = "holder"
	AttributeKeyAmountToman = "amount_toman"
	AttributeKeyMintedUphi  = "minted_uphi"
	AttributeKeyBurnedUphi  = "burned_uphi"
	AttributeKeyPayoutToman = "payout_toman"
	// redeemed_uphi == burned_uphi + protocol_fee_uphi + penalty_uphi + dust_uphi; only burned_uphi leaves supply.
	AttributeKeyRedeemedUphi    = "redeemed_uphi"
	AttributeKeyProtocolFeeUphi = "protocol_fee_uphi"
	AttributeKeyPenaltyUphi     = "penalty_uphi"
	AttributeKeyDustUphi        = "dust_uphi"
	// On mint: minted_uphi == recipient_uphi + protocol_fee_uphi.
	AttributeKeyRecipientUphi   = "recipient_uphi"
	AttributeKeyAttestedReserve = "attested_reserve"
	AttributeKeyLastAttestedAt  = "last_attested_at"
	AttributeKeyFrozen          = "frozen"
	AttributeKeyShortfallToman  = "shortfall_toman"
	AttributeKeyInstitutionType = "institution_type"
	AttributeKeyFxCurrency      = "fx_currency"
	AttributeKeyFxAmount        = "fx_amount"
	AttributeKeyFxTxRef         = "fx_tx_ref"
	AttributeKeyFxID            = "fx_id"
	AttributeKeyApplicant       = "applicant"
	AttributeKeyGuarantor       = "guarantor_id"
	AttributeKeyProposalID      = "proposal_id"
	AttributeKeyActive          = "active"
	AttributeKeyStartedAt       = "started_at"
	AttributeKeyEscrowedUphi    = "escrowed_uphi"
	AttributeKeyReason          = "reason"
)
