// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: phi/institutions/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3ca40fb88818bd9, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

type QueryParamsResponse struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3ca40fb88818bd9, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryInstitutionRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryInstitutionRequest) Reset()         { *m = QueryInstitutionRequest{} }
func (m *QueryInstitutionRequest) String() string { return proto.CompactTextString(m) }
func (*QueryInstitutionRequest) ProtoMessage()    {}
func (*QueryInstitutionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3ca40fb88818bd9, []int{2}
}
func (m *QueryInstitutionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryInstitutionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryInstitutionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryInstitutionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInstitutionRequest.Merge(m, src)
}
func (m *QueryInstitutionRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryInstitutionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInstitutionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInstitutionRequest proto.InternalMessageInfo

func (m *QueryInstitutionRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type QueryInstitutionResponse struct {
	Institution Institution `protobuf:"bytes,1,opt,name=institution,proto3" json:"institution"`
	// COMPUTED at read time from block_time vs institution.last_attested_at against the effective
	// threshold. It is derived, never stored: the §4.6 gate does not flip Status, so this is the only
	// place the staleness is visible without replaying the mint gate.
	AttestationStale bool `protobuf:"varint,2,opt,name=attestation_stale,json=attestationStale,proto3" json:"attestation_stale,omitempty"`
	// The threshold actually applied (seconds) — the stricter of the protocol floor and the
	// institution's own max_vault_attestation_latency_s. 0 = the gate is disabled.
	EffectiveStalenessSeconds uint64 `protobuf:"varint,3,opt,name=effective_staleness_seconds,json=effectiveStalenessSeconds,proto3" json:"effective_staleness_seconds,omitempty"`
}

func (m *QueryInstitutionResponse) Reset()         { *m = QueryInstitutionResponse{} }
func (m *QueryInstitutionResponse) String() string { return proto.CompactTextString(m) }
func (*QueryInstitutionResponse) ProtoMessage()    {}
func (*QueryInstitutionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3ca40fb88818bd9, []int{3}
}
func (m *QueryInstitutionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryInstitutionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryInstitutionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryInstitutionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInstitutionResponse.Merge(m, src)
}
func (m *QueryInstitutionResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryInstitutionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInstitutionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInstitutionResponse proto.InternalMessageInfo

func (m *QueryInstitutionResponse) GetInstitution() Institution {
	if m != nil {
		return m.Institution
	}
	return Institution{}
}

func (m *QueryInstitutionResponse) GetAttestationStale() bool {
	if m != nil {
		return m.AttestationStale
	}
	return false
}

func (m *QueryInstitutionResponse) GetEffectiveStalenessSeconds() uint64 {
	if m != nil {
		return m.EffectiveStalenessSeconds
	}
	return 0
}

type QueryInstitutionsRequest struct {
}

func (m *QueryInstitutionsRequest) Reset()         { *m = QueryInstitutionsRequest{} }
func (m *QueryInstitutionsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryInstitutionsRequest) ProtoMessage()    {}
func (*QueryInstitutionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3ca40fb88818bd9, []int{4}
}
func (m *QueryInstitutionsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryInstitutionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryInstitutionsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryInstitutionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInstitutionsRequest.Merge(m, src)
}
func (m *QueryInstitutionsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryInstitutionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInstitutionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInstitutionsRequest proto.InternalMessageInfo

type QueryInstitutionsResponse struct {
	Institutions []Institution `protobuf:"bytes,1,rep,name=institutions,proto3" json:"institutions"`
}

func (m *QueryInstitutionsResponse) Reset()         { *m = QueryInstitutionsResponse{} }
func (m *QueryInstitutionsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryInstitutionsResponse) ProtoMessage()    {}
func (*QueryInstitutionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3ca40fb88818bd9, []int{5}
}
func (m *QueryInstitutionsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryInstitutionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryInstitutionsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryInstitutionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInstitutionsResponse.Merge(m, src)
}
func (m *QueryInstitutionsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryInstitutionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInstitutionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInstitutionsResponse proto.InternalMessageInfo

func (m *QueryInstitutionsResponse) GetInstitutions() []Institution {
	if m != nil {
		return m.Institutions
	}
	return nil
}

type QuerySolvencyRequest struct {
}

func (m *QuerySolvencyRequest) Reset()         { *m = QuerySolvencyRequest{} }
func (m *QuerySolvencyRequest) String() string { return proto.CompactTextString(m) }
func (*QuerySolvencyRequest) ProtoMessage()    {}
func (*QuerySolvencyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3ca40fb88818bd9, []int{6}
}
func (m *QuerySolvencyRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySolvencyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySolvencyRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySolvencyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySolvencyRequest.Merge(m, src)
}
func (m *QuerySolvencyRequest) XXX_Size() int {
	return m.Size()
}
func (m *QuerySolvencyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySolvencyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySolvencyRequest proto.InternalMessageInfo

type QuerySolvencyResponse struct {
	// total supply (uphi)
	TotalSupplyUphi string `protobuf:"bytes,1,opt,name=total_supply_uphi,json=totalSupplyUphi,proto3" json:"total_supply_uphi,omitempty"`
	// sum of all institutions' reserves (Toman)
	SumVaultBalanceToman string `protobuf:"bytes,2,opt,name=sum_vault_balance_toman,json=sumVaultBalanceToman,proto3" json:"sum_vault_balance_toman,omitempty"`
	// whether the solvency invariant holds
	Solvent bool `protobuf:"varint,3,opt,name=solvent,proto3" json:"solvent,omitempty"`
}

func (m *QuerySolvencyResponse) Reset()         { *m = QuerySolvencyResponse{} }
func (m *QuerySolvencyResponse) String() string { return proto.CompactTextString(m) }
func (*QuerySolvencyResponse) ProtoMessage()    {}
func (*QuerySolvencyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3ca40fb88818bd9, []int{7}
}
func (m *QuerySolvencyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySolvencyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySolvencyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySolvencyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySolvencyResponse.Merge(m, src)
}
func (m *QuerySolvencyResponse) XXX_Size() int {
	return m.Size()
}
func (m *QuerySolvencyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySolvencyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySolvencyResponse proto.InternalMessageInfo

func (m *QuerySolvencyResponse) GetTotalSupplyUphi() string {
	if m != nil {
		return m.TotalSupplyUphi
	}
	return ""
}

func (m *QuerySolvencyResponse) GetSumVaultBalanceToman() string {
	if m != nil {
		return m.SumVaultBalanceToman
	}
	return ""
}

func (m *QuerySolvencyResponse) GetSolvent() bool {
	if m != nil {
		return m.Solvent
	}
	return false
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "phi.institutions.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "phi.institutions.QueryParamsResponse")
	proto.RegisterType((*QueryInstitutionRequest)(nil), "phi.institutions.QueryInstitutionRequest")
	proto.RegisterType((*QueryInstitutionResponse)(nil), "phi.institutions.QueryInstitutionResponse")
	proto.RegisterType((*QueryInstitutionsRequest)(nil), "phi.institutions.QueryInstitutionsRequest")
	proto.RegisterType((*QueryInstitutionsResponse)(nil), "phi.institutions.QueryInstitutionsResponse")
	proto.RegisterType((*QuerySolvencyRequest)(nil), "phi.institutions.QuerySolvencyRequest")
	proto.RegisterType((*QuerySolvencyResponse)(nil), "phi.institutions.QuerySolvencyResponse")
}

func init() { proto.RegisterFile("phi/institutions/query.proto", fileDescriptor_f3ca40fb88818bd9) }

var fileDescriptor_f3ca40fb88818bd9 = []byte{
	// 615 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xc1, 0x6e, 0xd3, 0x4c,
	0x14, 0x85, 0x33, 0x69, 0xff, 0xfe, 0xed, 0xb4, 0x82, 0x76, 0x08, 0xd4, 0x35, 0xc5, 0x58, 0x2e,
	0x2d, 0x6d, 0xa3, 0xc6, 0x52, 0x10, 0x2c, 0x59, 0x44, 0x42, 0x50, 0x09, 0xa4, 0xe0, 0x00, 0x0b,
	0x36, 0xd6, 0xc4, 0x99, 0xc6, 0x23, 0x39, 0x1e, 0x37, 0x33, 0x0e, 0x44, 0x08, 0x21, 0xf1, 0x02,
	0x80, 0xe0, 0x1d, 0x78, 0x95, 0xae, 0x50, 0x25, 0x36, 0xac, 0x10, 0x4a, 0x78, 0x10, 0xe4, 0xf1,
	0x24, 0x38, 0x31, 0x6d, 0xb3, 0x8b, 0xe7, 0x7c, 0x73, 0xcf, 0xb9, 0x37, 0xd7, 0x86, 0x9b, 0x91,
	0x4f, 0x6d, 0x1a, 0x72, 0x41, 0x45, 0x2c, 0x28, 0x0b, 0xb9, 0x7d, 0x1c, 0x93, 0x6e, 0xbf, 0x12,
	0x75, 0x99, 0x60, 0x68, 0x35, 0xf2, 0x69, 0x25, 0xab, 0xea, 0xa5, 0x36, 0x6b, 0x33, 0x29, 0xda,
	0xc9, 0xaf, 0x94, 0xd3, 0x37, 0xdb, 0x8c, 0xb5, 0x03, 0x62, 0xe3, 0x88, 0xda, 0x38, 0x0c, 0x99,
	0xc0, 0x92, 0x56, 0xea, 0x56, 0xce, 0x23, 0xfb, 0x90, 0x42, 0x56, 0x09, 0xa2, 0xa7, 0x89, 0x73,
	0x1d, 0x77, 0x71, 0x87, 0x3b, 0xe4, 0x38, 0x26, 0x5c, 0x58, 0x4f, 0xe0, 0x95, 0x89, 0x53, 0x1e,
	0xb1, 0x90, 0x13, 0x74, 0x0f, 0x2e, 0x44, 0xf2, 0x44, 0x03, 0x26, 0xd8, 0x5d, 0xae, 0x6a, 0x95,
	0xe9, 0xa0, 0x95, 0xf4, 0x46, 0x6d, 0xfe, 0xe4, 0xe7, 0xcd, 0x82, 0xa3, 0x68, 0x6b, 0x0f, 0xae,
	0xcb, 0x72, 0x87, 0x7f, 0x49, 0xe5, 0x84, 0x2e, 0xc1, 0x22, 0x6d, 0xc9, 0x72, 0x4b, 0x4e, 0x91,
	0xb6, 0xac, 0x6f, 0x00, 0x6a, 0x79, 0x56, 0xf9, 0x3f, 0x80, 0xcb, 0x19, 0x33, 0x15, 0xe2, 0x46,
	0x3e, 0x44, 0xe6, 0xae, 0x4a, 0x92, 0xbd, 0x87, 0xca, 0x70, 0x0d, 0x0b, 0x41, 0x78, 0x3a, 0x2e,
	0x97, 0x0b, 0x1c, 0x10, 0xad, 0x68, 0x82, 0xdd, 0x45, 0x67, 0x35, 0x23, 0x34, 0x92, 0x73, 0x74,
	0x1f, 0x5e, 0x27, 0x47, 0x47, 0xc4, 0x13, 0xb4, 0x47, 0x52, 0x34, 0x24, 0x9c, 0xbb, 0x9c, 0x78,
	0x2c, 0x6c, 0x71, 0x6d, 0xce, 0x04, 0xbb, 0xf3, 0xce, 0xc6, 0x18, 0x69, 0x8c, 0x88, 0x46, 0x0a,
	0x58, 0x7a, 0xbe, 0x9f, 0xf1, 0x98, 0x5b, 0x70, 0xe3, 0x1f, 0x9a, 0x6a, 0xf6, 0x21, 0x5c, 0xc9,
	0x36, 0xa5, 0x01, 0x73, 0x6e, 0xd6, 0x6e, 0x27, 0x2e, 0x5a, 0xd7, 0x60, 0x49, 0xba, 0x34, 0x58,
	0xd0, 0x23, 0xa1, 0xd7, 0x1f, 0xb9, 0x7f, 0x01, 0xf0, 0xea, 0x94, 0xa0, 0xac, 0xf7, 0xe1, 0x9a,
	0x60, 0x02, 0x07, 0x2e, 0x8f, 0xa3, 0x28, 0xe8, 0xbb, 0x71, 0xe4, 0x53, 0xf5, 0x1f, 0x5d, 0x96,
	0x42, 0x43, 0x9e, 0x3f, 0x8f, 0x7c, 0x8a, 0xee, 0xc2, 0x75, 0x1e, 0x77, 0xdc, 0x1e, 0x8e, 0x03,
	0xe1, 0x36, 0x71, 0x80, 0x43, 0x8f, 0xb8, 0x82, 0x75, 0x70, 0x28, 0x47, 0xba, 0xe4, 0x94, 0x78,
	0xdc, 0x79, 0x91, 0xa8, 0xb5, 0x54, 0x7c, 0x96, 0x68, 0x48, 0x83, 0xff, 0x73, 0x69, 0x2b, 0xe4,
	0x08, 0x17, 0x9d, 0xd1, 0x63, 0xf5, 0xeb, 0x3c, 0xfc, 0x4f, 0xc6, 0x42, 0xaf, 0xe0, 0x42, 0xba,
	0x4e, 0xe8, 0x56, 0xbe, 0xeb, 0xfc, 0xd6, 0xea, 0xdb, 0x17, 0x50, 0x69, 0x77, 0x96, 0xf9, 0xfe,
	0xfb, 0xef, 0xcf, 0x45, 0x1d, 0x69, 0x76, 0xee, 0x05, 0x49, 0xf7, 0x15, 0x7d, 0x02, 0x70, 0x39,
	0x33, 0x55, 0xb4, 0x77, 0x46, 0xe1, 0xfc, 0x3e, 0xeb, 0xfb, 0xb3, 0xa0, 0x2a, 0x48, 0x59, 0x06,
	0xd9, 0x46, 0x5b, 0xf6, 0xb9, 0x6f, 0xaa, 0xfd, 0x86, 0xb6, 0xde, 0xa2, 0x0f, 0x00, 0xae, 0x64,
	0xf7, 0x04, 0xcd, 0xe0, 0x34, 0x9e, 0x4c, 0x79, 0x26, 0x56, 0xc5, 0xda, 0x91, 0xb1, 0x4c, 0x64,
	0x9c, 0x1f, 0x0b, 0xbd, 0x83, 0x8b, 0xa3, 0xcd, 0x41, 0x3b, 0x67, 0x18, 0x4c, 0xed, 0x9c, 0x7e,
	0xfb, 0x42, 0x4e, 0x85, 0xb0, 0x64, 0x88, 0x4d, 0xa4, 0xe7, 0x43, 0x70, 0xc5, 0xd6, 0x1e, 0x9f,
	0x0c, 0x0c, 0x70, 0x3a, 0x30, 0xc0, 0xaf, 0x81, 0x01, 0x3e, 0x0e, 0x8d, 0xc2, 0xe9, 0xd0, 0x28,
	0xfc, 0x18, 0x1a, 0x85, 0x97, 0xd5, 0x36, 0x15, 0x7e, 0xdc, 0xac, 0x78, 0xac, 0x63, 0xd7, 0x59,
	0x57, 0x1c, 0xd4, 0x1f, 0x1d, 0x26, 0x85, 0x0e, 0x3c, 0x1f, 0xd3, 0xd0, 0x7e, 0x3d, 0x59, 0x50,
	0xf4, 0x23, 0xc2, 0x9b, 0x0b, 0xf2, 0x83, 0x78, 0xe7, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1b,
	0xee, 0x5d, 0x39, 0x9b, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Params returns the module's current parameters.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Institution returns an institution by ID.
	Institution(ctx context.Context, in *QueryInstitutionRequest, opts ...grpc.CallOption) (*QueryInstitutionResponse, error)
	// Institutions lists all registered institutions.
	Institutions(ctx context.Context, in *QueryInstitutionsRequest, opts ...grpc.CallOption) (*QueryInstitutionsResponse, error)
	// Solvency returns the global solvency summary (TotalSupply and Σ vault_balance).
	Solvency(ctx context.Context, in *QuerySolvencyRequest, opts ...grpc.CallOption) (*QuerySolvencyResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/phi.institutions.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Institution(ctx context.Context, in *QueryInstitutionRequest, opts ...grpc.CallOption) (*QueryInstitutionResponse, error) {
	out := new(QueryInstitutionResponse)
	err := c.cc.Invoke(ctx, "/phi.institutions.Query/Institution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Institutions(ctx context.Context, in *QueryInstitutionsRequest, opts ...grpc.CallOption) (*QueryInstitutionsResponse, error) {
	out := new(QueryInstitutionsResponse)
	err := c.cc.Invoke(ctx, "/phi.institutions.Query/Institutions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Solvency(ctx context.Context, in *QuerySolvencyRequest, opts ...grpc.CallOption) (*QuerySolvencyResponse, error) {
	out := new(QuerySolvencyResponse)
	err := c.cc.Invoke(ctx, "/phi.institutions.Query/Solvency", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Params returns the module's current parameters.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Institution returns an institution by ID.
	Institution(context.Context, *QueryInstitutionRequest) (*QueryInstitutionResponse, error)
	// Institutions lists all registered institutions.
	Institutions(context.Context, *QueryInstitutionsRequest) (*QueryInstitutionsResponse, error)
	// Solvency returns the global solvency summary (TotalSupply and Σ vault_balance).
	Solvency(context.Context, *QuerySolvencyRequest) (*QuerySolvencyResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Institution(ctx context.Context, req *QueryInstitutionRequest) (*QueryInstitutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Institution not implemented")
}
func (*UnimplementedQueryServer) Institutions(ctx context.Context, req *QueryInstitutionsRequest) (*QueryInstitutionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Institutions not implemented")
}
func (*UnimplementedQueryServer) Solvency(ctx context.Context, req *QuerySolvencyRequest) (*QuerySolvencyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Solvency not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phi.institutions.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Institution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryInstitutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Institution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phi.institutions.Query/Institution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Institution(ctx, req.(*QueryInstitutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Institutions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryInstitutionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Institutions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phi.institutions.Query/Institutions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Institutions(ctx, req.(*QueryInstitutionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Solvency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySolvencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Solvency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phi.institutions.Query/Solvency",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Solvency(ctx, req.(*QuerySolvencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "phi.institutions.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Institution",
			Handler:    _Query_Institution_Handler,
		},
		{
			MethodName: "Institutions",
			Handler:    _Query_Institutions_Handler,
		},
		{
			MethodName: "Solvency",
			Handler:    _Query_Solvency_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "phi/institutions/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryInstitutionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryInstitutionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryInstitutionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryInstitutionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryInstitutionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryInstitutionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EffectiveStalenessSeconds != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.EffectiveStalenessSeconds))
		i--
		dAtA[i] = 0x18
	}
	if m.AttestationStale {
		i--
		if m.AttestationStale {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.Institution.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryInstitutionsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryInstitutionsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryInstitutionsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryInstitutionsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryInstitutionsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryInstitutionsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Institutions) > 0 {
		for iNdEx := len(m.Institutions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Institutions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QuerySolvencyRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySolvencyRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySolvencyRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QuerySolvencyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySolvencyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySolvencyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Solvent {
		i--
		if m.Solvent {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.SumVaultBalanceToman) > 0 {
		i -= len(m.SumVaultBalanceToman)
		copy(dAtA[i:], m.SumVaultBalanceToman)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.SumVaultBalanceToman)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.TotalSupplyUphi) > 0 {
		i -= len(m.TotalSupplyUphi)
		copy(dAtA[i:], m.TotalSupplyUphi)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.TotalSupplyUphi)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryInstitutionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryInstitutionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Institution.Size()
	n += 1 + l + sovQuery(uint64(l))
	if m.AttestationStale {
		n += 2
	}
	if m.EffectiveStalenessSeconds != 0 {
		n += 1 + sovQuery(uint64(m.EffectiveStalenessSeconds))
	}
	return n
}

func (m *QueryInstitutionsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryInstitutionsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Institutions) > 0 {
		for _, e := range m.Institutions {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QuerySolvencyRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QuerySolvencyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TotalSupplyUphi)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.SumVaultBalanceToman)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Solvent {
		n += 2
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryInstitutionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryInstitutionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryInstitutionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryInstitutionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryInstitutionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryInstitutionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Institution", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Institution.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AttestationStale", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AttestationStale = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EffectiveStalenessSeconds", wireType)
			}
			m.EffectiveStalenessSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EffectiveStalenessSeconds |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryInstitutionsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryInstitutionsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryInstitutionsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryInstitutionsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryInstitutionsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryInstitutionsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Institutions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Institutions = append(m.Institutions, Institution{})
			if err := m.Institutions[len(m.Institutions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySolvencyRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySolvencyRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySolvencyRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySolvencyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySolvencyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySolvencyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalSupplyUphi", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalSupplyUphi = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SumVaultBalanceToman", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SumVaultBalanceToman = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Solvent", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Solvent = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
